### ISSUE TITLE
Shift clicking upgrades don't work well.

### ISSUE THREAD

**Issue by ruifung** [ExtraCells/ExtraCells2#123]
For example. shift clicking upgrades from the inventory moves it to the hotbar - and shift clicking from hotbar moves it into the upgrade slots.

It is also impossible to shift click upgrades out from the upgrade slots, and upgrades don't drop when the bus is wrenched.

**Comment by sww1235** [comment]
Also when shiftclicking acceleration cards into busses (inport/output/storage) the entire stack of upgrades in your inventory will vanish
