### ISSUE TITLE
a small bug in FluidCellHandler.java file

### ISSUE THREAD

**Issue by chentao807** [ExtraCells/ExtraCells2#151]
line 85
inventory.usedTypes() == inventory.totalBytes()
maybe
inventory.usedTypes() == inventory.totalTypes()

**Comment by RAnders00** [comment]
[This is it](https://github.com/ExtraCells/ExtraCells2/blob/rv2/src/main/scala/extracells/util/FluidCellHandler.java#L53)

See #211, https://github.com/RAnders00/ExtraCells2/commit/742e76a34a632136ae31f96ce3ae896eda48f9a7
