### ISSUE TITLE
ME Chest for fluids Crash

### ISSUE THREAD

**Issue by Earhbound** [ExtraCells/ExtraCells2#154]
BC Pump pumping oil --> BC Tank --> fluid importbus --> 2x acceleration card --> ME chest -->Fluid storage cell --> vibr. chamber.

crashed instantly without a crash report.

**Comment by DrummerMC** [comment]
log file?

**Comment by Earhbound** [comment]
sorry bout that, cant find the right one. was hunting down another one and generated too many.
but that bug should be reproducable. if not, let me know and i ll provide further information.
