### ISSUE TITLE
Black Hole Storage Support

### ISSUE THREAD

**Issue by Keridos** [ExtraCells/ExtraCells2#157]
Could you please add in support for SuperMassiveTechs Black Hole Storage?
They can store 2^40 miliBuckets of Fluid.

Currently it does not recognize them correctly, it only lists some fluids and they do not have the correct amount listed.

**Comment by Soaryn** [comment]
2^40 is far beyond max Int. A fluidStack is a fluid and an amount in an Int. Not much can be done for it unless it is compressed

**Comment by M3gaFr3ak** [comment]
I think IAEFluidStack allows a long... Then the machine would have to use fake values for machines asking for the amount of stuff in it as fluidstacks...
