### ISSUE TITLE
Crafting of Recipe wont trigger creation of required fluids.

### ISSUE THREAD

**Issue by PhoenixMage** [ExtraCells/ExtraCells2#174]
Hi,

I am trying to automate the filling of empty tesseract frames using EC2.

If I create a recipe to fill an empty tesseract frame by having the empty tesseract frame and a bucket of resonant ender create a full tesseract frame and put in in a ME Fluid Interface attached to a fluid transposer it works.

If I dont have an empty tesseract frame, it will craft one.

However if I have no resonant ender in an fluid drive despite having a recipe to create it in a ME Fluid interface connected to a magma crucible it will not create it, it doesnt show up as a step in the Crafting Plan.

If I execute the crafting recipe for the liquid ender prior to kicking off the tesseract frame job everything works as planned as long as I cancel the job as it doesnt 'see' the bucket of ender as it goes straight into the fluid drive.

I guess the bottom line is that the crafting of the resonant ender isn't triggered in a crafting plan.

I am running ExtraCells-1.7.10-2.2.53b82.jar

**Comment by jacesilverleaf** [comment]
I have a similar issue. I'm trying to make it so I can autocraft buckets of resonant ender to make enderium dust, but it won't do it. I have a recipe for the bucket - an empty bucket into a bucket of resonant ender, but no matter which block I use it on (molecular assembler or fluid assembler), it won't make it. I have multiple CPUs for crafting, and they show it trying to craft, but it never does. And I have the resonant ender stored in my fluid cells.

**Comment by ruifung** [comment]
Duplicate #8
