### ISSUE TITLE
Console posts error

### ISSUE THREAD

**Issue by Cuppycake** [ExtraCells/ExtraCells2#175]
http://pastebin.com/CkbK7WyT

Causes an extreme TPS drop on the server when this happens. Also watching the CPU usage of my server, it jumps above 100%. 

Running forge 1291

Applied Energistics2 rv1-stable-1
Extra Cells 2.1.37b62
EnderIO 2.2.8.349

**Comment by DrummerMC** [comment]
Try the newest rv2 Version

**Comment by Cuppycake** [comment]
So I have to update the main mod in the package to fix the addon? >.>

**Comment by DrummerMC** [comment]
I think I have fix this in rv2

**Comment by Cuppycake** [comment]
Alrighty Ill go ahead and patch it up and see if that helps. If you think you have fixed this in the new version would it be safe to say that it is whats causing the spike in CPU usage? Or may I have another issue on my box? :P
