### ISSUE TITLE
Autocrafting of Fluids

### ISSUE THREAD

**Issue by krakentoa** [ExtraCells/ExtraCells2#182]
Right now fluid level emitters seem to be a way to always keep a buffer of a fluid ready.
Is there any way to autocraft lava on demand, e.g. a pattern like "cobble->lava" in magma crucible?

**Comment by lambaline** [comment]
I was wondering the same thing, but for enderpearls -> resonant ender for making tesseracts

**Comment by DrummerMC** [comment]
This doesn't work.
Sorry
