### ISSUE TITLE
Fluid export terminal

### ISSUE THREAD

**Issue by kayila** [ExtraCells/ExtraCells2#184]
I'm using Extra Cells to control my Tinker's Construct smeltery, and find that it would be very helpful to have a fluid export terminal block, one that has a built in export terminal and fluid terminal such that the fluid terminal could dynamically pump out fluid based on what the user had selected at the screen. Sort of a 'dial a fluid'

Right now it can be done by taking a bucket out of a fluid terminal, putting it into the export bus, then putting it back in the terminal, but this is difficult when you don't have a bucket's worth of fluid.

**Comment by ruifung** [comment]
This would be useful, its similar to the Fluid Request Pipe from LP.
