### ISSUE TITLE
Issue when clicking on the 16384k Storage Cell in my inventory

### ISSUE THREAD

**Issue by KamranMackey** [ExtraCells/ExtraCells2#187]
For some reason, this error happens whenever I click on that Storage Cell in my inventory: https://paste.ee/p/PCytP

I'm not sure what's causing it.

**Comment by shobu9** [comment]
Caused by: com.google.gson.stream.MalformedJsonException: Expected name at line 4 column 2 

Weird the crash happens usually on creative mod tough 
I don't think there's anything to stress about...

**Comment by KamranMackey** [comment]
@shobu9 I was in creative mode. I think it might of been because my inventory was full or something, which might've been what caused the crash.
