### ISSUE TITLE
Fluids in formatted cells not accessible (2.2.63b94)

### ISSUE THREAD

**Issue by rowlock** [ExtraCells/ExtraCells2#192]
Upgraded my server last night, and currently any fluid stored in a formatted cell cannot be extracted via the fluid terminal, or fluid export buses.

Placing a bucket in the fluid terminal results in the bucket sitting in the input slot and not moving.

Portable tanks will receive the fluid ID and move to the output slot, but will not receive any fluid volume. The tank then becomes locked to the fluid type despite being "empty" and cannot be filled with other fluids.

Fluids that are stored in unformatted cells continue to behave normally.

Placing a formatted cell in the ME IO port, in an attempt to move the fluid to a working cell, also results in the cell just sitting there and not moving any fluid.

Any ideas?

I'm on ExtraCells-1.7.10-2.2.63b94 and appliedenergistics2-rv2-beta-18.

Thanks!

**Comment by rowlock** [comment]
After a little more testing, it appears that those formatted cells also no longer accept fluid input. If I add more fluid to the system it goes onto some other unformatted cell instead.

**Comment by XFactHD** [comment]
Try to reformat the cell, I have had the same problem after an update and reformatting solved the problem.
