### ISSUE TITLE
NEI Recipes disappears.

### ISSUE THREAD

**Issue by Cooolaid** [ExtraCells/ExtraCells2#195]
I have AE2 RV2 Beta 26, 27 & 28.
When installing your mod alongside the AE versions listed above, NEI recipes completely disappears.
When your mod is taken out, NEI returns back to normal. 

Also, Just wanted to inform you.
Its a bit difficult to figure out which of your EC mod is suppose to go with which version of AE (exactly).
Thank you. :D

**Comment by DrummerMC** [comment]
NEI version???

**Comment by Cooolaid** [comment]
v1.7.10 - NEI v1.0.4.95 Universal - & - v1.0.4.83-universal

**Comment by ChromeMystic** [comment]
I can confirm this error, I tested it with multiple NEI versions, Extra Cells just seems to disable NEI ingame.

**Comment by M3gaFr3ak** [comment]
which version of the chickenbones library are you using?

**Comment by ChromeMystic** [comment]
CodeChickenCore-1.7.10-1.0.4.35-universal and CodeChickenLib-1.7.10-1.1.3.127-universal if that helps you

**Comment by DrummerMC** [comment]
I have testet it with the newes nei and CodeChickenCore version on curseforge and it works

**Comment by DrummerMC** [comment]
try this version:
http://shadowcity.net:8080/job/ecrv2/111/

**Comment by xJon** [comment]
I had no problem with NEI with the latest version (68). Now after Forge is updated, which I'm not gonna use because it broke other mods, I can't update ExtraCells?
