### ISSUE TITLE
Can not load world

### ISSUE THREAD

**Issue by ultrasn0w** [ExtraCells/ExtraCells2#198]
Hey there,
I updated ExtraCells to the latest Jenkins version today (http://shadowcity.net:8080/job/ecrv2/115/) and now I cannot load a world, the log says this:
http://pastebin.com/YFTqAG1q
Using NotEnoughItems-1.7.10-1.0.4.95-universal & Forge 10.13.2.1352.

Greetings
ultrasn0w

Btw:
I'm not able to update to newer Forge Versions because not all mods have adapted to the new Forge Fluid System introduced in 10.13.3.1355.

**Comment by DrummerMC** [comment]
I will give you a link with a compatible version

**Comment by DrummerMC** [comment]
this should work:
https://www.dropbox.com/s/tclhdhmfbiot8ya/ExtraCells-1.7.10-2.2.68bNIGHTLY.jar?dl=0

**Comment by ultrasn0w** [comment]
Thank you very much <3, trying this now :)

**Comment by ultrasn0w** [comment]
And it works, thank you again!
