### ISSUE TITLE
Heads-Up minor API change

### ISSUE THREAD

**Issue by thatsIch** [ExtraCells/ExtraCells2#200]
I have a PR idle which does change the API a bit, while still offering the old support through deprecation.

https://github.com/thatsIch/Applied-Energistics-2/blob/b-1186-disassembling-storage-missing-upgrades/src/api/java/appeng/api/implementations/items/IStorageCell.java#L65-L75

nothing major, but since you have tons of cells, might be interesting to keep it on the radar as a to-do

**Comment by DrummerMC** [comment]
Will implement it next weekend

**Comment by thatsIch** [comment]
no need to hurry, `@deprecated` stuff will not be removed before **rv3 alpha**

**Comment by thatsIch** [comment]
Its in, have fun. Its not actually called right now, so it will not break if you do not implement it.
