### ISSUE TITLE
Kicked out of world after creating with 2.2.69

### ISSUE THREAD

**Issue by Amaxter** [ExtraCells/ExtraCells2#201]
http://hastebin.com/kagixayago.vbs

**Comment by Dudesfield** [comment]
Im having the same issue, but my crash log contains nothing out of the ordinary unlike yours

**Comment by Phyn** [comment]
According to the posted log, the issue has nothing to do with this mod.

**Comment by Belgabor** [comment]
Are you using a Forge 10.13.2.X version (pre fluid update)? Extra Cells after 2.2.67 need forge 10.13.3.X.
