### ISSUE TITLE
Extracells

### ISSUE THREAD

**Issue by excelcrafter** [ExtraCells/ExtraCells2#202]
server: cauldron 1307 + many mods

client: forge 1291 + many mods

everything works fine, till I add MineFactoryReloaded-[1.7.10]2.8.0-104.jar
then: 

http://pastebin.com/szggiXfB

I am using ExtraCells-1.7.10-2.2.68bNIGHTLY because this version ExtraCells-1.7.10-2.2.69bNIGHTLY doesnt work at all with setup I have...

**Comment by DrummerMC** [comment]
See #198
