### ISSUE TITLE
client crash

### ISSUE THREAD

**Issue by Elfrio22** [ExtraCells/ExtraCells2#204]
help me, my client always crashes just after the world has loaded, the log doesn't look abnormal, and I am using the latest version of forge and AE2.
it's not crashing out of the game but just kicks me out, because a fatal error occured or something like that.

**Comment by zeryl** [comment]
Seeing the same, mostly stock DW20 build.  Here is the server log for the time: http://pastebin.com/iWhYSTs6

And client:
http://pastebin.com/inEF2Gyq

I can provide more info upon request.

Edit: Sorry, forgot to mention, this is with a direct build from current github code as of 4/22

**Comment by benblank** [comment]
Minecraft Forge 1.7.10-10.13.3.1358 introduced breaking changes to the fluids API.  If you want to use the recommended version of Forge, you'll need to roll back to ExtraCells 2.2.68.  If you want to use the latest version of Extra Cells, you'll need to update to Forge 1.7.10-10.13.3.1358 or higher.

**Comment by zeryl** [comment]
That worked, thank you!

**Comment by Elfrio22** [comment]
but when  update my forge to 13.3.1358, I cant open my worlds because it is in an "invalid state".
and the version that I use for extra cells doesn't have everything that is on the wiki.
