### ISSUE TITLE
ru_RU needs update

### ISSUE THREAD

**Issue by Kanol** [ExtraCells/ExtraCells2#208]
![bandicam 2015-04-26 19-19-13-805](https://cloud.githubusercontent.com/assets/10697310/7337609/409e6126-ec49-11e4-927b-3ba3d9834425.jpg)
Russian translate looks like this since the lastest update 2.2.69 beta
Here is a link for updated file(new names are translated too) translated by me http://www.mediafire.com/download/kruy7vg3ka3t4yp/ru_RU.lang
If there is something wrong you can write me kanolcraft@gmail.com

**Comment by labpaw** [comment]
Works just fine for me. Try this version: http://shadowcity.net:8080/job/ecrv2/117/
