### ISSUE TITLE
Is there a reason why you display 1KiloB instead of a number like 1104?

### ISSUE THREAD

**Issue by Euphoreich** [ExtraCells/ExtraCells2#210]
It's frustrating not knowing if you have 1001 buckets or 1999, you can have almost double the amount and no way to tell the difference. Can you guys change it so we can see numbers sub 100Kb? Or even 10Kb would be a dramatic improvement.

**Comment by bunnyman14** [comment]
If you hold shift, it will show the EXACT amount. At least, it should.

**Comment by Euphoreich** [comment]
Mmmm, not for me in tppi2, and i've tried unbinding everything else bound to shift, which was just vanilla sneak.

**Comment by Euphoreich** [comment]
Found out there was a config option for this, but just a suggestion would be to by default move from mb to buckets after 9999 mb, and then from buckets to kb after 9999 buckets.
