### ISSUE TITLE
How to craft fluids?

### ISSUE THREAD

**Issue by RAnders00** [ExtraCells/ExtraCells2#212]
I want to create a crafting recipe that turns 1 redstone into 100 mb of destabilized redstone.

I know that I can use portable tanks etc. to simulate a fluid in patterns that use fluids and that you the have to pu it into the fluid interface's pattern slots.

I tried a recipe that says 1 Redstone -> Portable Tank with 100 mb of destabillized Redstone, but it did not work.

How is it done?

**Comment by rbuckton** [comment]
According to #182, this is not possible. 

@DrummerMC, is there a plan to be able to support crafting of fluids in this fashion at some point in the future? Is there a way to raise an event to AE2 to indicate that a bucket-worth of a fluid has been added to the storage grid, to tell the Job it should advance to the next step, or would this require changes to fluid crafting? 

For example, one approach would be to add a new "Fluid Pattern Terminal" capable of including fluids of a specific volume (say, 1000mB of Resonant Ender) directly into a crafting pattern, without needing to include a container like a bucket. Or to have a processing pattern that produces a specific volume of a fluid, for use in an ME Interface. It would also be interesting to be able to request crafting of a specific fluid as well.
