### ISSUE TITLE
Dupe bug. EC ver. 2.2.69. AE2 ver. rv2-beta-28

### ISSUE THREAD

**Issue by sanovskiy** [ExtraCells/ExtraCells2#215]
Get portable fluid storage and put to input slot number (N) of Universal fluid cells with some contents.
Voila! You've got 64(input)+64(output)+N(in hand) cells with fluid. Plus N buckets of fluid in storage.

**Comment by YuRaNnNzZZ** [comment]
Confirmed, same versions - dupe works fine.

**Comment by itanshi** [comment]
I had a hard time understanding this post before I posted my bug report. I feel it is the same bug as again the storage fluid bus is at issue.
