### ISSUE TITLE
NEW FEATURE REQUEST - IC2 REACTOR IMPORT/EXPORT BUS

### ISSUE THREAD

**Issue by chloeprince** [ExtraCells/ExtraCells2#216]
It is difficult to automate either the regular reactor or the fluid nuclear reactor for IC2. That is because there is a 6x9 of slots in the GUI for internal components that can wear out. Automating their exact and precise replacement into and out of those slots are difficult because of the limitation of the existing EXPORT and IMPORT BUS for AE2.

It would be nice if you could add to this mod, a new set of IC2 specific IMPORT and EXPORT buses that would have a 6x9 grid in the GUI of slots that you could place the item in each slot you want the ME System to replace inside your IC2 Reactor or Fluid Reactor, automatically.

For instance - if the heat exchangers in my reactor setup wear out, I want a new export bus for AE2 to place replacements into those exact slots.

Right now, you can't do this because you can't tell it which slot to place an item in, and its limited to a 3x3 GUI slot in the Export or Import bus.

**Comment by XFactHD** [comment]
+1 for this idea. I am having the same problem, especially when my reactor runs on one quad cell and one dual cell.

**Comment by Alaberti** [comment]
This seems like a request for the AE2 team.

**Comment by XFactHD** [comment]
@Alaberti I don't think so because this is a very special and mod-specific feature request. What do you think @thatsIch ?

**Comment by thatsIch** [comment]
9 is generally the opt to go, cause a row in minecraft is defined like that. Such thing will not be implemented for just one use-case.

There should be a more general purpose motivation, also you need to think about it from their side:

maybe it is intended to be difficult to automate

**Comment by chloeprince** [comment]
The whole purpose of Mods, for Minecraft (or any game) is to change the intended mechanics of the original design of the game. 

Also, there are many mods that add in features that have one purpose. 

Maybe upgrade the existing export bus to allow you to place items in a specific slot number of a blocks inventory. Gregtech already has such a device, but it comes at the cost of adding Gregtech.
