### ISSUE TITLE
Certus Quartz Tank Rendering Glitch

### ISSUE THREAD

**Issue by TheJulianJES** [ExtraCells/ExtraCells2#225]
With: http://gyazo.com/2427964f4ba7100ab8a97f1720ab4b5e
Without: http://gyazo.com/9e7bcd79dd5c1d4ad54ccae3da3ac288

**Comment by TheJulianJES** [comment]
Only on "Fancy" graphic setting

**Comment by Nedelosk** [comment]
Fixed in 1.10.
