### ISSUE TITLE
Filled an empty bedrockium drum using a 67 bucket selection

### ISSUE THREAD

**Issue by itanshi** [ExtraCells/ExtraCells2#226]
An unlisted video is available by request. This is on version 2.2.68 and 1408 forge, multiplayer only. (fixed on single player)

**Comment by ImKonor** [comment]
Can confirm this works on Forge v. 1395, both multiplayer and single player.

**Comment by scifibob** [comment]
There is a problem using drums in the terminal.
You can easilly fill/empty a stack of bedrockian drums, and once they are filled/emptied, there seems to be a problem with them being "ghost items".
Maybe a NBT problem, I don't know what extra properties a drum has, but it's mostly impossible to move/copy any drum after it's emptied into a terminal.
If you fill it using any other mod, it becomes normal again.

So to be short, there is a major bug integrating with drums, and it includes massive duplication.

Running Forge 1395 and ExtraCells 1.7.10-2.2.69.

**Comment by scifibob** [comment]
Forgot to mention, I'm running Mekanism-1.7.10-8.1.2.229

**Comment by itanshi** [comment]
I'm not filling a stack of barrels, but just one barrel in the fluid terminal.

**Comment by itanshi** [comment]
I'll add a bit of info to this. I understand the suspect bedrockium barrel was placed on a nulifier and drained normally. There is no ghosting here.

**Comment by itanshi** [comment]
Update, this only works if you have a tank attached to a fluid storage bus with X buckets of fluids in it. When you add a larger empty fluid (tank) say a bedrockium drum to the fluid terminal, the magic happens. This does not work without a storage bus on a tank with X fluid in it.

**Comment by itanshi** [comment]
I have updated to 2.2.73b and this is still an issue.

**Comment by ruifung** [comment]
That's because this hasn't been fixed. I've just only recently started looking into the actual implementations of the terminal containers and so on. So it will take some time before I figure this out.

**Comment by ruifung** [comment]
Just to be certain, it happens with any fluid container item (or only drums?) with more capacity then the amount of the fluid you are storing into it that is present in the system, and it fills said container completely?

Also does it happen using portable terminals and the portable fluid storage cell?

Did I get that right?

**Comment by itanshi** [comment]
Yes

**Comment by ruifung** [comment]
Hmm, in this case it  SHOULD be in the ContainerFluidStorage class since thats where the logic is handled.. hmm.

**Comment by itanshi** [comment]
No change in mod update.
