### ISSUE TITLE
Suggestion: "Wireless Bucket"

### ISSUE THREAD

**Issue by rbuckton** [ExtraCells/ExtraCells2#229]
While the wireless fluid terminal is nice, it is somewhat cumbersome to use it when the intent is to place buckets of a liquid in the world manually (for instance, when filling air gaps in a Big Reactor with Gelid Cryotheum). 

I would envision a "Wireless Bucket" as a crafting recipe that requires a Wireless Receiver (A), a Dense Energy Cell (B), a Fluid Formation Plane (C), a Fluid Annihilation Plane (D), and a Bucket (E) in a shaped crafting recipe:

```
 --- --- ---
|   | A |   |
 --- --- ---
| C | E | D |
 --- --- ---
|   | B |   |
 --- --- ---
```

After linking the "Wireless Bucket" to your ME network, to bind the "Wireless Bucket" to a specific fluid, you would: 
1. Activate an existing Fluid Terminal on the same ME network as the "Wireless Bucket".
2. Select a fluid available in the Fluid Terminal.
3. Place the "Wireless Bucket" in the input slot of the "Fluid Terminal". It would then move to the output side of the terminal and be bound to that fluid.

Then, with the "Wireless Bucket" active in the hot bar, it would act in a fashion similar to a vanilla bucket with the following modifications:
- Right-clicking with the "Wireless Bucket" will always act like emptying the bucket, by draining 1000mB of the bound fluid from the storage network and placing it in the world.
- Shift-right-clicking with the "Wireless Bucket" on a block of the bound fluid in the world will always act like filling the bucket, by removing the fluid from the world and filling the storage network with 1000mB of the fluid.
- Right-clicking a Tank would drain _up to_ 1000mB from the network and fill the tank by that amount.
- Shift-right-clicking a Tank would drain _up to_ 1000mB from the tank and fill the network with that amount.

**Comment by XFactHD** [comment]
I like the idea, but I don't think that the fluid you can pick up should be limited to the one the Wireless Bucket is bound to.

**Comment by BraynStorm** [comment]
Great suggestion IMO. I think it will be better to be a rebindable wireless bucket: you basically Shift-RightClick to open the Fluid Terminal and choose a "placeFluid" but you can scoop whatever you want (as @XFactHD says). These are my thoughts on the idea but I would really like them to be in-game.

Cheers

**Comment by rbuckton** [comment]
@BraynStorm: I think I agree with you. Here's a new control scheme proposal:
- Shift-right-click, opens a GUI similar to the fluid terminal to select a fluid or clear the selection. 
- Right-click an air block to place the selected fluid in the world.
- Right-click any fluid block to drain the fluid from the world and place it in the ME network (if there is room).
- Right-click a tank to place the selected fluid.
- Shift-right-click a tank to drain the selected fluid from the tank and place it in the ME network.

When a fluid is selected in the GUI the item sprite for the wireless bucket would look as if it contained the selected fluid, similar to a vanilla bucket.
