### ISSUE TITLE
[Render Issue] Blast Resistant ME Drive

### ISSUE THREAD

**Issue by spannerman79** [ExtraCells/ExtraCells2#231]
Forge 1420
[ExtraCells-1.7.10-2.2.71b121](http://minecraft.curseforge.com/mc-mods/229218-extracells2/files/2239971)
appliedenergistics2-rv2-stable-5

The images speak for themselves I think
![2015-06-10_06 54 18](https://cloud.githubusercontent.com/assets/7542384/8069547/9a713698-0f3e-11e5-96ff-0345935517d8.png)
![2015-06-10_06 54 22](https://cloud.githubusercontent.com/assets/7542384/8069550/9a7eb4d0-0f3e-11e5-9046-46f826725b9e.png)
![2015-06-10_06 54 39](https://cloud.githubusercontent.com/assets/7542384/8069548/9a781e9a-0f3e-11e5-9694-0185462ef58c.png)
![2015-06-10_06 55 25](https://cloud.githubusercontent.com/assets/7542384/8069549/9a7ad5d6-0f3e-11e5-9cdf-c58b586e84a5.png)

**Comment by DrummerMC** [comment]
The blast resistent me drive isn't complete finished yet.

**Comment by spannerman79** [comment]
I apologise, I searched through your [wiki](https://github.com/ExtraCells/ExtraCells2/wiki) and forum thread and didn't see that it was incomplete.
