### ISSUE TITLE
Render Bug with Blast Resistant ME Drive

### ISSUE THREAD

**Issue by NitroxydeX** [ExtraCells/ExtraCells2#232]
When you place down the Blast Resistant ME Drive there are some graphic glitches.

![2015-06-08_00 30 42](https://cloud.githubusercontent.com/assets/9305576/8086516/1ca94c0c-0f96-11e5-94a9-8fcd68cd4064.png)
![2015-06-08_00 30 52](https://cloud.githubusercontent.com/assets/9305576/8086515/1ca790b0-0f96-11e5-84d4-2a4b390946fb.png)

**Comment by 6210classick** [comment]
what version of forge & AE2 & Extra cells are you using ?

**Comment by spannerman79** [comment]
Isn't this a dupe from #231 ?

**Comment by NitroxydeX** [comment]
Seems that we opened it nearly same time. :D 
Informations:

Forge 1448
ExtraCells-1.7.10-2.2.71b121.jar
Applied Energistics RV2 Stable 5

**Comment by OldManCraft** [comment]
If you turn Clouds on in Video settings it goes away. Just a FYI

**Comment by Nedelosk** [comment]
Fixed in 1.10.

**Comment by gordominossi** [comment]
It still happens on 2.0.8.3
