### ISSUE TITLE
Can't place an Me Fluid Auto Filler

### ISSUE THREAD

**Issue by Shayleel** [ExtraCells/ExtraCells2#237]
Hi, I can't place an Me Fluid Auto Filler when a Security Terminal is in the system.
Edit : Seems like it works when I place it then connect a cable, but placing it on a cable doesn't work.

**Comment by edgard** [comment]
Also having this problem, you can't connect it to ME network, but can connect ME network to it. :D

**Comment by Vastrix** [comment]
2 years later and we still have this [issue](https://puu.sh/x4Tns/88a03764fc.gif)?
cmon guys.. ;(

**Comment by abc123me** [comment]
Same problem here
