### ISSUE TITLE
Fluid crafting

### ISSUE THREAD

**Issue by cerbralone** [ExtraCells/ExtraCells2#241]
I assume that the fluid patterns that are marked as a work in progress will allow for say 4 cryotheum dust to a gelid cryotheum in a me system? If so, I am excited to see those come!

**Comment by j1philli** [comment]
I'm really interested in this feature. Being able to use the fluid interface for crafting with Thermal Expansion machines for example, just like we use the regular interface will be amazing!

**Comment by codewarrior0** [comment]
:+1:

Trying to automate the complex alloying in a TiCon Smeltery for Infinity Expert mode but there's no way to specify the amount of fluid input for a pattern in a Fluid Interface.
