### ISSUE TITLE
*Fluid Storage Buses Requiring Block Update

### ISSUE THREAD

**Issue by jjc54** [ExtraCells/ExtraCells2#243]
I am using a ME P2P Tunnel to get 32 channels from my controller to my fluid room. This trick works well with regular AE2 storage buses, and can successfully tap into all 32 channels. For some reason this trick is not wanting to work with EC2 fluid storage buses. 

As you can see from the screenshots below, the regular storage bus will connect to the network via ME P2P Tunnel -> dense cable -> regular cable. Even though the channels are listed in the WAILA tooltip as being used, the fluid storage buses refuse to connect. 

Regular Connects, Fluid doesn't: http://i.imgur.com/gmlOxU7.png
WAILA says everything is connected: http://i.imgur.com/8PJg3NW.png

Applied Energistics 2: appliedenergistics2-rv2-stable-9
Extra Cells 2: ExtraCells-1.7.10-2.2.73b129

**Comment by jjc54** [comment]
**Okay this issue isn't as severe as I thought. It seems that the fluid storage buses NEED a block update in order to work properly. The buses unload every time I leave the area. In order to get them working again they require a block update.

**Comment by lehjr** [comment]
I'm seeing this with everything that has a visual indicator for a connection, such a import/export and storage buses, and fluid terminals. It might even be everything, I haven't really checked.

I thought maybe a change in AE2 might have caused this but other AE2 addon mods are working fine.
