### ISSUE TITLE
No block expanding/implementing extracells:part.base has a channel.

### ISSUE THREAD

**Issue by webmilio** [ExtraCells/ExtraCells2#244]
Using ExtraCells-1.7.10-2.2.73b130, since 131 crashes on multiplayer.

I have setup a ME Network containing fluids and using fluid storage busses, connected to Bedrockium Drums (65,536,000mb). I can see neither the liquids in the cells (lava, f.e.) and in the drums (heavy water, f.e.). All my busses are marked as offline/missing channel and my cells contain liquids that aren't displayed and which cannot be extracted.

<br/>
#### Busses

![2015-06-25_12 54 06](https://cloud.githubusercontent.com/assets/836345/8360413/8dbe7854-1b3a-11e5-8234-c80b954fe968.png)
![2015-06-25_12 52 49](https://cloud.githubusercontent.com/assets/836345/8360412/8dbb6240-1b3a-11e5-85fa-e3fcab02c86c.png)
![2015-06-25_12 52 52](https://cloud.githubusercontent.com/assets/836345/8360414/8dbfd262-1b3a-11e5-8eb0-494089fb0e63.png)

<br/>
#### ME Terminal & Cells

![2015-06-25_12 50 27](https://cloud.githubusercontent.com/assets/836345/8360437/b306e204-1b3a-11e5-93cc-cc2eac461cb6.png)
![2015-06-25_12 50 39](https://cloud.githubusercontent.com/assets/836345/8360438/b30a9ff2-1b3a-11e5-9845-69615afb4c15.png)

**Comment by webmilio** [comment]
I can see lava in the terminal when I'm in a different dimension, but thats it.

**Comment by ruifung** [comment]
Is this still happening?
