### ISSUE TITLE
Fluid storage buses don't like tank contents changing externally

### ISSUE THREAD

**Issue by TruePikachu** [ExtraCells/ExtraCells2#245]
First of all, EC2 version is 2.2.72b, the best I can tell.

When I attach a fluid storage bus to any tank, and change the tank's contents not through the bus, the bus continues to report the old quantity of fluid to the system. For instance, at this very moment, I have a fluid storage bus attached to a drum full of water, yet my storage monitor doesn't report the water, nor does my terminal.
![2015-06-25_00001](https://cloud.githubusercontent.com/assets/9327340/8368083/b790932c-1b5a-11e5-9b76-17689ff4027a.jpg)

**Comment by ruifung** [comment]
Duplicate #39
