### ISSUE TITLE
Liquid duplication

### ISSUE THREAD

**Issue by Livan-pro** [ExtraCells/ExtraCells2#249]
Hi, there is a bug in version 2.2.73b129(&earlier). It allow you to duplicate any liquid.
How to reproduce:
1. Place Certus Tank with small amount of any liquid in world
2. Place random item in every slot of your inventory
3. Take 2+ empty buckets
4. Click on Certus Tank with empty buckets
5. Profit! Buckets is still empty(because there isn't slot where filled bucket can be placed), but amount of liquid in tank is increased.
And there is a video(not by me) describes how to do that:
https://www.youtube.com/watch?v=McUCzzMkQvM

**Comment by Krysinski** [comment]
I can confirm that. Any news?

**Comment by bookerthegeek** [comment]
Still an Issue.
