### ISSUE TITLE
ExtraCells-1.7.10-2.2.73b129.jar not works with NEI

### ISSUE THREAD

**Issue by SWATOPLUS** [ExtraCells/ExtraCells2#250]
1.7.10-Forge10.13.2.1352-1.7.10.jar //can't use older version, because GregTech5 don't support them.
Minecraft was crash when i start a SP game, only 4 mods:

ExtraCells-1.7.10-2.2.73b129.jar
appliedenergistics2-rv2-stable-9.jar
NotEnoughItems-1.7.10-1.0.3.74-universal.jar  // this version is recommender be chickenbones
CodeChickenCore-1.7.10-1.0.4.29-universal.jar // also recommended

**Comment by SWATOPLUS** [comment]
No this bug, when i use ExtraCells-1.7.10-2.2.68bNIGHTLY.jar

**Comment by ruifung** [comment]
Not enough information.

**Comment by DrummerMC** [comment]
FML and ec version incompatible.  Use the last stable forge version.
