### ISSUE TITLE
[request] support mekanism gas

### ISSUE THREAD

**Issue by Tsunayoshi** [ExtraCells/ExtraCells2#251]
Hi,

I don't know if this matches with the fluid-base of this mod. But maybe you could support the gases from mekanism, too? The excuse could be that is only a to hot fluid :p 
Maybe this brings more with it, a few new blocks (cooler and heater) to bring it to the fluid physical state.

**Comment by DrummerMC** [comment]
I'm already working on it. Now only the gas import bus and the gas storage cells works.

**Comment by Tsunayoshi** [comment]
That sounds good. I am looking forward to it :wink:

**Comment by ruifung** [comment]
@Tsunayoshi Don't need a cooler and heater, since its Mekanism gas, that implies you already have mekanism installed, which means you can just use the rotary condenserator instead.

Although @DrummerMC does AE2's API allow for extra P2P support anyway?
