### ISSUE TITLE
Rock melter fluid duplication

### ISSUE THREAD

**Issue by Baughn** [ExtraCells/ExtraCells2#252]
![2015-07-05_17 47 33](https://cloud.githubusercontent.com/assets/45811/8512556/0c14e4f6-2340-11e5-9b20-2ecdcc626871.png)

This setup consists of:
- A RotaryCraft rock melter, feeding lava into an import bus.  (Paging @ReikaKalseki)
- A small ME system with a single 1k fluid storage disk.
- A Thermal Expansion igneous extruder, with two export buses attached.
- And an EIO reservoir attached to a fluid storage bus, because I needed the water.

Lava (possibly; hard to be sure) isn't duplicated while filling the storage disk, which took two-and-a-bit stacks of netherrack, but once the disk is full, a single bucket of lava being extracted from the disk gets refilled from the rock melter _without_ said rock melter losing any of its contents. I can see the disk blinking green as this happens, so I think the problem is on the import bus.

This happens while using the latest ExtraCells version, as well as 2.2.58b88 (the version in TPPI2 0.1.1), and RotaryCraft V6f.

**Comment by ReikaKalseki** [comment]
I have heard things before about fluid buses copying liquid. Last I heard, it was related to speed cards.

**Comment by Baughn** [comment]
There were no speed cards involved this time. Or cards of any kind.

**Comment by Baughn** [comment]
A bit of further experimentation: This does not happen if the fluid cell is not full. (As expected.)

**Comment by Baughn** [comment]
Or if I use a fluid storage bus instead.
