### ISSUE TITLE
Compatibility issues with latest AppleCore

### ISSUE THREAD

**Issue by p-schneider** [ExtraCells/ExtraCells2#255]
Lastest versions of [AppleCore](https://github.com/squeek502/AppleCore/) (available on [drone.io](https://drone.io/github.com/squeek502/AppleCore/files)) trigger a crash related to ExtraCells2 at startup on a dedicated server.
AppleCore stumbles across the class `ModelCertusTank` while trying to look for plants (`net.minecraft.block.IGrowable`). The analyzing methods can't find the parent class `net.minecraft.client.model.ModelBase` and therefore it crashes the launching server.
[(see crash-log)](https://gist.github.com/p-schneider/44dd87b8e3eeea0cf199)

[extracells.Extracells.init()](https://github.com/ExtraCells/ExtraCells2/blob/rv2/src/main/scala/extracells/Extracells.scala#L60) (`new RenderHandler(...)` is called regardless if it's a dedicated server or a client)
[extracells.render.RenderHandler](https://github.com/ExtraCells/ExtraCells2/blob/rv2/src/main/scala/extracells/render/RenderHandler.java#L19) (the constructor of `ModelCertusTank` gets invoked)
[squeek.applecore.asm.module.ModulePlantFertilization.transform()](https://github.com/squeek502/AppleCore/blob/master/java/squeek/applecore/asm/module/ModulePlantFertilization.java#L94) (tries to check if `ModelCertusTank` extends `net.minecraft.block.Block`)
[squeek.asmhelper.applecore.ASMHelper.doesClassExtend()](https://github.com/squeek502/ASMHelper/blob/master/raw/squeek/asmhelper/ASMHelper.java#L178) (crashes because it can't find the class definition for `net.minecraft.client.model.ModelBase`)

Not using the latest version of AppleCore prevents the crash but I think the RenderHelper class should not be loaded on a dedicated server in the first place.

Mentioning @squeek502 here might notify him about this issue, even though I assume the crash should be prevented on ExtraCells side.

**Comment by squeek502** [comment]
The latest builds of AppleCore are _not_ ready for use. Use the [last officially released version, v1.1.0](https://github.com/squeek502/AppleCore/releases/tag/v1.1.0), instead. There is no benefit to using a newer version right now.

That said, I don't see the harm in making RenderHandler client-only. It is something that AppleCore will need to deal with, though, so I'll try to find a solution on my end as well.
