### ISSUE TITLE
[Feature Request] Bigger Thaumic Energistics Storage Cells

### ISSUE THREAD

**Issue by gabor7d2** [ExtraCells/ExtraCells2#256]
As the title says, I think it would be a good idea to have Essentia Storage Cells with bigger capacities (and even with more essentia types) registered by this mod if the Thaumic Energistics mod is in the game. Up to like 4096k or something. I don't know how difficult it would be, it's just a suggestion.

**Comment by angelnc1989** [comment]
Why would you ever need so much stored essentia?
The biggest one from Thaumic Energistics can hold 131072 of one aspect.
More than you could ever use.

**Comment by gabor7d2** [comment]
Oh sorry, I didn't calculated it, but that's very cool actually. I didn't know that. But thanks for the info and answer. :smile:
