### ISSUE TITLE
Linux build.sh typo

### ISSUE THREAD

**Issue by davidpanic** [ExtraCells/ExtraCells2#258]
``` linux
./gradlew clean setupCIWorkSpace build
```

instead of

``` linux
gradlew clean setupCIWorkSpace build
```

you're welcome.

**Comment by Beyley** [comment]
This seems to have regressed, and the build script once again is `gradlew` instead of `./gradlew` 
https://github.com/ExtraCells/ExtraCells2/blob/rv6-1.12/build.sh
