### ISSUE TITLE
Server Crash With Extra Cells 2

### ISSUE THREAD

**Issue by king05** [ExtraCells/ExtraCells2#262]
Hi,
I got this crash, when I right click on an ME Fluid Terminal on an server

http://pastebin.com/C3tHaEjV

Hope you can help me

**Comment by ruifung** [comment]
Thats a mighty strange crash you got there, I mean, the relevant code referenced by the stack trace doesn't even reference that class.

**Comment by king05** [comment]
This Crash is with the Newest Veriosn 2.2.73b132

With the Version 2.2.73b131 I can't even acces the Terminal.... but it didn'T crash :)

Edit: With Version 2.2.73b130 it seems to be working
