### ISSUE TITLE
Mekanism Gasses

### ISSUE THREAD

**Issue by thechad24** [ExtraCells/ExtraCells2#264]
In the config file:
 # Enable MekanismGas Integration.
    B:enableMekanismGas=true

I was not able to get extracells.part.gas.importname import any gasses. I didn't see any special storage cells, so i was using fluid cells. Is this part of the mod not fully implemented yet?

**Comment by thechad24** [comment]
I see there is another request

**Comment by DrummerMC** [comment]
fixed with https://github.com/ExtraCells/ExtraCells2/commit/7accd33461b623d34d081adbbf5dcb33356ae379
