### ISSUE TITLE
Nice dupe glitchy!

### ISSUE THREAD

**Issue by Buzzefall** [ExtraCells/ExtraCells2#271]
Those nice ME Drive Fixtures can be clicked once with a wrench and then rapidly same but with shift pressed, which gives you a GUI with cells which can be extracted, whilst the fixture is already in your inventory, i guess there is no check if it was dismantled. 

Also, they seem to me work somehow differently compared to regular ME Drives, do they? As I had problems with Thaumic Energistics integration: essentia wasn't going in a cell after 1 type of 12 was stored. All the cells were filled by 1 of 12 types and when they are maxed (not in bytes, but the whole system type-maxed) that way, they input is blocked entirely. But that might be TE problem though, sorry for bothering if that is really so.

On my TPPI server by the way wireless fluid terminal causes ghost items to be produced, which after try to stack them with shift (tried resonant UU-matter tanks) dissapeared with all the contents, and completely from ME system too. Do they work or in a WIP state?

**Comment by ruifung** [comment]
Fun fact, this mod has so many WIP parts in the code, heck it canInteractWith in the container classes seems to be hardcoded to return true..

**Comment by ruifung** [comment]
So.. I've been trying to figure out how to check if the part is still present, but given that ALL of EC's tileEnts don't seem to implement IInventory, I can't check isUseable heck, I can't seem to figure out how to check if the tileEntity is still present because I can't figure out how to get the tileEntity when its a multipart block, getTileEntity seems to only work with XYZ coords which defines a block space... so I need some ideas here.

@DrummerMC

**Comment by Buzzefall** [comment]
Well, I have no modding experience for now, though looking forward to learn more and make own mod. Sad for me there is no even comments on code x)

upd: Okay now i know what tileEntities are and aware of a very bit of facilities from original minecraft :D 

So, what If they had implemented inventory, what the solution would be?

**Comment by ruifung** [comment]
nevermind, I was just looking for a way to check if the part is still valid, took me a while to figure it out.

**Comment by Buzzefall** [comment]
Have you fixed it? And what's the solution?

**Comment by ruifung** [comment]
I _think_ I fixed it in my own branch (but haven't tested), but right now I'm trying to clean up the code in my own branch.

**Comment by ruifung** [comment]
@Buzzefall please try with build 135, it should fix this.
