### ISSUE TITLE
False math with storage cells

### ISSUE THREAD

**Issue by chaos234** [ExtraCells/ExtraCells2#277]
Hey,

I want to report that the storage cells have false values because for each different item it will waist a hugh amount of space but for each 8 items it will only use 1 byte.

Correct use should be 1 byte for each 8 items of the same type and also each different type should only be use one byte because 1 byte are 8 bit and if 8 items of the same type uses 1 byte one item for each different type can't use over 131k as initial storage.

Pls correct this error.

**Comment by ruifung** [comment]
Can you please clarify what you mean? 

Each type uses totalBytes / 128 as per the maths provided by AE.
http://ae-mod.info/ME-Storage-Math/

**Comment by chaos234** [comment]
Sure, it's exactly that what I've written.
The space needed for an item to store it is 1 bit because for each 8 items of the same type we need 1 byte. But why should I waste for each different item (e. g. Stone and Dirt) more than 1 byte?
If I store one dirt on an 16M disk it will eat over 130000 byte and this is false because one item is only 1 bit so the correct value has to be 1 byte for each different first item ( one stone, dirt, iron ingot, ...) otherwise 50% of the storage is wasted after storing 63 different types and this isn't accebtable so it has to be changed.

Von Samsung-Tablet gesendet

-------- Ursprüngliche Nachricht --------
Von: ruifung notifications@github.com 
Datum: 18.08.2015  11:51  (GMT+01:00) 
An: ExtraCells/ExtraCells2 ExtraCells2@noreply.github.com 
Cc: Chaos234 info@deltanet-production.de 
Betreff: Re: [ExtraCells2] False math with storage cells (#277) 

Can you please clarify what you mean?

**Comment by ruifung** [comment]
First, storage of items & storage of types, is completely different. The size per type is following the pattern set by AE2 itself. The size per item on the other hand, is handled by AE2 itself.

So the amount of storage used for TYPES, is following the pattern set by AE2.
Example: For a 64k Cell, it uses 65536/128=512 bytes per type, which makes 32256 bytes at 63 types.

So that makes 32256/65535 bytes of a single 64k Cell is used for storing types if you have 63 types.
So really, you should go complain to AE2 instead.

Also, all this mod can do is specify the size per type, which it  follows AE2's ratio on type size to cell size.

**Comment by chaos234** [comment]
Then I would override this methode an put in my methode that each TYPE only consumes 1 byte and after each 8 items one additional byte will be used. More space and less waste like a compressed hdd in our pc.
So thies means that 63 different TYPES ade using only 63 byte and not more nor not less. Now all adittional items from the same TYPE can use the free space because there are only 63 bytes used currently and many bytes are free.
This will be the best and perfect value to store items correctly without wasting storage, which means that you can store up to x8 of one TYPE on the cell what this means doesn't need words ... 16Mx8 or 4096Kx8 and so on.

Von Samsung-Tablet gesendet

-------- Ursprüngliche Nachricht --------
Von: ruifung notifications@github.com 
Datum: 18.08.2015  17:18  (GMT+01:00) 
An: ExtraCells/ExtraCells2 ExtraCells2@noreply.github.com 
Cc: Chaos234 info@deltanet-production.de 
Betreff: Re: [ExtraCells2] False math with storage cells (#277) 

First, storage of items & storage of types, is completely different. The size per type is following the pattern set by AE2 itself. The size per item on the other hand, is handled by AE2 itself.

So the amount of storage used for TYPES, is following the pattern set by AE2.

Example: For a 64k Cell, it uses 65536/128=512 bytes per type, which makes 32256 bytes at 63 types.

So that makes 32256/65535 bytes of a single 64k Cell is used for storing types if you have 63 types.

So really, you should go complain to AE2 instead.

**Comment by ruifung** [comment]
Then go ahead and fork the mod and override it yourself, its a very trivial edit in only one method.
While I'm not the official maintainer, I still think we should keep with AE2's conventions, this mod after all has to complement AE2, not supersede it. 

AE2 has the design that you can store more items with less types and less items with more types. 
A mod that adds to AE2 shouldn't break that design IMHO.

**Comment by chaos234** [comment]
I accept your meaning but pls also accept my one because I think with the real life and there it's not like it actually is.
On a real hdd or an other storage it doesn't matter how many types are on the storage ... it depends on how big are the files, so another possibility can be to set for each item founded in the level.dat's database a value in bit ore byte. There so many better solutions as the actually ones I think ...

Von Samsung-Tablet gesendet

-------- Ursprüngliche Nachricht --------
Von: ruifung notifications@github.com 
Datum: 18.08.2015  17:40  (GMT+01:00) 
An: ExtraCells/ExtraCells2 ExtraCells2@noreply.github.com 
Cc: Chaos234 info@deltanet-production.de 
Betreff: Re: [ExtraCells2] False math with storage cells (#277) 

Then go ahead and fork the mod and override it yourself, its a very trivial edit in only one method.

While I'm not the official maintainer, I still think we should keep with AE2's conventions, this mod after all has to complement AE2, not supersede it. 

AE2 has the design that you can store more items with less types and less items with more types. 

A mod that adds to AE2 shouldn't break that design IMHO.

**Comment by ruifung** [comment]
Yes, so instead of trying to convince me try to convince the AE2 dev team yes?
Here's their repository: https://github.com/AppliedEnergistics/Applied-Energistics-2

**Comment by XFactHD** [comment]
@Chaos234 The thing with the item list in the world files might work but it also doesn't make much sense because every item in Minecraft has the same size, no matter if it is a block in item form or a simple item.

**Comment by ruifung** [comment]
no, setting the type size per item is not possible in the ae2 api afaik.

**Comment by XFactHD** [comment]
And it would not make sense to do it random, you would need compatibility code for EVERY mod that adds even just a single block or item for this to make sense.

**Comment by ruifung** [comment]
random typesize per item? Not even remotely possible, type size is same for every item per cell. lol
