### ISSUE TITLE
Make Fluid Formation plane behave like AE2 Formation Planes

### ISSUE THREAD

**Issue by jkuball** [ExtraCells/ExtraCells2#279]
Yesterday I drove crazy why [this](http://imgur.com/XOhTo9P) didn't work. The _same_ contraption works with the original Formation Planes from AE2, because they are passive storage devices.

After some testing I found out that the Fluid Formation Planes are pulling actively stuff out of the system. This is not mentioned anywhere.

I think it should be at least mentioned in the item tooltip - or the behaviour has to be changed.

**Comment by ruifung** [comment]
Related: #281
