### ISSUE TITLE
Make Fluid Storage cell types use up storage too

### ISSUE THREAD

**Issue by ruifung** [ExtraCells/ExtraCells2#280]
Related: #281
Like AE, where each type uses up cellBytes/128 bytes
Because right now it doesn't use any bytes for storing types at all.
(This will go in my rewrite branch for now)

Opinions please.

@DrummerMC

**Comment by DrummerMC** [comment]
I think this is already implemented, but with config Option.

**Comment by ruifung** [comment]
No its not. I just went through the FluidItemStorageHandler, its getFreeBytes doesn't take into account types.
