### ISSUE TITLE
liquid formation plane and openblocks liquid xp crash issue

### ISSUE THREAD

**Issue by shandromand** [ExtraCells/ExtraCells2#282]
Liquid XP does not behave like other liquids (i.e. you can't pour a bucket out into the world).  The formation plane tries to do it anyway, and both server and sp client hard crash.  I don't have the logs from the server, but the client log is here:  

http://paste.atlauncher.com/view/2e7d7058  

We had to wipe both the region and NBT data to resolve the server issue.  This is part of the Modsauce 2 pack.

**Comment by ruifung** [comment]
Grab the latest build off the jenkins.

**Comment by shandromand** [comment]
Awesome sauce, thank you!  :)
