### ISSUE TITLE
Can't start game

### ISSUE THREAD

**Issue by EmberEdison** [ExtraCells/ExtraCells2#289]
When I push "Singleplayer"-"Create New World" it say "A fatal error has pccired, this connection is terminated".

log output:
http://pan.baidu.com/s/1qWwxexu

**Comment by ruifung** [comment]
baidu... really. It takes forever and a day to load for me, can you mirror it to pastebin or something?

**Comment by ruifung** [comment]
Please don't post links to baidu here, (fortunately I can read chinese, but it takes FOREVER to load.) - But not everyone can.

**Comment by ruifung** [comment]
Please update Minecraft Forge and ExtraCells to latest versions.

**Comment by EmberEdison** [comment]
At ExtraCells2.2.74b137 & Forge10.13.2.1291, it say "A fatal error has pccired, this connection is terminated"too.
At Forge10.13.2.1492, it crash.

**Comment by EmberEdison** [comment]
log output:
Forge10.13.2.1492
https://mega.nz/#!XQ5kjS7L!zZs2N3IernWw6k-pa4YWeM0DXjjoRUjDPH4VRtNSPJA
Forge10.13.2.1291
https://mega.nz/#!WcoUQD4Y!GZQCeXgy5XtKzGRzd2PK5dQPMrynaKVZW91x2lslVPc

**Comment by ruifung** [comment]
Forge 1291 is not new enough, the NoSuchMethodException is a clear indicator, you should use latest 1492.

Your crash on 1492 is not related to extracells in any way.

**Comment by EmberEdison** [comment]
thanks a lot.what version of extracells can use in Forge 1291?

**Comment by ruifung** [comment]
Don't know. I only began work on this recently. But I don't think there are any versions left around that can run on 1291, short of the really old ones on the curse page.

You're better off updating all your other mods or finding out which mod is causing the crash in 1492.
