### ISSUE TITLE
Gas export bus dosn't function with Mekanism yet?

### ISSUE THREAD

**Issue by Aaeru1022** [ExtraCells/ExtraCells2#290]
Sorry in advance, I am new to get hub and I was just wondering if you had gotten the gas import bus to work and not the gas export bus to work yet or if I'm just using a different version of Mekanism than what you are testing with?

Again sorry if this is the wrong place to ask this. I just want to make sure if I'm doing something wrong.

I'm using:
forge-1.7.10-10.13.4.1448
ExtraCells-1.7.10-2.2.74bNIGHTLY
Mekanism-1.7.10-8.1.7.252
along with a bunch of other mods in my mod pack

**Comment by Simon-Bitdiddle** [comment]
There is a workaround; use Ender IO gas pipes as a step between the ExtraCells2 Exporter and the Mekanism machine.

**Comment by DrummerMC** [comment]
fixed with https://github.com/ExtraCells/ExtraCells2/commit/7accd33461b623d34d081adbbf5dcb33356ae379
