### ISSUE TITLE
Redstone detection on fluid export bus too sensitive?

### ISSUE THREAD

**Issue by edgard** [ExtraCells/ExtraCells2#293]
Apparently the Fluid Export Bus (not sure about interface and others) is too sensitive to redstone signals.

This works with regular (item) exports buses:
http://imgur.com/GLeYocD

But it doesnt work with extracells. I can't have them stacked like that because the buses are picking up the redstone signals from the other emmiters, I have to put a block separating them like that:
http://imgur.com/4OaRzPR

**Comment by ruifung** [comment]
O.O I'll take a look at this in a bit.
