### ISSUE TITLE
ME Portable Fluid Storage drains excessive amounts of power from active capacitors.

### ISSUE THREAD

**Issue by AmethystAir** [ExtraCells/ExtraCells2#296]
I'm using Applied Energistics rv2-stable-10 and Extra Cells 2.2.73 in the FTB Infinity pack v1.10.1. I've tested this with both the Wyvern Capacitor from Draconic Evolution and the Redstone Flux Capacitor from Thermal Expansion, and both seem to have this problem.
Edit: I updated Extra Cells to 2.2.74 and the problem still exists.

**Comment by ruifung** [comment]
How much is it draining? Is it idle drain or when doing something?

**Comment by AmethystAir** [comment]
I don't know exact numbers, but it's able to drain a Wyvern Capacitor (80,000,000 RF) in about thirty seconds. I made a quick video showing the bug with some additional information: https://www.youtube.com/watch?v=ojDZLfdvLwg

**Comment by AmethystAir** [comment]
I think the problem might be [here](https://github.com/ExtraCells/ExtraCells2/blob/rv2/src/main/scala/extracells/item/ItemStoragePortableCell.java#L248-L249). If I'm interpreting the code correctly, when the portable storage is full [injectAEPower](https://github.com/ExtraCells/ExtraCells2/blob/rv2/src/main/scala/extracells/item/ItemStoragePortableCell.java#L213-L219) will return zero, meaning notStored will be zero as well. That causes the receiveEnergy function to return maxReceive, even though no power is being used by the storage.

**Comment by AmethystAir** [comment]
I ran some more tests, and it seems that the storage cell doesn't drain power when it's charging and does drain power when it isn't.

**Comment by ruifung** [comment]
Send a pull request! I haven't had time to work on EC recently (assignment rush time! =P)
