### ISSUE TITLE
Fluid terminal not lit and not showing channel active

### ISSUE THREAD

**Issue by leagris** [ExtraCells/ExtraCells2#298]
An AE2 ME Terminal is emitting light when active.
But a fluid terminal does not.

All AE2 micro-block devices show a when channel active or no channel available.
Fluid devices don't.

**Comment by ruifung** [comment]
#243 Related?

**Comment by leagris** [comment]
## Versions used:
- forge-1.7.10-10.13.4.1492-1.7.10-universal.jar
- appliedenergistics2-rv2-stable-10.jar
- ExtraCells-1.7.10-2.2.74b137.jar

## Detail

> #243 Related?

Not sure, I can still use and access the fluid terminal while it is not lit and does not show an active channel mark/colour on its connector side.
It is placed on an ME Glass Cable.

## Illustration
- Below you can see the ME Terminal with a blue rectangle on its back connector, because it has an active channel.
- The ME Fluid Terminal has its connector rectangle black, as if did not get a channel while it is still working.
- You can also see the Fluid terminal unlit.

![Screen-shot 2015-09-24_03 50 09](https://cloud.githubusercontent.com/assets/1111474/10063600/1f7e1372-6270-11e5-8411-8696aefb63cf.png)

**Comment by XFactHD** [comment]
I am seeing this behaviour too, but in a completely different build: When I have to shift around some fluids, I build a sub network out of a drive, a terminal and a glass cable with a quartz fiber. On this network without a controller, the fluid terminal is lit and has a channel but as soon as I remove the quartz fiber, to connect everything to my main network, the terminal isn't lit anymore and indicates that it doesn't have a channel.

OT: Just as a tip: Change the connection type of the parts to glass cable, it just looks much better.

**Comment by ruifung** [comment]
So... a visual bug only?

**Comment by XFactHD** [comment]
Yeah, the parts seem to be missing a update call, because a block update also fixes it most of the times.
