### ISSUE TITLE
Wireless Fluid Terminal dupe

### ISSUE THREAD

**Issue by fishmealx** [ExtraCells/ExtraCells2#302]
Placing a bedrockium drum (Extra Utilities) in a Wireless Fluid Terminal (but not wired) to fill it, then placing that drum on the ground does not use up the drum in my inventory. I can keep placing the same drum repeatedly, as though I am in creative mode.
Edit: Filling 2 drums in the wireless terminal will also cause them to try to stack in the rightmost slot, sometimes deleting the second drum.
I'm playing on Modsauce 2 if that helps.

**Comment by ruifung** [comment]
What? @rwtema Any ideas about this? This sounds more like something in ExU though?

**Comment by itanshi** [comment]
I tested this. I filled a stack of bedrockium drums with water. I used 1 bucket of water via fluid storage bus and a tank. Not been able to dupe barrels yet. I seem to be deleting barrels.

Oh, these are empty drums labeled as water. weird.
