### ISSUE TITLE
Extra cells gasses support

### ISSUE THREAD

**Issue by Renegade2** [ExtraCells/ExtraCells2#305]
I was using mekanism/galacticraft  the other day and though,"Hey,why are there really no good ways to store mekanism gasses?" A good idea for gasses would be to make storage cells,and inport/export busses that would be able to store and transfer gases from mekanism or other gas related mods.

**Comment by ruifung** [comment]
The problem with that, is there is no standardized gas API. Also - there is a good way to store mekanism gas - heard of the rotary condenserator? - that aside, I probably will finish up the mek gas support eventually.

**Comment by Aaeru1022** [comment]
"standardized API" do you mean that EC developers are waiting for the forge developers to create a standard way of handling gases? 
Also thank you so much for stating that you will not give up on mek gas support. Many of my building ideas depend on that functionality.

**Comment by ruifung** [comment]
By standardized api.. well does any mod OTHER then mekanism use gas anyway?

**Comment by ruifung** [comment]
Although... If I remember correctly, the reason @aidancbrady made mekanism's gas system is mainly because he wanted it to be a seperate system from fluids. - You can still store it using rotary condenserators to turn them to fluids though.

At this moment, I'm still evaluating if this will actually conflict with the whole reason that mekanism has a gas system in the first place.

**Comment by Aaeru1022** [comment]
not sure if this is relevant or not but the reason I am looking to EC for gas logistic support is because the situation I will be building in renders all of mek's logistics items useless.

**Comment by ruifung** [comment]
Hmm? Can you give an example?

**Comment by Aaeru1022** [comment]
Ok well what I want to build is a fully functional spaceship. In every way. It's doable in the mod pack I maintain. but the movability part is handled by Archimedes ships plus which for some reason deletes all forge micro blocks when the ship is compiled. I've taken the problem up with the mod maker and he basically said he doesn't care. Now also for reasons unknown all of the tubes cables and pipes from mek are considered forge micro blocks (my conclusion given by wala saying "forge multi part block"). Archimedes ships plus has no problem with AE2 or EC so when i saw "extracells.gas.inport.name" in the nei menu i got really exited

**Comment by ruifung** [comment]
Thats beacuse all mekanism transmitters ARE forge microblocks. While I still am considering about gas storage, what I do plan to add is a Gas P2P - eventually. (A while off though, given that I'm currently rewriting EC2.)

**Comment by Aaeru1022** [comment]
alright if it will be a while, I'll keep a closer eye on ender io development. Hopefully their gas conduits stop crashing whenever I look at them.

**Comment by DrummerMC** [comment]
fixed with https://github.com/ExtraCells/ExtraCells2/commit/7accd33461b623d34d081adbbf5dcb33356ae379

**Comment by woodzykiler** [comment]
SO Question related to this, is there a was to format the gas cells?
the cell bench doesnt seem to be working for this and the Mek tanks are only goin in as an item.
