### ISSUE TITLE
EC2 cells + ME IO port

### ISSUE THREAD

**Issue by XFactHD** [ExtraCells/ExtraCells2#306]
It is impossible to empty out fluid storage cells by putting them into a ME IO port. I would suggest creating your own Fluid IO port, like @Nividica did it.

**Comment by ruifung** [comment]
I would prefer to figure out why it isn't working if possible. and make it work. - if possible.

**Comment by adamcirillo** [comment]
I've just tried this on ExtraCells-1.7.10-2.3.0b142.jar for me it works but its a lot slower then using the item cells of the same size like 1 64k item storage would take like a minute or 2 with maxed out accelerations cards where a 64k fluid would take 10 minutes plus to do.
