### ISSUE TITLE
Fluid Vibration Chamber block does not render active/burning state

### ISSUE THREAD

**Issue by leagris** [ExtraCells/ExtraCells2#307]
When burning fluids, the vibration chamber does not use/reference the active icon:
https://github.com/ExtraCells/ExtraCells2/blob/rv2/src/main/scala/extracells/block/BlockVibrationChamberFluid.java#L79

Because it does so only when there is an explicit IBlockAccess:
https://github.com/ExtraCells/ExtraCells2/blob/rv2/src/main/scala/extracells/block/BlockVibrationChamberFluid.java#L79

**Comment by leagris** [comment]
It look like the Fluid Vibration Chamber is not finished/not working properly at all.
Feeding Lava, It start generating only when its internal tank is full.
It generate for a while, then stop and don't accept more fluid.

On placing the VC, the front face is in the opposite direction as expected.

The fluid gauge texture is squeezed.distorted in the upper 10% of the gauge.

Whil it accept Forestry Ethanol, Vanilla Lava. It does not accept Railcraft fuel, creosote or other different fluid fuels

**Comment by ShadowDrakken** [comment]
This still seems to be an issue after a full year... what's the current state of the mod? :\

**Comment by Nedelosk** [comment]
Fixed in 1.10.
