### ISSUE TITLE
Add crafting recipe to remove cells

### ISSUE THREAD

**Issue by deathglow** [ExtraCells/ExtraCells2#311]
Like in ae2 when a housing and a storage component are combined the form into a storage cell.  In ae2 you can then put that storage cell into a crafting window and receive the housing and the component again.  It would be very helpful if you implemented a similar recipe.

**Comment by ruifung** [comment]
Enhancement noted, but in the meantime - you can just shift r click to seperate the parts.

**Comment by deathglow** [comment]
I was not aware of that.  Thank you.

**Comment by ruifung** [comment]
b-but... Thats been in AE since AE1 i think.
