### ISSUE TITLE
Helium plasma on Fluid Storage Monitor / Fluid Interface

### ISSUE THREAD

**Issue by SapientMC** [ExtraCells/ExtraCells2#313]
If add Helium Plasma to Fluid Storage Monitor and to Fluid Interface it works fine only till next game restart (single). After that there are some different liquid there and i need to reconfigure them to plasma again.
May be it would be same bug for any plasma i didn't test it.

ExtraCells-1.7.10-2.2.73b129
appliedenergistics2-rv2-stable-10
gregtech_1.7.10-5.08.30

**Comment by ruifung** [comment]
Hmm, i wonder if the fluid ID is changing between restarts.

**Comment by SapientMC** [comment]
It is possible, but fluid storage drive (with helium plasma) and universal fluid cell does not change containing fluid.

**Comment by ruifung** [comment]
Hmm. Then something else is wierd.

**Comment by Blood-Asp** [comment]
Due to gregtechs multithreaded loading, the order of fluid IDs is different every load. The fluid ids are saved inside of the world and are synced on world load. So maybe EC somehow caches the IDs before the world is loaded?

**Comment by ruifung** [comment]
Shouldn't be though? The fluid ID's are resolved through the fluiddict if i remember correctly.

**Comment by Blood-Asp** [comment]
It should not, but still it seems to happen anyways.

**Comment by SapientMC** [comment]
Additional info
Molten Tungsten/Osmium has same issue.
