### ISSUE TITLE
AE2 won't detect any fluids in ME Drive connected through ME Storage Bus > ME Interface

### ISSUE THREAD

**Issue by FaberoneX** [ExtraCells/ExtraCells2#315]
http://imgur.com/a/17c4T

**Comment by XFactHD** [comment]
Try it with a Fluid Storage Bus and a Fluid Interface (just an idea, I don't know if it really works).

**Comment by FaberoneX** [comment]
Just tried it, it works. 2 ME Drives with one fluid and one item cell each, one is connected with fluid storage bus the other one is connected with me storage bus. I can only see half of all the stuff. I think it's working as intended.

**Comment by jghake** [comment]
I have a very large ME Drive storage system all stored on a subnetwork. When I place the Fluid Cells in that network they won't be recognized and fluid can't be put into or pulled from them. When I add a drive to my main network, not on a subnetwork, then place the cells in that they work.
