### ISSUE TITLE
Exporting of IC2 UU-Matter outputs too much fluid

### ISSUE THREAD

**Issue by A-Vaillant** [ExtraCells/ExtraCells2#316]
Using the version of ExtraCells2 including in FTB Infinity.

When any amount of UU Matter is in the fluid system, exporting to a container with the Fluid Terminal fills up the entire container regardless of the amount of UU Matter. This goes for Universal Cells and Extra Utilities drums. Similarly, exporting the fluid to a Replicator exported 2000mB at a time.

**Comment by itanshi** [comment]
Using a fluid storage bus? The Fluid storage bus is broken imho. Its being worked on.

**Comment by A-Vaillant** [comment]
Yeah, actually - access to my fluid storage cells was mediated via a fluid storage bus and a fluid interface (i.e. a subnetwork for the fluid-holding ME drives). 

The setup went [Fluid Drives] - [Fluid Interface|Fluid Storage] - [ME Controller] - [P2P Tunnel Pair] - Fluid Import Bus on a Mass Fab. I'll see if I can reproduce the bug.

**Comment by ruifung** [comment]
So.. did you manage to reproduce the bug reliably?

**Comment by A-Vaillant** [comment]
Sorry, I've been busy as of late. I'll try to reproduce it as soon as I can.
