### ISSUE TITLE
crash client (already tesselating error) when certus tank is filled with untextured gases

### ISSUE THREAD

**Issue by Krysinski** [ExtraCells/ExtraCells2#317]
If you fill certus tank with untextured gases (https://github.com/micdoodle8/Galacticraft/issues/1664) you get "already tesselating" error and crash client.
You cant connect to server more, you will getting crash. World will be broken for you then.
linked with this issue https://github.com/micdoodle8/Galacticraft/issues/1664
mods:
Gregtech
Galacticraft

**Comment by Aaeru1022** [comment]
I know this is no solution but a temp fix would be to use mcedit to remove the certus tank in question.
This way you don't lose your progress in the world.
