### ISSUE TITLE
shift clicking upgrades into added ME network components sometimes destroys items

### ISSUE THREAD

**Issue by kotoroshinoto** [ExtraCells/ExtraCells2#318]
As it says in title, instead of distributing the items into the slots, it attempts to place all of them in one spot, which flattens the stack to 1 item and destroys the rest. as in the fluid import bus.

**Comment by ZeroInputCtrl** [comment]
I'm still seeing this in ExtraCells-1.7.10-2.3.5b171 when shift-clicking a stack of Acceleration Cards. One is in the first slot of the fluid import bus and the rest are gone.
