### ISSUE TITLE
Fluid Assembler is broken

### ISSUE THREAD

**Issue by SneakyDevil** [ExtraCells/ExtraCells2#320]
http://puu.sh/l5e6e/8206a9e074.jpg

Is there some new fangled way to connect them to the network that I wasn't informed of? I used to have them connected via cable just fine...

Edit:Also, It appears milk it a bit broken in that fluid export, import, and storage buses refuse to work with it

**Comment by XFactHD** [comment]
The fluid assembler is severely broken and will be replaced. Just take a look at #301.

**Comment by SneakyDevil** [comment]
Any info on why milk is suddenly broken?

**Comment by ruifung** [comment]
which mod?

**Comment by SneakyDevil** [comment]
Uhm...Milk? You know. That thing in vanilla minecraft?

**Comment by XFactHD** [comment]
Are you using MineFactory Reloaded? It replaces the vanilla MC milk.
