### ISSUE TITLE
ME Fluid Level Emitter emits redstone signal when offline or missing channel

### ISSUE THREAD

**Issue by Artorp** [ExtraCells/ExtraCells2#325]
Minecraft 1.7.10
AE rv2-stable-10
Extra Cells 2 2.2.73b129

Description of issue:

When a Fluid Level Emitter is offline it will emit redstone signal if the setting for "emit when fluid level is below" is enabled. Instead of being disabled when offline/missing channel it will treat the disconnection as if there aren't any fluid in the network. This is inconsistent with the AE ME level emitter which will never emit a signal if it is offline/missing channel.

Pictures:

![2015-11-20_01 04 31](https://cloud.githubusercontent.com/assets/147366/11288470/9c528ff0-8f24-11e5-8e63-5080e79b43cf.png)

![2015-11-20_01 04 39](https://cloud.githubusercontent.com/assets/147366/11288472/a1116c64-8f24-11e5-936a-8951b0c20d9d.png)

![2015-11-20_01 04 49](https://cloud.githubusercontent.com/assets/147366/11288474/a56c35dc-8f24-11e5-86e6-9b8dd653b8a9.png)

Why this matters:

I was trying to figure out why one day all of my Ender Pearls were gone from the system. I've got a Magma Crucible producing Resonant Ender hooked up to a ME Fluid Emitter which will emit a signal whenever the Resonant Ender goes below 8 buckets. Turns out this system is suffering from random disconnections from the main network (could be due a multitude of reasons which I've yet to find out, most likely due to the server being under stress from a Quarry). Whenever the ME Fluid Emitter is disconnected it will emit a redstone signal and convert more and more Ender Pearls into Resonant Ender. During the course of the day more and more pearls were melted down. Random disconnections aren't ideal of course, but tweaking the behavior of the ME Fluid Level Emitter would at least alleviate the issue.

**Comment by Darkpye** [comment]
Has anyone looked into this issue? The issue should be considered a bug. The nature of the bugs prevents you from sending a redstone signal only when stock is below a given level. If the state is set to emit when stock is below then if the network goes offline then it emits, you set it to emit when above then when it goes offline it no longer emits.

**Comment by Darkpye** [comment]
There is a word around to this issue for any users who might be interested.

It requires to emitters. One of your emitters has to work as a "check to see if online", to do this add an emitter that emits when stock is ABOVE 0 this emitter will always be on when the system is online, but off when system is offline, use this in combination with an ADD gate and you will only emit a signal when both conditions are met.
