### ISSUE TITLE
Dupe liquids/gases with IC2 Cells in Certus Tank

### ISSUE THREAD

**Issue by Krysinski** [ExtraCells/ExtraCells2#329]
I record small video about issue:
https://youtu.be/EVo606tydyY

**Comment by DrummerMC** [comment]
Have you test it with bc tanks too?

**Comment by Krysinski** [comment]
No, i haven't BC on my server long time. This problem has long been known. I decided to write to you since I saw you again started to work on new versions EC2.
I believe that this does not apply to containers BC, or among similar video https://www.youtube.com/watch?v=McUCzzMkQvM would long ago have appeared video with dupe in tanks BC.

**Comment by ghost** [comment]
What version do you using?

**Comment by Krysinski** [comment]
ExtraCells-1.7.10-2.3.0b142

**Comment by spannerman79** [comment]
Update to [ExtraCells-1.7.10-2.3.1b144](http://minecraft.curseforge.com/projects/extracells2/files/2268445)

**Comment by Krysinski** [comment]
Update to ExtraCells-1.7.10-2.3.1b144 will fix this dupe?) If not, updating is useless(
Thanks, i'll try.

**Comment by spannerman79** [comment]
Regardless or not, many (if not all) mod devs require you to be running the most latest recommended release unless directed otherwise.

This is common practise and simply put - common sense.

**Comment by Krysinski** [comment]
Tested with  ExtraCells-1.7.10-2.3.1b144. Dupe is still there.

**Comment by DrummerMC** [comment]
Are you using normal ore universal ic2 cells

**Comment by Krysinski** [comment]
normal cell

**Comment by Krysinski** [comment]
server crashes!!!
http://pastebin.ru/dPAlzs3Z#

**Comment by DrummerMC** [comment]
see #348

**Comment by Krysinski** [comment]
Ok, disabling NEI integration in config fix crash. 
But DUPE is still THERE!!!
