### ISSUE TITLE
fluid registry corrupted

### ISSUE THREAD

**Issue by walkerjonny** [ExtraCells/ExtraCells2#331]
Hi, 
I'm getting this ingame crash shortly after world loading with the last two builds of ExtraCells2.
http://pastebin.com/jkuajce3
Any idea what could have caused this?
ExtraCells-1.7.10-2.2.73b129 is the las build that works fine for me.

**Comment by walkerjonny** [comment]
Thank you for fixing it that fast!
I hope that there will be a release anytime soon

**Comment by DrummerMC** [comment]
Download build 160 or 161
http://shadowcity.net:8080/job/ecrv2/
