### ISSUE TITLE
Mekanism Gas Drives + MineTweaker inconsistency

### ISSUE THREAD

**Issue by 6210classick** [ExtraCells/ExtraCells2#333]
i don't know why but it's impossible to hide Gas House Cell & Gas Drives using MineTweaker (Mekansim is not installed)

if possible can you make it so that it detects when the Mekansim is installed the Gas Drives adds themselves and when uninstalled it gets removed ?

or at least when you disable Mekansim integration in EC config file everything related to Mekansim is removed

EC2 v2.3.2b158
AE2 RC2-Stable-10
Forge 1564

PS : the Universal Terminal has no crafting recipe ?

**Comment by DrummerMC** [comment]
The items are removed if mekanism isn't installed in the next days 

Universall Terminal isn't completly finished
