### ISSUE TITLE
[Suggestion] Larger Block Storage

### ISSUE THREAD

**Issue by Mohron** [ExtraCells/ExtraCells2#334]
Would it be possible to have a larger ME Block Storage Container, not so much for the extra features but for 1 massive cell restricted to a single item type (Think DSU Cell). Hooking up DSUs, Barrels, Caches or other similar single item storage very quickly use many channels/buses and can be a nightmare to keep organized. When I saw the ME Block storage item, I realized it was exactly what I needed except for many of my excessive items had already surpassed the 65,536 number. I would really love to see this type of storage cell in this mod since it already covers the insanely large ME Storage Cell niche.

Edit:

You asked for recipe ideas so here you go. Since the basic cell using a 1k component to provide 64k storage I was thinking similar scaling should be used (making these recipes 4096k). I don't know if 2 billion storage per cell is possible or realistic since worst case scenario is there's 10 of these storage cells in 1 drive completely full.

AE2/EC2 Recipe
![dsucellbasic](https://cloud.githubusercontent.com/assets/3623122/11510900/349d1452-9866-11e5-9651-6392ddcccccf.PNG)
Modpack Recipes
![dsucellmfr](https://cloud.githubusercontent.com/assets/3623122/11511015/ddfe8558-9866-11e5-9199-8ab2c3ba8ae9.PNG) ![dsucellte](https://cloud.githubusercontent.com/assets/3623122/11511036/04249dda-9867-11e5-8842-26516e28902d.PNG) ![dsucelljabba](https://cloud.githubusercontent.com/assets/3623122/11511086/3f7b3420-9867-11e5-9427-999e32562d4f.PNG)

**Comment by 6210classick** [comment]
what about the recipe ? would you say that it needs to have MFR DSU in it ?

**Comment by spannerman79** [comment]
That would I assume make MFR a required dependant not optional for EC2 which isn't exactly a good idea.

Some other alternate crafting recipe would be needed

**Comment by Mohron** [comment]
I made an edit for you guys. If you could possibly enlighten me on what the limit for storage of a 1 type cell would be. I'm guessing the DSUs 2 billion is closely based on some limit imposed by the data type used to store the information. I do like the idea of a DSU based recipe is MFR is installed but obviously reverting to a AE2/EC2 only recipe when other mods are not present.

**Comment by 6210classick** [comment]
the AE2/EC2 Recipe is too cheap i would say at least a single 16M Drive

the same also applies for the other three , 16M Drives is much more balanced given that you can store 10 drives in a single ME Drive

a DSU can store a little over 2.14 billion item

**Comment by Mohron** [comment]
I'm fine with increasing it but I don't know the limits of such a storage cell in a ME. 2 billion in 1 block space seems like a lot. multiplying that by 10 isn't a problem?

**Comment by spannerman79** [comment]
I don't have have minecraft up at the moment and for the life of me I cannot remember the crafting stages for EC2 for the high tier cells, but it would more or less need to follow similiar lines, but limited to 1 item type - sort of like how the (from memory) the creative storage drive within EC2 is like - except its not unlimited.

To set that one item that item could be used in the crafting recipe - to "lock" that drive to that item type. You won't get that item back though but lets be honest here if your going to be using a storage drive that will store the Java limit you'll have more then just one of them.

With EC2 drives you can store more then just one drive in a single block (ME Drive), Jabba/DSU/etc need a full block, so yes crafting a "DSU" type drive should be **much** more expensive

**Comment by Mohron** [comment]
The capability to lock the cell to an item already exists with the cell workbench. So I wouldn't figure that should be overridden.
