### ISSUE TITLE
fluid registry is corrupted

### ISSUE THREAD

**Issue by MapleSight** [ExtraCells/ExtraCells2#336]
Note: Been working for hours on this modpack update... So I may be making a simple mistake somewhere. 

Using the latest AE2 and ExtraCells2 builds from curse forge. Client launches fine. When I go to create a map the client crashes and the report says the fluid registry is corrupted. 

Crash Report: http://pastebin.com/YETmWxwc

**Comment by DrummerMC** [comment]
Download build 160 or 161
http://shadowcity.net:8080/job/ecrv2/

**Comment by MapleSight** [comment]
Forgot to check the jenkins. Tyvm. :D
