### ISSUE TITLE
[REQUEST] Gas Storage Bus and Interface

### ISSUE THREAD

**Issue by cloakable** [ExtraCells/ExtraCells2#338]
Not sure if it's possible or not, but it would be nice to see gasses get the same options for moving them in and out of the system and storing them as the fluids do.

**Comment by DrummerMC** [comment]
I can only add an interface. Storage bus isn't possible

**Comment by spannerman79** [comment]
The way that I get around it is convert the gas into a liquid via [Pressure Pipes Multi-block Tank](https://bdew.net/pressure/multiblock-tanks/) and I can import the liquid that way.

But as to exporting its the same, or you can use other mod's devices to convert the liquid into gas again easily enough.

**Comment by cloakable** [comment]
The PP tank is admittedly nice, but using a minimum of four blocks to convert gas->liquid or liquid->gas does not lead to compact builds. :D

An interface would be a good option for more compact/elegant builds.
