### ISSUE TITLE
[REQUEST] Priority settings and formatting

### ISSUE THREAD

**Issue by ghost** [ExtraCells/ExtraCells2#340]
If this already exists, I am unable to find it. The ability to set priority on Storage Buses is my go to method for voiding excess items. I would love to use the same method to void excess fluid.

See: http://i.imgur.com/pFjZGjt.png The storage bus is configured to a low priority.

Current method of voiding excess liquids: http://i.imgur.com/gT4Pnnd.png
It's rather slow and inefficient, relying on an emitter that activates when extra fluid enters the system.

The four cells on the right are liquid storage cells: http://i.imgur.com/efrmxFS.png

Someone left the xp farm running, jamming up the system. Subnetworks aren't an option either as cells accept fluid indiscriminately. Being able to format these to only accept a single liquid would be exceptional. My apologies if these things already exist, Googling the issue leads to pages upon pages of how to format cells in Microsoft Excel...

**Comment by Artorp** [comment]
You can format/partition a cell to only accept a single type of liquid by using the Cell Workbench. I've done that with all of mine to prevent one liquid input from jamming the system. Is that what you are after?

**Comment by ghost** [comment]
Exactly what I'm after, at least partially. Though when I attempt to format fluid cells on the latest version instead of selecting the liquid, it selects the bucket/tank. Cells formatted this way will still accept all fluids.

**Comment by ZeroInputCtrl** [comment]
I'm running ExtraCells-1.7.10-2.3.5b171 and the cell workbench will partition a fluid drive for me when using a bucket. But what i cannot do is read the drive as use the current contents to partition the drive. Would this be possible to do or is it a AE2 limitation at this point?
