### ISSUE TITLE
Crash on forge server

### ISSUE THREAD

**Issue by adamcirillo** [ExtraCells/ExtraCells2#343]
I used build 164 and it crashes the forge server build 163 was fine. Build 164 on the client I can create a world and load it up no crashes.

here is the log file
[fml-server-3.txt](https://github.com/ExtraCells/ExtraCells2/files/60296/fml-server-3.txt)

**Comment by spannerman79** [comment]
`MinecraftForge v10.13.4.1517 Initialized` - Update to at least `10.13.4.1558`

`fastcraft-1.22-ctest17.jar` - remove fastcraft - even Player states if there are issues disable the mod to ensure if it is fastcraft itself or something else

@DrummerMC the issue starts at line 8659 on the above log.  Looks like its trying to open a GUI when none exists on a dedicated server instance.

**Comment by adamcirillo** [comment]
I'm getting the same error again with build 170 build 165 worked fine when I last used it. I also update forge to 1558 and remove fastcraft as well still was getting it

[fml-server-3.txt](https://github.com/ExtraCells/ExtraCells2/files/66321/fml-server-3.txt)

**Comment by dimitriy0810** [comment]
I'm getting crash with build 170 build 162 worked fine when I last used it. I update forge to 1614 and server crash again
[crash-2015-12-18_16.03.13-server.txt](https://github.com/ExtraCells/ExtraCells2/files/66711/crash-2015-12-18_16.03.13-server.txt)

**Comment by DrummerMC** [comment]
fixed in https://github.com/ExtraCells/ExtraCells2/commit/200d85d27fcd794f66289a2b15dcc056edee7415

**Comment by dimitriy0810** [comment]
Why server crash?

**Comment by DrummerMC** [comment]
because I called a client only class on server

**Comment by dimitriy0810** [comment]
I want to use the new version of ExtraCells on my srver. What do I do? Client works well wuth build 170

**Comment by DrummerMC** [comment]
I already Upload a fix zu curseforge ec2.3.5

**Comment by dimitriy0810** [comment]
Oh, thanks

**Comment by dimitriy0810** [comment]
Now when I open wireless gas terminal and wireless fluid terminal server disconnects me and minecraft write me 'A fatal error has occured, this connection is terminated'
