### ISSUE TITLE
crash 2.3.3b 168

### ISSUE THREAD

**Issue by ghost** [ExtraCells/ExtraCells2#345]
[Server thread/INFO] [FML]: The state engine was in incorrect state SERVER_STOPPING and forced into state SERVER_STOPPED. Errors may have been discarded.
[Client thread/INFO] [FML]: Server terminated.
Exception in thread "AE2 VersionChecker" AL lib: (EE) alc_cleanup: 1 device not closed
open Crafting Monitor

**Comment by spannerman79** [comment]
Add the whole log file. You can attach to the issue or use gist or a paste service (pastebin, paste etc )

**Comment by XFactHD** [comment]
That's a known problem in AE2.
