### ISSUE TITLE
[Duplicate] Fluid Terminal and Gas Terminal share same recipe

### ISSUE THREAD

**Issue by TsumiHokiro** [ExtraCells/ExtraCells2#346]
As the title says, both Fluid Terminal and Gas Terminal have the same recipe (v. 2.3.3b.162).
Also, it seems that the Fluid Terminal recipe has been changed to that of the Gas Terminal (it no longer uses Lapis Lazuli, it is requesting Yellow Dye now.)

**Comment by wlhlm** [comment]
This should have been fixed. Have you tried the latest version? See #341

**Comment by TsumiHokiro** [comment]
Yup, it is, I guess I opened an already reported error since the latest version on Curse hasn't been updated.
