### ISSUE TITLE
Transparent blocks bug because of Certus Tank

### ISSUE THREAD

**Issue by AiramProvoker** [ExtraCells/ExtraCells2#347]
Quite simple and quite annoying visual bug.
Whenever I have Certus Tank placed nearby(even without any liquid), all transparent blocks(leaves, glass) becomes badly rendered/shiny.
Using:
ExtraCells-1.7.10-2.3.4b170
appliedenergistics2-rv2-stable-10
fastcraft-1.22-ctest17
OptiFine_1.7.10_HD_U_C1
Forge 1558

Optifine config: http://pastebin.com/d3LuAFHp
Screenshots: https://imgur.com/a/DHN3l
Thanks in advance.

**Comment by wlhlm** [comment]
Is this fixed when you remove Optifine and/or Fastcraft?

**Comment by spannerman79** [comment]
Ninja'd by @wlhlm :stuck_out_tongue: as I was just about to ask that.

Usually with any issues like that (rendering) remove any and all mods - even client side - that affect rendering.  Including and not limited to just Optifine but also Fastcraft, Liteloader, etc.

**Comment by AiramProvoker** [comment]
Strangely, the same problem appears without Fastcraft and Optifine.
Screenshots (with fancy and without fancy graphics): https://imgur.com/a/4ru6B

**Comment by AiramProvoker** [comment]
Forgot to mention I also had BetterFPS. Removing it also didn't work.

**Comment by spannerman79** [comment]
Confirmed @DrummerMC 
Console Log - http://paste.ee/p/qUaOo

I wouldn't say transparent, but leaves do have a weird graphical "effect"

Before Placement of Certus Tank
![2015-12-19_00 57 02](https://cloud.githubusercontent.com/assets/7542384/11898406/c17a2a30-a5eb-11e5-9742-3972421fc98c.png)

After Placement of Certus Tank
![2015-12-19_00 57 12](https://cloud.githubusercontent.com/assets/7542384/11898418/d061880e-a5eb-11e5-9445-3eadb631595b.png)

Visibly evident viewing leaves afar
![2015-12-19_01 05 30](https://cloud.githubusercontent.com/assets/7542384/11898573/db4e69f2-a5ec-11e5-86ea-f05f374d2c8e.png)

Similar but not as bad as what I reported back in #231

Also reported in #232

**Comment by AiramProvoker** [comment]
I realize Blast Resistant Drive is still unfinished (it has "[WIP]" written in its name), but it also causes the same visual bug.

**Comment by spannerman79** [comment]
> I realize Blast Resistant Drive is still unfinished (it has "[WIP]" written in its name), but it also causes the same visual bug.

That is why I referenced the issue I raised in relation to the WIP Blast Resistant Drive @AiramProvoker.  In order for @DrummerMC to see if its sharing any rendering code etc

**Comment by AiramProvoker** [comment]
I understood it and it's smart. 
Seems like we can only wait for @DrummerMC answer now.

**Comment by AiramProvoker** [comment]
ExtraCells-1.7.10-2.3.5b171
fastcraft-1.22-ctest17
BetterFPS 1.01
OptiFine_1.7.10_HD_U_C1
Forge 1558
Optifine config: http://pastebin.com/d3LuAFHp
Game crashes with the next crashlog: http://pastebin.com/AZM2XgMj
Not sure if I need to make another topic.

**Comment by spannerman79** [comment]
As always and general rule - for issues **only** run the mod/mods required.

> fastcraft-1.22-ctest17
> BetterFPS 1.01
> OptiFine_1.7.10_HD_U_C1

Not required for testing purposes.
