### ISSUE TITLE
Minecraft server trowths of the game with error

### ISSUE THREAD

**Issue by dimitriy0810** [ExtraCells/ExtraCells2#350]
When I open wireless gas terminal and wireless fluid terminal, server disconnects me, and minecraft writes to me 'A fatal error has occured, this connection is terminated'. Wireless universal terminal doesn't work with mode fluid and gas. Client works fine with ex 2.3.5b171. What should I do?
Versions:
forge 10.13.4.1614
extracells 2.3.5b171
appliedenergistics2 rv2 stable 10
Server log: http://paste.ubuntu.com/14113482/

**Comment by spannerman79** [comment]
1. Learn how to open and create issues properly.  What you have provided isn't step by step.
2.  Logs?  None provided.
3. Check your web browsers spell checker

**Comment by ZeroInputCtrl** [comment]
I think this would be part of the same issue the op is having. I'm running 
ExtraCells-1.7.10-2.3.5b171
appliedenergistics2-rv3-beta-1
AE2TechAddOn-1.7.10-1.0-b81-universal
ae2stuff-rv3-0.5.1.9-mc1.7.10

When I have a universal wireless terminal in hand if i shift-right-click than right-click it opens up the fluid terminal for me. If i shift-right-click than right-click again the game crashes. I've done this with the fluid  and gas add-ons and with the fluid add-on only with the same result.
Client Logs:
https://gist.github.com/DeathCorps69/4fa8a4b3ac0b68af6410
https://gist.github.com/292422ff93633b615c63

Server Logs:
https://gist.github.com/DeathCorps69/012c007181b4bd6c801b

**Comment by ZeroInputCtrl** [comment]
Scratch that even pulling up the fluid terminal breaks from the universal wireless terminal now that I have a Fluid Storage Drive in place.
