### ISSUE TITLE
Fluid Export Bus Crash

### ISSUE THREAD

**Issue by HandGrenade** [ExtraCells/ExtraCells2#351]
Hello,

Whenever I open the Fluid Export Bus, and go to click on a bucket (Anywhere in my inventory), with the GUI open, I crash with the following crash-log:
http://pastebin.com/rAweRSuW

Versions:
Forge - 1541
AE2 - rv2 stable 10
Extra Cells - 2.3.3b162

If you require further information or testing, I'd be happy to provide.

Thanks. :)

**Comment by spannerman79** [comment]
> Forge - 1541

Update to at least 1558

> Extra Cells - 2.3.3b162

Newer version available.

**Comment by HandGrenade** [comment]
Seems that by simply updating Forge (With the same Extra Cells Version) the issue is resolved. Thanks :)
