### ISSUE TITLE
Crash V2.3.5b171

### ISSUE THREAD

**Issue by YukiRainee** [ExtraCells/ExtraCells2#354]
dont really know what this crash means but it happens when I try to put it on my server

pastebin.com/sZ9FFvES

**Comment by Dream-Master** [comment]
same here

#352

**Comment by YukiRainee** [comment]
thanks ill check the config and turn it off 
hopefully it works

**Comment by Dream-Master** [comment]
it works but on server you get a spam log. I think we have to wait for a new version.

**Comment by spannerman79** [comment]
The console spam I think is just debugging code left behind thats all.

Also as a note - it _is_ Christmas, so give @DrummerMC some actual time for family/friends.Even more so for this time of year.
