### ISSUE TITLE
[Major Bug] Unlimited fluid extraction through fluid storage busses

### ISSUE THREAD

**Issue by fsedarkalex** [ExtraCells/ExtraCells2#355]
Please see this video for reference: https://youtu.be/yGhreP7lkqg

When using a fluid storage bus you can extract unlimited amounts of fluids from an ME system.
The video shows that issue using EC2's Quartz Tanks but this can be reproduced with any fluid container.

Whan having at least 1mB of fluid in a tnak connected through a fluid storage bus, you can always fill one container completely with fluid. e.g. having 1 mB in a quartz tnak connected through fluid storage bus would allow to fill 65536000mB into a bedrockium drum using the fluid terminal.
The bug is definitey within storage busses as it does NOT happen using fluid storage cells.

Furthermore I read about this bug: https://github.com/ExtraCells/ExtraCells2/issues/243
You cna see it at the end of the video also. if you got other fluids within your ME system you can see that storage-bus-connected fluids get updated whenever any other liquid changes in the system also.
Why I am writing this here is as I thought probably those issues are linked to each other.

(Btw: Using FTB infinity evolved with EC2 2.2.73 here)

**Comment by spannerman79** [comment]
Update EC http://shadowcity.net:8080/job/ecrv2/lastSuccessfulBuild/artifact/build/libs/ExtraCells-1.7.10-2.3.6b174.jar

**Comment by fsedarkalex** [comment]
damned the major bug is fixed. simply the storage levels not reported back automatically are left

**Comment by spannerman79** [comment]
That is why I **never** use a third party modpack.

And its why you should of reported this over at the FTB forum - **not here**

**Comment by fsedarkalex** [comment]
yep.
Do you know which version has the change? Is it fixed in every 2.3.6 release?

**Comment by DrummerMC** [comment]
Already fixed
