### ISSUE TITLE
Recipes

### ISSUE THREAD

**Issue by idnthvn** [ExtraCells/ExtraCells2#359]
I am having issues seeing Recipes for the Gas side of the Import/export/storage buses and the Use of the Gas system it self???? If anyone could shine some lite with this??? The server i play on has the latest NEI and i think the 2.3.5 version of Extra Cells. I know there are new versions, but none that correct this direct issue, 
If someone could shine a light on this so i can pass this info along. 
Thank you

**Comment by Dream-Master** [comment]
In the newer version the Gas Terminal and Busses etc are hidden if you not have Makanissem.

**Comment by idnthvn** [comment]
@ Dream-Master, Playing on a server that has Mekanism, But it doesnt allow us to see the Recipe's on the Gas side of things, Was hoping someone could let us know what they are or how to find them?

**Comment by Dream-Master** [comment]
We have ExtraCells-1.7.10-2.3.3b162 no mekanism and see the Gas terminal. The new version 172 and above not show the items any more.

**Comment by idnthvn** [comment]
Dream-Master Could you post screen shots of the recipe's? for the gas??? Maybe somethign silly that its the same as liquid but exchange the Lapis for something?

**Comment by Dream-Master** [comment]
sure
![screenshot 2015-12-30 00 49 45](https://cloud.githubusercontent.com/assets/2970688/12044304/5ac99850-ae8f-11e5-8de2-d3fc1a84fc87.png)
![screenshot 2015-12-30 00 49 50](https://cloud.githubusercontent.com/assets/2970688/12044307/5acd86b8-ae8f-11e5-86db-fd87b107b0ed.png)
![screenshot 2015-12-30 00 49 53](https://cloud.githubusercontent.com/assets/2970688/12044306/5acc74bc-ae8f-11e5-91f6-9ada5dd9966a.png)
![screenshot 2015-12-30 00 50 12](https://cloud.githubusercontent.com/assets/2970688/12044305/5acc4cf8-ae8f-11e5-9433-275010fc47ff.png)
![screenshot 2015-12-30 00 51 13](https://cloud.githubusercontent.com/assets/2970688/12044315/79c88040-ae8f-11e5-87ed-2b16d821e608.png)
![screenshot 2015-12-30 00 51 22](https://cloud.githubusercontent.com/assets/2970688/12044316/79caaf14-ae8f-11e5-8114-0adcccd6b814.png)

**Comment by DrummerMC** [comment]
The Items would hide if the Makanism Gas API isn't loaded. The recipes wont be removed if the gas System is not installed/disabled in the config.

**Comment by Dream-Master** [comment]
This was only in a old Version 162. But now it is hidden.  For me everything is fine. I not using Mekanism.

**Comment by DrummerMC** [comment]
On my tests the recipes work with and without mekanism. Only the items are hidden

**Comment by Dream-Master** [comment]
Ok. I never test it.

**Comment by Dream-Master** [comment]
btw runs extra cell together with newest AE2 RV3 Beta 2 ?

**Comment by idnthvn** [comment]
Fixed, Server did NOT have the latest update and was running on a version during a transition for Gas's (New issue which i posted about)
