### ISSUE TITLE
ME Fluid Export bus bug

### ISSUE THREAD

**Issue by tekkitan** [ExtraCells/ExtraCells2#361]
I think I've seen this same bug with import buses, but my most current and memorable experience is trying to export Essence from my ME Fluid system into an MFR Auto-Spawner. After a while it seems it will completely stop importing fluid and the device will report as offline. I checked all the channels and the whole channel leg was only using 2 of 8 channels. Everything checked out fine. If I logged out of my server then back in again, it would come online then without any changes. It seems the buses lose their channels somehow occasionally.

The bus will also report it is missing a channel while the cable says there are 1 of 8 channels in use (only device on the cable) and it will still continue to function.

Running FTB Infinity 2.2.2 for reference.

**Comment by kerenon** [comment]
Same issue here with import busses. Every time I restart my server, all the import busses go offline. Removing and re-adding a piece of cable or replacing the busses fixes the problem. Tried completely disabling the channel-system, but it didn't help.

**Comment by Muzarmo** [comment]
I got something like this as well. Tried to put ME Fluid Export buses on the network and channels would randomly not work. I use ME P2P and sometimes the missing channels would appear on conduits that didn't even have a Extra Cells Export Bus. Removing the Fluid Export Buses solved the problem.
