### ISSUE TITLE
Asscess Fluid Universe Terminal server crash

### ISSUE THREAD

**Issue by TheBlueKingLP** [ExtraCells/ExtraCells2#363]
error log:http://pastebin.com/raw/d2WCWGZz
I am using Universal Terminal Fluid mode,on the normal fluid terminal no this problem,just the universal terminal crash my server.

Edit:some time not crash,just this error and kick me from the server: http://pastebin.com/raw/mNLEEb25

**Comment by DrummerMC** [comment]
Can you try the last version from the build server?

**Comment by Nedelosk** [comment]
Fixed in 1.10.
