### ISSUE TITLE
Gas Import bus not responding to redstone card

### ISSUE THREAD

**Issue by adamcirillo** [ExtraCells/ExtraCells2#364]
Having trouble using the gas level emitters with the gas import bus they don't seem to respond to Redstone signal from the emitter don't know if its the emitter or the bus itself. Also have put a Redstone Card & set to active without signal. Fluid Emitters work fine.

Using Extra Cells 2.3.7b182
Ae2 Rv2 Stable 10

Here is the picture of my setup

![gas import redstpme](https://cloud.githubusercontent.com/assets/13363284/12215087/8a8f1496-b701-11e5-8162-2b2a162ea148.png)

**Comment by Jizanthapus** [comment]
Also having this problem with a nearly identical setup

Forge: 10.13.4.1614
AE2: rv3-beta-5
ExtraCells2: 2.3.9

**Comment by Basili0** [comment]
Same problem.

Forge 10.13.4.1558
AE2 rv3-beta-6
ExtraCells2 2.3.9b188

**Comment by mkaito** [comment]
I don't know what "triaged" stands for, but this is still happening in 2.6.5, AE2 rv6-stable-7.
