### ISSUE TITLE
The Game closes Universal Terminals when pressing "t"

### ISSUE THREAD

**Issue by gabor7d2** [ExtraCells/ExtraCells2#367]
## Description

I encountered a small problem, when I press t on my keyboard, it closes the Universal Terminal. This doesn't happen on an AE2 Terminal (Wireless). I have set the Universal Terminals (along with all the other terminals) to search **NEI Synchronized Auto** and this happens when I open the Wireless Universal Terminal, and try typing something in. Sometimes it doesn't exit the GUI, it just doesn't write the t letter. If I click in the search box (on the terminal) and then type, everything works fine. This is not an issue on AE2 Terminals.

**Sorry if this is an intended feature or an already known issue.**
### Screenshots:

_Typing in "stone" in Universal Wireless Terminal_
![2016-01-16_15 59 58](https://cloud.githubusercontent.com/assets/12859334/12372984/59f1768a-bc6a-11e5-88bf-07481dfd091a.png)

_Typing in "stone" in AE2 Wireless Terminal_
![2016-01-16_16 01 43](https://cloud.githubusercontent.com/assets/12859334/12372988/766ba5d8-bc6a-11e5-8096-ae784561cbae.png)
### Versions:

**Applied Energistics 2**: rv2-stable-10
**ExtraCells 2**: 2.3.7b176
I am playing on FTB BeeHappy with a few mods added (I think one of which is this mod)

**If you need forge logs, modlist, or anything like that, tell me.**
**Thanks for the help!**

**Comment by adamcirillo** [comment]
its related to extra utilities its got a key binding on t in the nei controls that will search for an item in a nearby inventory go into nei options and change it.

**Comment by gabor7d2** [comment]
Thank you so much for the information! :smile: Though, in the mod's perspective this is still an issue, as it doesn't happen to normal AE2 Wireless Terminals.

**Comment by adamcirillo** [comment]
well it happened to me on all the ae terminals including wireless what happens when u press t hovering over the item it activates the feature so if not over a item and press t it will go in the text field.

**Comment by gabor7d2** [comment]
Oh, okay I see. I tested it, and it's definitely that, probably because when I open the terminal it looks at an item. And I can confirm it is in all the terminals, but sometimes it works and doesn't have any issues with "t". Only the Crafting Terminal doesn't do this because when I open it the cursor isn't on an item. Anyway, thanks for the help! So this is not an issue then, right ? (It's kind of an issue but definitely not EC2, maybe AE2 or NEI, or it should be turned off by default because personally I don't even know what that does).

**Comment by adamcirillo** [comment]
you just need to change the keybinding click the option then go into the keybindings I set mine to right control that way it doesn't interfere with anything

**Comment by gabor7d2** [comment]
Already did that :smile: I was just testing that all the wireless terminals does this then (at least the ones with items), so this is definitely not an EC2 issue, I am **closing** this.

Thanks for the help!
