### ISSUE TITLE
Patterns to Export Gas's

### ISSUE THREAD

**Issue by idnthvn** [ExtraCells/ExtraCells2#369]
I cannot get the Pattern's to work with Gas's 
Is there a way to export the Gas's out of the ME System that i am not seeing?
I have tried the Pattern's but with no luck on Gas's Only Liqued's 
I have gotten the server to update to version 2.3.7b176
Let me know if there is a solution or do i need to wait for this to be done?

**Comment by idnthvn** [comment]
I did see WIP on them, Didnt know if i was loosing my mind or somethign too

**Comment by adamcirillo** [comment]
do you want to select what gas the export bus uses? if so put a gas tank with some of the gas you want to export and using like a bucket in the fluid export bus.

**Comment by idnthvn** [comment]
That works PERFECTLY   Thank you (i will see if i can do a small link on youtube later tonight!

**Comment by LuciDuki** [comment]
i can'T export any gases from my me system.
the gas's are Deuterium and Tritum from Mekanism.
i tried the tip from adamcirillo but it doesn't work.

**Comment by LuciDuki** [comment]
i use Version 2.3.14

**Comment by woodzykiler** [comment]
the gases will export/import jsut fine, but we cant tell the Gas cell(drive disk) what gas to hold...

**Comment by CSmither** [comment]
I found using any tank containing the gas (Such as the gas tanks from Mekanism) you can open the GUI for the export bus and place the tank on the filter box to select that gas for export. It does require a mod with a gas tank though.
