### ISSUE TITLE
Applied Energistics 2 rv3?

### ISSUE THREAD

**Issue by xJon** [ExtraCells/ExtraCells2#370]
Hi,
As I saw here already in some issues, the latest version of Extra Cells does work with rv3, but you're still using rv2 API. Any reason?
Thanks

**Comment by spannerman79** [comment]
I would assume that some of the API stuff that Extra Cells uses is still on rv2 - for example Thaumic Energistics ( https://github.com/ExtraCells/ExtraCells2/blob/rv2/src/api/java/thaumicenergistics/api/ThEApi.java )

I'd say it will be updated Soon <sup>TM</sup>

**Comment by xJon** [comment]
@spannerman79 Do you think using rv3 with the latest version of Extra Cells can cause problems?

**Comment by Dream-Master** [comment]
Thamuic Energistics hava already a rv3 version.
http://minecraft.curseforge.com/projects/thaumic-energistics/files/2277332

**Comment by XFactHD** [comment]
@xJon This shouldn't cause problems.

**Comment by Dream-Master** [comment]
We used it in a modpack and we not have problems so far.

**Comment by spannerman79** [comment]
> Do you think using rv3 with the latest version of Extra Cells can cause problems?

In theory - no.  But as always keep world backups. Everyone should have a habit of keeping at least one backup at any rate LOL

**Comment by XFactHD** [comment]
So true...

**Comment by xJon** [comment]
:+1:

**Comment by DrummerMC** [comment]
all rv2 versions with versionnumber 2.3.x works with rv3

**Comment by Dream-Master** [comment]
:+1:
