### ISSUE TITLE
Crash with EC 2.3.8b186 and AE rv3

### ISSUE THREAD

**Issue by Kanol** [ExtraCells/ExtraCells2#372]
Minecraft crashes with 2.3.8b186 and AE rv3
[crash-2016-01-30_23.47.25-client.txt](https://github.com/ExtraCells/ExtraCells2/files/110941/crash-2016-01-30_23.47.25-client.txt)

**Comment by DrummerMC** [comment]
Use the Last version on curseforge 

Von meinem iPhone gesendet
