### ISSUE TITLE
Cell workbench integration

### ISSUE THREAD

**Issue by Gowcu** [ExtraCells/ExtraCells2#374]
Is it possible to use the gas and fluid storage cells in the cell workbench to exclude other fluids from entering a storage cell. If not would you be able to include this feature in a future update?

**Comment by XFactHD** [comment]
This is already possible with fluid cells but I don't know if it's the same for gas cells.

**Comment by Gowcu** [comment]
i just tested it and i wasn't able to configure either the gas or the fluid storage cells to be exclusive. i am running version 2.3.7b176, if it has been updated since then i am sorry to have bothered you. BTW i used the ME Fluid Pattern for the fluid, and a Mekanism Tank for the gas. With both storage cells when i inserted them back into the cell workbench the changes i had made were not there.

**Comment by XFactHD** [comment]
Try using a bucket instead of the fluid patterns.

**Comment by Gowcu** [comment]
So i tried it with using the bucket and it worked 1 out of 2 times, the first time when i put the bucket it, the bucket icon turned into a water source icon and the programming didn't stick. The second time the bucket icon didnt change and the programming stuck. When would Cell workbench support be available for the Gas Cells do you think?

**Comment by XFactHD** [comment]
I don't know, I am not the developer.

**Comment by cecell** [comment]
+1 Please allow partitioning of ME Gas Storage
