### ISSUE TITLE
ExtraCells prevents reading of essentia levels with OpenComputers

### ISSUE THREAD

**Issue by Belgabor** [ExtraCells/ExtraCells2#377]
As soon as ExtraCells is installed I can no longer read essentia levels (Thaumic Energistics) via the getFluidsInNetwork method.

**Comment by DrummerMC** [comment]
Disable extracells in the oc config

**Comment by DrummerMC** [comment]
I will Talk to sangar to add a getEssentiaInNetwork function

**Comment by Belgabor** [comment]
That would probably be the best solution.

On the config, I couldn't find anything related to ExtraCells in the OC config, were you referring to the OC option in the ExtraCells config? I tried turning that off (as well as the Thaumic Energistics config), neither helped.
