### ISSUE TITLE
Fluid Storage Bus dont work with inverter card

### ISSUE THREAD

**Issue by TaiGel** [ExtraCells/ExtraCells2#379]
I try to blacklist stored fluids and it dont work

**Comment by spannerman79** [comment]
Oh wow, like I know exactly how to re-produce your issue.........

What build number? How did you exactly try to blacklist.....

A dev needs **exact** reproduction steps.

**Comment by TaiGel** [comment]
Np i try to give you this info.
version 2.3.7b176

i insert Inverter card in storage bus and fill all blacklisted fluids in fields on center window

Screenshots:
http://joxi.ru/4Ak5z6tMKQzpmq
http://joxi.ru/E2pKeZuBXKgOmY

**Comment by spannerman79** [comment]
Old mod version - update

**Comment by TaiGel** [comment]
It work now THX, but this version in latest FTB Infinity Evolved modpack. And another users can find this issue too

**Comment by spannerman79** [comment]
Blame the modpack creator - not the mod dev @TaiGel
