### ISSUE TITLE
The I&Opart of Gas Storage Textures

### ISSUE THREAD

**Issue by Fnober** [ExtraCells/ExtraCells2#380]
ME gas input&output BUS and others part have same textures as fluid.
But I think they should be yellow not blue.

**Comment by Aivech** [comment]
Doesn't Mekanism use orange for gases?

**Comment by Fnober** [comment]
sry The yellow means orangeXD

**Comment by CyanideCarrot** [comment]
The accepted label was added more than a year ago and yet this is still not implemented?
