### ISSUE TITLE
Import and export busses fail. (Saying missing channel. and smart cable disagree)

### ISSUE THREAD

**Issue by iceman11a** [ExtraCells/ExtraCells2#381]
I have a export bus trying to get oil from a network that's full of oil. I try and export the oil to a small red tank. The bus says missing channel. How ever the smart cables say that I have every thing right. So the version I have tried this with are listed below. In any case the export bus fails to export any thing. and I have the same problem with the import buses. 

ExtraCells-1.7.10-2.3.9     Release 1.7.10  53,325  Feb 7, 2016
ExtraCells-1.7.10-2.3.8     Release 1.7.10  15,584  Jan 29, 2016
ExtraCells-1.7.10-2.3.7     Release 1.7.10  132,800 Dec 28, 2015
ExtraCells-1.7.10-2.3.6     Release 1.7.10  2,971   Dec 25, 2015
ExtraCells-1.7.10-2.3.5     Release 1.7.10  41,164  Dec 18, 2015
ExtraCells-1.7.10-2.3.4   Release   1.7.10  811 Dec 17, 2015

I just tested all of these versions of this mod. and I can't go back to the version I had before. My server crashed because of the other mods I updated needed a newer version of Extracells. So until this gets fixed. Nothing I can do. 

I have a 132 mods on my server. If you want a list. Let me know. and I'll make one.

**Comment by XFactHD** [comment]
Try causing a block update by placing a block adjacent to the import or export bus. The bus should say "online" and should export or import whatever you want.

**Comment by iceman11a** [comment]
Hope. That didn't work, I even tried to bust it and replace it with a new one.

**Comment by Aivech** [comment]
Try a redstone pulse.

**Comment by iceman11a** [comment]
how do I do a redstone pulse on a import, export bus.

**Comment by Aivech** [comment]
Just put a lever next to it and turn it on and off

**Comment by XFactHD** [comment]
You need to put a Redstone card into the bus.

**Comment by iceman11a** [comment]
Ok, I'll try that. So I put a redstone card in and put a leve next to it. and us the lever to turn it off or on. Got ya. Thanks
