### ISSUE TITLE
Storage size discrepancy between AE2 and EC2

### ISSUE THREAD

**Issue by SephirothWS** [ExtraCells/ExtraCells2#383]
So, I currently have a 64k storage cell specifically partitioned and set aside for the various ingots my AE system stores at this time. It's getting close to full.

![Image](http://i.imgur.com/VcQJgpD.png)

So I crafted a 256k storage unit from EC2, and via the ME I/O Port, moved all the items to the 256k unit and re-partitioned it.

![Image2](http://i.imgur.com/RytuLVh.png)

Somehow the same exact contents of the cell uses more than twice as many bytes. This doesn't really make sense. o_O

Using ExtraCells-1.7.10-2.3.7b176.jar with appliedenergistics2-rv2-stable-10.jar

**Comment by spannerman79** [comment]
Just for the sake of testing (and my memory is shot at the moment) doesn't the AE2 WAWLA component allows you to view the number of items within a drive? 

A side note:

I do notice with AE2 it will move items around by itself into drives that contain the majority of that item.
For example if i have a ME bank that contains 10k of cobble, stone & gold as well as other little bits and pieces spread across multi storage cells and I add a larger capacity drive it will shift by itself the majority of one item to a single storage cell.

You didn't do a before/after check of your other drives did you?  If you did you will notice that more then likley the bytes of those cells will be freed up.

**Comment by SephirothWS** [comment]
As the 256k cell is partitioned to only accept the correct items, I can ensure that the same exact items are on the cell. I had completely dumped everything out of the AE system and imported it back in with the partitioned cells on a higher-priority drive than the rest of them, so I know there's no discrepancy between the two screenshots. Same amount of item types, and I even have a screenshot or two of the contents of the drive via a ME Chest.

The report is the fact that EC2 calculates item bytes differently than how AE2 itself calculates them; which doesn't really make any sense at all.

# 256k Storage Unit

![image1](http://i.imgur.com/LchQEST.png)
![image2](http://i.imgur.com/SfvvXn5.png)

# 64k Storage Unit

![image3](http://i.imgur.com/55Jm05W.png)
![image4](http://i.imgur.com/WF9ZDvP.png)

**Comment by spannerman79** [comment]
Perhaps EC2 follows this http://www.tweakandtrick.com/2013/07/lost-storage-space.html :stuck_out_tongue: 

Perhaps I don't take much notice because of that difference in that link over the many years.

**Comment by XFactHD** [comment]
I think this is the same as in AE2. Have you compared a 16k with a 64k? Should be the same phenomenon.

**Comment by Aivech** [comment]
That looks like standard AE2 behavior - all cells store the same amount of item types and inserting just one item of a new type takes WAY more storage than inserting another item of a type already on the drive - the bigger the drive, the more storage inserting a new type takes.

**Comment by SephirothWS** [comment]
So you're telling me that inserting a single item onto the 256k drive is -supposed- to take up more than twice the space than inserting that single item onto a 64k drive? This doesn't make any sense what so ever. If this is the case, might as well just not use the larger drives from EC2 since that's essentially a waste of resources.

**Comment by Aivech** [comment]
Yes, but only when you insert an item that is NOT already on the drive. Once an item type is on the drive, you can store more items of the same type at ~1 byte/item (pretty sure its 1 byte/item)

**Comment by Aivech** [comment]
The same thing happens with 1k, 4k, and 16k storage cells, except inserting an item of a new type takes proportionally less space.

**Comment by spannerman79** [comment]
@SephirothWS http://ae-mod.info/ME-Storage-Math/ - confirmed.

This is intended behaviour.

Issue should be closed.

**Comment by SephirothWS** [comment]
Fine. I'll close this issue. I still find it ridiculously stupid that this so-called "math" exists. An item is an item. It shouldn't be larger just because its a larger storage cell.

**Comment by Aivech** [comment]
@SephirothWS It's their way of enforcing the 64 types per cell limit.

**Comment by Aivech** [comment]
You can still fit more items in a bigger cell.
