### ISSUE TITLE
Cards stored in Network Tool aren't drawn in correct locations

### ISSUE THREAD

**Issue by Viper007Bond** [ExtraCells/ExtraCells2#384]
I have the Network Tool in my inventory and I keep my cards in there for use in devices. Here it is in a vanilla AE UI:

![2016-03-11_00 08 57](https://cloud.githubusercontent.com/assets/406254/13696799/89820fc6-e71d-11e5-93d1-164e1d415d10.png)

Now compare to an Extra Cells UI:

![2016-03-11_00 08 22](https://cloud.githubusercontent.com/assets/406254/13696803/9068c762-e71d-11e5-951c-f1caae539ae8.png)

Note the difference in card locations.

ExtraCells-1.7.10-2.3.7b176

**Comment by XFactHD** [comment]
Report this to ExtraCells, they are assigning the slots in a different order.

**Comment by Viper007Bond** [comment]
> Report this to ExtraCells

I'm confused -- isn't that where I am?

**Comment by XFactHD** [comment]
WTF, when I wrote this, I thought you put this issue on the AE2 github (I am sure I read AppliedEnergistics at the top of the page). I feel dumb now.
