### ISSUE TITLE
Gas disk formating

### ISSUE THREAD

**Issue by Gonza-** [ExtraCells/ExtraCells2#386]
I can't format a disk to accept only 1 type of gas using gas tank or gauge. i can only do it using creative drums or openblocks tank filled with the gas

**Comment by Cbert** [comment]
Confirmed, there is no legitimate way to Partitioned - Precise Gas Storage in survival.

Also ME Gas Conversion Monitor can’t be configured.

**Comment by woodzykiler** [comment]
Can we make the gas cells Partitioned plz? gases are clogging up the drives to the point the gas system is becoming useless..

**Comment by cecell** [comment]
+1 Please allow partitioning of ME Gas Storage
