### ISSUE TITLE
Loss of liquid when inserting into network using Terminal

### ISSUE THREAD

**Issue by Sil3ntStorm** [ExtraCells/ExtraCells2#388]
If you put a drum storing an amount of liquid greater than the available space in the network for that liquid into a Fluid Terminal / Wireless Terminal it'll drain the entire drum even though there was no space for the entire content of the drum.

Example: Network with 1k Fluid Cell (capable of storing 256 buckets worth of a single fluid) which has 10 buckets worth of Lava in it, then open Combo Wireless Interface on Fluid mode and insert a full Lava drum into the left slot. It'll give you back an empty drum and the 1k fluid disk will be full. Put the empty drum back in the left slot, select lava and get a full lava drum in the right slot with the disk now being empty. You just lost 10 buckets worth of Lava.

Instead of getting an empty drum in the right slot you should be getting a drum that has 10 buckets worth of Lava left in it, as there was no room for those in the network.

AE2 rv3 beta 5
EC2 2.3.9b188
MC 1.7.10
FML 7.99.39.1566 (according to log)

**Comment by Aivech** [comment]
Is this related to an issue where if you fill a container and there is less fluid in the network than there is container space, it fills the container regardless?

**Comment by Sil3ntStorm** [comment]
Filling a container larger than the total amount of the liquid in the network correctly fills the container with the amount of fluid available in the network in the above mentioned version. (e.g. have 10 buckets of lava in the network, put in an empty drum and you get a drum with 10 buckets of lava).
Maybe you're using a different version.

**Comment by DrummerMC** [comment]
are you use the storage bus or a fluid cell?

**Comment by Sil3ntStorm** [comment]
@DrummerMC using a cell as per the original post: "Example: Network with 1k Fluid Cell"
No other liquid storage available/attached to the network
