### ISSUE TITLE
Fluid Level Emitter fails until restart

### ISSUE THREAD

**Issue by emperor06** [ExtraCells/ExtraCells2#389]
Say I have 10,000 mb of Gelid Cryotheum.
I set a level emitter to emit when above 5,000 and I use a bucket of gelid cryo to set the filter.
The emitter should emit but it doesn't. Now if I save quit and reload the world, the emitter works as expected.

Now if I edit the level emitter settings in the GUI and click the filter to remove it (no more filter), the emitter works as if it was still monitoring the gelid cryo.

If I use a bucket of water to set a new filter, the emitter stops watching the level of gelid cryo.
If I use a bucket of gelid cryo again, the emitter won't update and will fail monitoring gelid cryo until a restart.

It looks like there's an issue with filter update.
Note that forcing a block update never worked for me. I have tried to place another block near the emitter, a part (terminal) on the same block as the emitter, some redstone pulses around, break the cable it's attached to and remove/restore the channel, none of these worked. Only a restart of the world works around this issue.

(version is the latest, compiled from git today so 2.3.9 iirc)

**Comment by Aivech** [comment]
Does it start working if you unload and reload the chunk?

**Comment by emperor06** [comment]
Yes, reloading the chunk makes it work.
I've done a few more tests, here are the results.

When changing the filter, the NBT data updates correctly.
Test case: 10,000 water and 5,000 cryo stored in the system.
Emitter set to shine when water is above 6,000.
After a chunk reload, the emitter is on.
Filter change to cryo. the emitter should be off (< 6,000) but it is still on.
Add or remove a simple bucket of cryotheum in the system.
Now the emitter is off as expected.

It seems that onStackChange() is not called when changing the fluid filter so currentAmount is not updated until the filtered fluid stack changes in the system (or the chunk is reloaded).

**Comment by emperor06** [comment]
I just did a quick test in the code, a manual update of currentAmount from the grid cache in SetFluid(), after this.fluid is set and right before the watcher is updated. It works. But it's probably not the best way to fix it (I'm not in AE development at all). At least we know there's something wrong with currentAmount not reflecting the actual amount :)

**Comment by lee321987** [comment]
I'm pretty sure this is also effecting the ME Storage Monitor.
