### ISSUE TITLE
Draconic Evolution

### ISSUE THREAD

**Issue by Evulperson** [ExtraCells/ExtraCells2#391]
It seems that the Wyvern/Draconic Flux Capacitors will drain themselves entirely at an alarming rate, while trying to charge an already 100% full Wireless ME Fluid Terminal. This has also been submitted to Brandon3055@Draconic Evolution

**Comment by brandon3055** [comment]
@ExtraCells Im fairly certain this is not an issue on my end. Sounds like your IEnergyContainerItem#receiveEnergy method is not returning 0 when the item is full.
