### ISSUE TITLE
Blinking ME Fluid or Gas Level Emitter

### ISSUE THREAD

**Issue by Cbert** [ExtraCells/ExtraCells2#392]
ME Fluid or Gas Level Emitter blinks when level of a specified Fluid or Gas changes fast.
So I suggest to add a function similar to EnderIO Power Monitor. It would help to reduce blinking.
![2016-04-24 12 55 24](https://cloud.githubusercontent.com/assets/9320867/14766687/142c4c88-0a1c-11e6-9cff-25ff2a3c4026.png)

**Comment by spannerman79** [comment]
This happens even with the Multiblock tanks from Pressure Tanks when using redstone control.

I would (assume) this is the norm for any redstone based control - even if you have it set at a percentage it still would change and cycle - or "blinks" as you state it - when levels go above or below even a percentage level as you have given as your example.

**Comment by Cbert** [comment]
spannerman79
https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/2248
