### ISSUE TITLE
Render Bug with Blast Resistant ME Drive

### ISSUE THREAD

**Issue by maksim789456** [ExtraCells/ExtraCells2#393]
## When you place down the Blast Resistant ME Drive there are some graphic glitches.

![2016-04-26_17 28 00](https://cloud.githubusercontent.com/assets/8225008/14821821/ddc794a8-0bd4-11e6-9845-bb6e61d0a6ba.png)
![2016-04-26_17 35 38](https://cloud.githubusercontent.com/assets/8225008/14821929/54c0db14-0bd5-11e6-936c-2555e511abfb.png)
![2016-04-26_17 35 43](https://cloud.githubusercontent.com/assets/8225008/14821936/5931b4de-0bd5-11e6-8415-064da6b9020d.png)

**Comment by spannerman79** [comment]
Dupe https://github.com/ExtraCells/ExtraCells2/issues/231
