### ISSUE TITLE
Recipie Overlap between Buildcraft Tanks and Certus Quartz Tanks

### ISSUE THREAD

**Issue by CassWindred** [ExtraCells/ExtraCells2#394]
Certus Quartz Glass is in the oreDictionary as BlockGlass, and the Buildcraft Tank used "BlockGlass" in the same shape as the Certus Quartz Tank, thus when creating a Certus Quartz Tank the output is instead a Buildcraft Tank thus making it impossible to progress into Fluid Storage without cheating or using minetweaker scripts.

**Comment by spannerman79** [comment]
http://minecraft.curseforge.com/projects/stimmedcow-nomorerecipeconflict/files/2267374

**Comment by Dream-Master** [comment]
or Minetweaker.

http://minetweaker3.powerofbytes.com/
