### ISSUE TITLE
Certus Quartz Tank duping glitch

### ISSUE THREAD

**Issue by ghost** [ExtraCells/ExtraCells2#395]
Place a tank.
fill inventory so there is no room.
have your bucket(or equivilent) filled with liquid in your hotbar.
Keep filling tank because bucket will not empty.

**Comment by Mattabase** [comment]
https://www.dropbox.com/s/mel4x3y52lj3woh/2016-05-14_00-32-44.webm?dl=0

**Comment by ghost** [comment]
Thank you. and yes... exactly that.

**Comment by SapientMC** [comment]
All versions after ExtraCells-1.7.10-2.3.10b190 have another variant of may be that bug.
Just put some fluid in Certus Quartz Tank and try to fill Empty Cell (IC2). It fills, but value of fluid in tank does not decreases.

**Comment by Nedelosk** [comment]
Fixed in 1.10.
