### ISSUE TITLE
Server crushing when put anyting in crafting table

### ISSUE THREAD

**Issue by itskun** [ExtraCells/ExtraCells2#396]
When trying to put anything in crafting table have a server-crush with exception: 
`java.lang.NoClassDefFoundError: Could not initialize class extracells.util.UniversalTerminal$`
Full crash report: http://pastebin.com/qeEAD8eD

Server doesn't crush without ExtraCells2...

**Comment by jackiedorland** [comment]
Crush? No, offense, but it's 'crash'

**Comment by spannerman79** [comment]
`extracells{2.3.10} [Extra Cells 2] (ExtraCells-1.7.10-2.3.10b190.jar)`
Update
