### ISSUE TITLE
Ore Dictionary Export Bus stops working when it encounters a craftable item

### ISSUE THREAD

**Issue by aradian** [ExtraCells/ExtraCells2#398]
If the ME network has a craftable item that matches the configured oredict string, then the export bus will only extract items it encounters before the craftable item. When the Pattern responsible for the craftable item is removed from the network, the export bus resumes working normally.

**Comment by DietmarKracht** [comment]
issue still there. i got it on the GTNH pack with tiny dusts

**Comment by spannerman79** [comment]
> i got it on the GTNH pack

report to the pack author - not here
