### ISSUE TITLE
Server crash on ticking entity

### ISSUE THREAD

**Issue by themechman** [ExtraCells/ExtraCells2#399]
[crash-2016-05-26_00.34.19-server.txt](https://github.com/ExtraCells/ExtraCells2/files/283478/crash-2016-05-26_00.34.19-server.txt)
Got this removing a TE Hardened Fluiduct being filled by your Fluid Interface block. It was being filled with Galacticraft's Fuel.

**Comment by Nedelosk** [comment]
Fixed in 1.10.

**Comment by Ahlix3** [comment]
https://paste.dimdev.org/raw/zelibuquha

Got this error when trying to transfer fluid from fluid cows/stalls into extended fluid cells
