### ISSUE TITLE
Ore Dictionary export bus

### ISSUE THREAD

**Issue by fdgjgf** [ExtraCells/ExtraCells2#402]
The naming window for the ore dictionary export bus is too small, I encountered this problem when attempting to export potions it could not fit the name "minecraft:potion"  with the n at the end not fitting into the space provided

**Comment by sammko** [comment]
`minecraft:potion` is not an oredict name - it's just the item name. But the point still stands.
Speaking of item names, an export bus which could filter based on those would be quite useful.
