### ISSUE TITLE
applied energistics 2 problem or extracells problem idk which

### ISSUE THREAD

**Issue by bird191** [ExtraCells/ExtraCells2#403]
The gas storage bus you cant add a capacity card to filter which gas goes in so i dont know wether they have to add gas storage bus to the list of things that use capacity cards or if you have to add capacity card as an upgrade for the storage bus.

**Comment by thiakil** [comment]
How would you use such a storage bus?

**Comment by bird191** [comment]
I am trying to have some way to filter what gas goes where but accross alot of mods their is no gas filters so if my tank runs out of gas then it fills with the wrong liquid because there isn't a filter to say just hydrogen can go in but Idk if you have no slots unless you add capacity or wether extracells never added the ability to filter
