### ISSUE TITLE
Crash when Linking Universal Wireless Terminal

### ISSUE THREAD

**Issue by tanto259** [ExtraCells/ExtraCells2#404]
Running ExtraCells-1.7.10-2.3.13b196 with appliedenergistics2-rv3-beta-6 on Forge version 10.13.4.1614.

Full log: [https://paste.ee/p/fVEP1](https://paste.ee/p/fVEP1)
Crash report: [https://paste.ee/p/EvGvf](https://paste.ee/p/EvGvf)

Crash originally happen when opening the terminal. So I decided to replace the terminal and summon a new one in using NEI then it crashes again when trying to link it from the security terminal.

**Comment by SirKastros** [comment]
I use ExtraCells-1.7.10-2.3.10b1090 with appliedenistics2-rv3-beta-6 on forge 10.13.4.1614
I have the ap2 wireless terminal already link then upgraded to ExtraCells-1.7.10-2.3.13b196 and tried to use the wireless terminal and the game crash in SP and boot me from MP. I have tested b194 , b195 and I get the same issue. I have also tested the same EC2 builds with AP2rv2-stable-10 and get the same issue.

The crash is a Ticking Memory Connection the same as tanto259 here

**Comment by tanto259** [comment]
Something strange just happen, after seeing the code I decided to try the Wireless Crafting Terminal mod (Link: [http://minecraft.curseforge.com/projects/wireless-crafting-terminal](http://minecraft.curseforge.com/projects/wireless-crafting-terminal)), then I make a new universal terminal using the wireless crafting terminal as base, see: [http://p455w0rd.net/mc/WCT/EC2wWCT2.png](http://p455w0rd.net/mc/WCT/EC2wWCT2.png). After making it, the terminal works nicely.

EDIT: Actually all wireless terminal are working now, somehow. I'm starting to think that the crash happens since somehow the WCT mod are required since EC 2.3.11 changes.
