### ISSUE TITLE
Universal Wireless terminal power drain

### ISSUE THREAD

**Issue by adamcirillo** [ExtraCells/ExtraCells2#405]
I'm using extra cells 2 with the wireless crafting terminal and all the power gets instantly drained from my draconic flux capicater 250mil rf

using extra cells 2 2.3.14b197
wireless crafting terminal 1.7.10-rv3-1.8.7.11b
ae2 rv3 beta 6

**Comment by amesgen** [comment]
Can confirm this, used to work in 2.3.11 (also with wct)

**Comment by Rasmun** [comment]
I am having the same problem with the Wireless Universal Terminal in ExtraCells-1.7.10-2.3.14b197.jar and the Wyvern Flux Capacitor.  The WUT drains 80mill RF in a few seconds (instantly if full).  Wasn't a problem in ExtraCells-1.7.10-2.3.9b188.jar, which appears to be what FTB Infinity Evolved was using before I just updated it.

**Comment by BuggaNoia** [comment]
Supposly still a general problem: 

Minecraft 1.10.2, All The Mods Expert
ae2-rv4-alpha-11
(Vanilla) Wireless Terminal
Actual Addition Battery (all 5 Tiers), Charge-Items-in-Inventory-Mode
