### ISSUE TITLE
Missing changelog

### ISSUE THREAD

**Issue by TheTerrorByte** [ExtraCells/ExtraCells2#410]
I'm trying to find the changelog, but Curse doesnt have one, the MC forum thread said "(For EC2 changelog, look on the github or the build server.)". I cannot find a build server, and this has no changelog, so this is a bug.

**Comment by spannerman79** [comment]
http://shadowcity.net:8080/job/ecrv2/

Learn to look at README.md within github repos

**Comment by TheTerrorByte** [comment]
i though that was just a picture, not a link
