### ISSUE TITLE
Crash: ME Upgrade in Upgrade Container

### ISSUE THREAD

**Issue by amesgen** [ExtraCells/ExtraCells2#413]
My game crashes if I place a ME Upgrade (Tier II) in a Tier II Upgrade Container in a robot.
https://gist.github.com/condensedapple/c0c015196579a7194eb517aa194fb24d

Using latest OC and EC release.
Also see https://github.com/MightyPirates/OpenComputers/issues/1981

EDIT: After a restart, the ME Upgrade is actually in the robot, but the Robot GUI cant be opened anymore, and the robot is rapidly changing its name in its WAIlA display (its name in my inventory remains the same). Renaming in an anvil does not help, so the robot is now completely unusable.

**Comment by Nedelosk** [comment]
Fixed in 1.10.

**Comment by amesgen** [comment]
thanks a lot!
