### ISSUE TITLE
ME Fluid Import Buss Not Working

### ISSUE THREAD

**Issue by Krahazik-zz** [ExtraCells/ExtraCells2#415]
As the sole device on a ME Smart Cable and ME Glass Cable, attached to a smeltery drain, the import buss constantly claims to not have enough channels and will not active. It has more than enough channels. Tried attaching it to a portable tank as well and got the same thing.

**Comment by Krahazik-zz** [comment]
Amendment, apparently the units are working, but their indicators o not function. The small square on the side stays black as if its offline, and it said not enough channels, even though it is actually online and working.

**Comment by spannerman79** [comment]
What version of EC/AE2/Forge etc.

Bit hard to replicate when the dev has no idea of your current setup.
