### ISSUE TITLE
Client crash when putting blank fluid pattern in dark spots of fluid interface

### ISSUE THREAD

**Issue by COLDF1R3** [ExtraCells/ExtraCells2#416]
When using the fluid interface and clicking with a blank pattern in the spot the fluid goes the client crashes.

**Comment by spannerman79** [comment]
Logs or it never happened.

**Comment by COLDF1R3** [comment]
where would the crash logs be? i just looked and cant find them

**Comment by COLDF1R3** [comment]
here is the paste for the crash log
http://pastebin.com/NCYvtR0M

**Comment by Nedelosk** [comment]
Fixed in 1.10.
