### ISSUE TITLE
java.lang.ClassCastException

### ISSUE THREAD

**Issue by leytilera** [ExtraCells/ExtraCells2#417]
http://pastebin.com/5pvGKHSQ

**Comment by spannerman79** [comment]
Update AE2

**Comment by leytilera** [comment]
when i update ae2 it not works

**Comment by leytilera** [comment]
that means the modpack only supports ae2 rv2

**Comment by spannerman79** [comment]
Then tell the modpack author - not the mod dev.

**Comment by leytilera** [comment]
when i create a new world it works but not in this world

**Comment by spannerman79** [comment]
You were told what to do - this isn't an issue with Extra Cells.  Extra Cells was updated to use Mekanisms new API as well as use the most recent beta AE2 build.  This is a modpack issue - **not** an issue with the mod.

**Comment by DrummerMC** [comment]
disable mekanism gas in ec config
