### ISSUE TITLE
Another fluid dupe bug

### ISSUE THREAD

**Issue by wormzjl** [ExtraCells/ExtraCells2#418]
Video: https://youtu.be/zy2nTq3jta0
Dunno if related to https://github.com/ExtraCells/ExtraCells2/issues/414

**Comment by Scarsz** [comment]
Reproducible on FTB Infinity Evolved 1.7 v2.6.0

**Comment by spannerman79** [comment]
> Reproducible on FTB Infinity Evolved 1.7 v2.6.0

Unless that pack is running the most recent version of ExtraCells don't post here.  A mod author has no control over a public modpack @Scarsz

**Comment by Scarsz** [comment]
> Unless that pack is running the most recent version of ExtraCells don't post here. A mod author has no control over a public modpack @Scarsz

Yes, it is using the latest version, 2.3.14. Was just giving a method to quickly test it against the public version. @spannerman79
