### ISSUE TITLE
Fluid Formation Pane comparing in world block to Blocks.air instead of Block.isAir

### ISSUE THREAD

**Issue by covers1624** [ExtraCells/ExtraCells2#423]
Due to RailCraft's residual heat fake air blocks the FluidFormationPane fails to place any fluid due to a check to Blocks.air instead of Block.isAir.

https://github.com/ExtraCells/ExtraCells2/blob/rv2/src/main/scala/extracells/part/PartFluidPlaneFormation.java#L94

**Comment by Aivech** [comment]
Workaround: Disable the heat block in the RailCraft config,

**Comment by covers1624** [comment]
That is what i have done yes, but there are potentially other fake air blocks that could cause this, the Factorization lamp comes to mind.
