### ISSUE TITLE
[SUGGESTION] ProjectE Integration

### ISSUE THREAD

**Issue by lrwerewolf** [ExtraCells/ExtraCells2#424]
I would like to see integration with a mod called ProjectE.

ProjectE is a mod that adds a mechanic where certain items can be broken down into a 'currency' called EMC.  Items can then be formed from this EMC.  As an example, in the modpack I am learning ProjectE, a Block of Diamond is equivalent to 73,728 EMC and a Cobblestone is equivalent to 1 EMC.  A player could convert a Block of Diamond to 73,728 Cobblestone, or conversely, 73,728 Cobblestone to a Block of Diamond.  These conversions are done either directly (using blocks called Energy Condensers) or more powerfully, the Transmutation Table/Tablet, which interface with a player's personal EMC network.

I would suggest the following additions to enable that:

STORAGE:
    1K - 4M EMC Storage Components -- Tracks the amount of EMC held in the storage.  Ranging from few tens of thousands EMC for 1K to one billion for 4M.  Suggest that the recipe be similar to fluid/gas, but using an item from ProjectE called "Red Matter" in place of the blue/yellow dye

TERMINALS/MONITORS:
    ME EMC Crafting Terminal -- Has a slot to hold a Transmutation Tablet, from which it pulls information about the player's EMC network and known recipes.  Also has a slot for items to be converted to EMC.  Instead of displaying the inventory in the AE2 network, displays items the Tablet can create.  Items inserted into this terminal are checked for an EMC equivalence -- if one exists, the item is destroyed and its EMC added to the network if space exists for the EMC, otherwise the insertion is refused.  Recipe should involve Red Matter from ProjectE in some way.
    ME EMC Monitor -- Displays the total amount of EMC held in the network.  Would need large integers as 1B EMC is not a difficult task.  A display such as "100K EMC" or "7.4T EMC" would be useful.  Recipe should use Dark Matter from ProjectE in some way (Dark Matter being a less involved material to obtain than Red Matter, given this is an information block, not a functional block)

UTILITY BLOCKS:
    ME EMC Transmutation Unit -- If a Transmutation Tablet is installed in an ME EMC Crafting Terminal (above), enables the network to convert EMC to items needed for crafting Patterns, if the Transmutation Tablet installed knows how to make that item.  Can accept Acceleration Cards to speed the process -- perhaps default is 1 stack / 1 sec, with each card doubling that.

```
ME EMC Network Link -- When added to an AE2 network by a player, links that network to that player's EMC network.  Operations involving EMC can pull either from storage or the player's network, depending on priorities set for the ME EMC Network Link and the ME Drive holding an ME EMC Storage Cell.
```

**Comment by spannerman79** [comment]
https://minecraft.curseforge.com/projects/equivalent-energistics
