### ISSUE TITLE
Extra Cells + EnderStorage dupe

### ISSUE THREAD

**Issue by Hiagg** [ExtraCells/ExtraCells2#426]
Placing an ender tank with anything in it into your ME Fluid Terminal makes it so you can pull infinite amounts of any fluid in your system. I tried things like breaking my drive box, breaking the terminal, cutting the power to my system, and a few other things to fix it. But nothing I tried works. I can't go NBT diving because it's on a server too. On the bright side though, I have infinite o anything and everything fluid.

pack is FTB Inventions

**Comment by Kalbintion** [comment]
Cannot replicate using Extra Cells 2 1.7.10-2.3.10b and EnderStorage 1.7.10-1.4.7.37 while under the SkyFactory 2.5.4 modpack
