### ISSUE TITLE
[Suggestion] "ME Upgrade" API Documentation

### ISSUE THREAD

**Issue by Be-Cool-Man** [ExtraCells/ExtraCells2#430]
Hello folks,

i can't find any information how to use the API from the ME Upgrades for the Robots from Open Computers. It would be verry helpful if you have an API Documentation like the one from Open Computers (i.e.: http://ocdoc.cil.li/api:robot)

Cheers
Be-Cool-Man

**Comment by alandoyle95** [comment]
this would be nice as its 2018 now................
