### ISSUE TITLE
Extra Cells Update?

### ISSUE THREAD

**Issue by Tyrantin** [ExtraCells/ExtraCells2#438]
How long before we see a update to 1.10.2? I am putting together a Mod Pack and would realy like to use this mod in the Pack...

**Comment by Nedelosk** [comment]
We update if ae 2 rv4 is out of the alpha state.

**Comment by Tyrantin** [comment]
Is their a Beta version I could test?
I am trying to put together a Alpha mod pack for private use

**Comment by spannerman79** [comment]
> How long before we see a update to 1.10.2?

As per clearly show on the AE info website;

_Alpha builds are not compatible with any AE2 addons, do not request add-on authors or other mod developers to support these builds._

So what @Nedelosk stated is correct @Tyrantin 

> Is their a Beta version I could test?

That has already been answered.

**Comment by mgdgfbhevdyeh** [comment]
@Nedelosk Hope you do not lie to us

**Comment by gabor7d2** [comment]
@spannerman79 What about **AE2Stuff** then?

**Comment by spannerman79** [comment]
You are now splitting hairs and being pedantic @gabor6505  .  I don't need to answer that as the answer is self evident.

@Nedelosk please lock this to contributors only - getting off topic and beyond the joke.

**Comment by Nedelosk** [comment]
Duplicate of #428
