### ISSUE TITLE
me ore dictionary export bus issue

### ISSUE THREAD

**Issue by CraftYourWay** [ExtraCells/ExtraCells2#439]
hello so when i want to put all ores in a machine i type ore*. i get that but now i want that all dust goes into a furnace, so as expected i typ dust* but this doesnt work what am i doing wrong, and is it even possible?

**Comment by Nedelosk** [comment]
dust* works.
![2017-10-09_23 58 40](https://user-images.githubusercontent.com/10259214/31360267-d18ffbaa-ad4d-11e7-901c-b8ad0158147d.png)
![2017-10-09_23 58 43](https://user-images.githubusercontent.com/10259214/31360269-d3f7a1d6-ad4d-11e7-831a-cd2c39d96ca9.png)
