### ISSUE TITLE
Fluid Import/Storage and Export/Storage Bus combinations not working on their own

### ISSUE THREAD

**Issue by Banjobeni** [ExtraCells/ExtraCells2#44]
It seems I can't get a system to work that only consists of, say, a Fluid Import Bus and a Fluid Export Bus. Only when I attach an ME Drive and put a Fluid Storage Cell into it, liquid will be transferred. This feels odd.

**Comment by ruifung** [comment]
Is this still happening?

**Comment by linkjankens** [comment]
I'm trying to get water to pump into the ME network (buildcraft to AE2) so I can move water around however I need, and I can't seem to be able to do any of the things you guys mentioned above. I thought it was possible to move fluids through the ME network?
