### ISSUE TITLE
extracells2 seems to crash when loading fastcraft

### ISSUE THREAD

**Issue by silverhikari** [ExtraCells/ExtraCells2#450]
link to crash report

https://drive.google.com/file/d/0B_TwP2ekIMhdMjkyZEJVbC1YMGs/view?usp=sharing

**Comment by spannerman79** [comment]
This is not an EC2 issue.

This is an Optifine and FastCraft issue.

https://forum.industrial-craft.net/thread/10820-wip-1-7-10-fastcraft-1-23-note-all-posts-of-new-members-need-to-be-approved-firs/?postID=207247#post207247

Non EC2 issue.
