### ISSUE TITLE
Dupe Glitch: IC2 cell (not universal cell) + ExtraCells certus tank

### ISSUE THREAD

**Issue by Krysinski** [ExtraCells/ExtraCells2#452]
Dupe:
https://www.youtube.com/watch?v=E_JlEXrB8oE
And when i put fluid into tank by right click, i dont get back empty cell!
ExtraCells: 1.7.10-2.3.14b197
I think there is no these bugs in previos build, i check this later.

**Comment by spannerman79** [comment]
Try http://shadowcity.net:8080/job/ecrv2/lastStableBuild/artifact/build/libs/ExtraCells-1.7.10-2.3.14b199.jar

**Comment by Krysinski** [comment]
@spannerman79 Thank you, all work fine now.
Please, update curse for last build *199.
