### ISSUE TITLE
Build issue with the rv4-1.10 branch

### ISSUE THREAD

**Issue by brisingraerowing** [ExtraCells/ExtraCells2#453]
Out of complete curiosity, I tried to build the rv4-1.10 branch myself (just to see if it works), and the build could not find Mekanism. A quick check showed you have an extra 0 (zero) in the build.properties file for the Mekanism download URL (e.g. 085, where only 85 is required). Changing that made the build work.

Just thought I'd let you know so you don't pull your hair out over failed downloads.

**Comment by Nedelosk** [comment]
I changed the mekanism version in one of the last commits, it should work now.
