### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by silasporth** [ExtraCells/ExtraCells2#456]
If I start the build.bat file, then it's downloading much, but it crash and sometimes there is a build folder but there is no lib folder. 

Lavariator
> Sorry for my bad English.

**Comment by Miner94** [comment]
i have no idea how to do that so ill just wait for the official download

**Comment by p455w0rd** [comment]
I am currently working on the conversion from Scala to java. I'm VERY close. After this, building will work out of the box without the need for the Scala plugin. I'm also refactoring things like the AE2 ivy dep as AE2 is back on the Forge maven (RV4 Stable 1 is 1.10.2). I have also re-implemented and changed up the WCT API just for EC2. Lots of changes and refactors coming soon. Please bare with us and have patience :)
