### ISSUE TITLE
AE2 RV5

### ISSUE THREAD

**Issue by SinusoidalC** [ExtraCells/ExtraCells2#460]
Recently AE2 RV5 is out of alpha test. I'm just make sure that would you finish EC 1.10.2 version first or just jump to 1.12.2 ?

**Comment by DeadSix27** [comment]
@SinusoidalC p455w0rd is doing the 1.12 port (together with Nedelosk? Probably), see: https://github.com/ExtraCells/ExtraCells2/issues/456#issuecomment-336456827

But he is not finished yet.

**Comment by SinusoidalC** [comment]
@DeadSix27 k, nks
