### ISSUE TITLE
FYI: crash in 1.12.2/2529 AE appliedenergistics2-rv5-stable-1

### ISSUE THREAD

**Issue by JasonKillsUs** [ExtraCells/ExtraCells2#466]
https://pastebin.com/fEABBXkP
thanks for looking in to it :-)

**Comment by DrDoom347** [comment]
I'm having the same crash, java.lang.AbstractMethodError: extracells.item.ItemWirelessTerminalFluid$.isInCreativeTab(Lnet/minecraft/creativetab/CreativeTabs;)Z

https://pastebin.com/9P3CfD7Y

**Comment by Krosta8** [comment]
Same problem for me 😄

**Comment by MainFreak** [comment]
Any idea when this will be pulled? lol

**Comment by DrummerMC** [comment]
https://minecraft.curseforge.com/projects/extracells2/files/2497496
