### ISSUE TITLE
Fluid storage bus can void fluids after attached tank being broken

### ISSUE THREAD

**Issue by yueh** [ExtraCells/ExtraCells2#474]
If the tank or something like a condenser attached to a fluid interface is broken, they will still consider it a valid place to store fluids.

Also a new tank will not be used. Instead it will still be voided. Only replacing the storage bus will cause it to use the new tank.

Version: rv5-1.12
Commit: 331f7757d23d075312526165e4e16621aabb4c35

**Comment by DrummerMC** [comment]
fixed in https://github.com/ExtraCells/ExtraCells2/commit/cf09f72f2a37c98e9f4ddbac4c96ea26cb28168a
