### ISSUE TITLE
Shift clicking a bucket into an export or import bus will stall the client

### ISSUE THREAD

**Issue by yueh** [ExtraCells/ExtraCells2#475]
No crashlog, it will just put the client into an infinite loop or similar.

This seems to be only happening with the export and import bus. It works fine with a fluid storage bus.

Version: rv5-1.12
Commit: 331f7757d23d075312526165e4e16621aabb4c35

---
Edit: Also happens with the auto filler. Level emitter works fine.

**Comment by DeadSix27** [comment]
That is probably related to what I reported:

> Client crashes if you shift-click anything other than storage cells into the Blast Resistant Drive (and some other machines and parts) (I can't offer you a stacktrace because it does not generate one for me.. it just locks the game and no log messages appear)
