### ISSUE TITLE
[1.12.2] Fluid Interface desync...

### ISSUE THREAD

**Issue by Xiaminou** [ExtraCells/ExtraCells2#489]
When using a fluid interface to provide water it's causing a desync with the server and some weird behavior: https://youtu.be/27YlPo32SH8

It causes desync, emits light for some reason and lowers FPS.
Note that it only happens on dedicated server, I tried to reproduce it in SSP but failed.

Minecraft: 1.12.2
Forge: 2538
Mods: [list.txt](https://github.com/ExtraCells/ExtraCells2/files/1463820/list.txt)

**Comment by DrummerMC** [comment]
can't reproduce

**Comment by Xiaminou** [comment]
I'm still getting some weird lag when I use Fluid Interfaces (the bus version only) and they do emit light for some reason when they are powered (again the bus version only). Maybe it's related.

https://youtu.be/QGqGvx8e3t0

**Comment by ruifung** [comment]
Deprecated functionality.
