### ISSUE TITLE
Fluid Terminal

### ISSUE THREAD

**Issue by Xiaminou** [ExtraCells/ExtraCells2#490]
Sorry if this is just not implemented yet...
The Fluid and Gas Terminals is missing some UI elements:
- [x] - "Grey background" like you get when you open your inventory
- [ ] - "Sort by" like other AE Terminals
- [ ] - "View" I'm not sure if that applies here
- [ ] - "Sort Order"
- [ ] - "Search Box Mode"
- [ ] - "Terminal Style"
- [ ] - "Unit" Kilo Bucket, Bucket, Milli Bucket

![2017-11-11_21 01 21](https://user-images.githubusercontent.com/8670392/32693141-c55f8bf6-c725-11e7-8e12-ea7b6ff5f479.png)

**Comment by Xiaminou** [comment]
Any news on the rest of that list? specifically "Search Box Mode", I don't like "Auto" because I always use "use" to exit UIs.

**Comment by Xiaminou** [comment]
Added:
- [ ] - "Unit" Kilo Bucket, Bucket, Milli Bucket

Because right now you can't tell if you have 1000 Bucket or 1999 Bucket worth of liquid.

**Comment by ruifung** [comment]
Deprecated functionality.
