### ISSUE TITLE
[1.12.2] Gas Terminal Doesn't Display Gases

### ISSUE THREAD

**Issue by TheLimePixel** [ExtraCells/ExtraCells2#493]
The Gas Terminal doesn't display the gases it has, but it does (not even always) allow you to put gases into it.
![image](https://user-images.githubusercontent.com/25333164/32740199-74aa4948-c8a2-11e7-9577-df500ba01bc9.png)
![image](https://user-images.githubusercontent.com/25333164/32740219-83b76ef2-c8a2-11e7-8fff-f178cc98dc9a.png)

**Comment by DrummerMC** [comment]
Version?

**Comment by TheLimePixel** [comment]
The one that was just released, also, I just put in a creative Gas Tank in it, it showed up, but not correctly:
![image](https://user-images.githubusercontent.com/25333164/32740684-f60343d6-c8a3-11e7-9bd6-d37fd499c0d5.png)
![image](https://user-images.githubusercontent.com/25333164/32740687-f90aa7a4-c8a3-11e7-8824-e40558118b14.png)

**Comment by DrummerMC** [comment]
is a me drive fixture in your network?

**Comment by TheLimePixel** [comment]
Nope, besides the first time when I couldn't put gases in it. I even tried it with multiple gases and it seems that it doesn't display until it reaches a certain amount, but it doesn't even display it corrently then.

**Comment by DrummerMC** [comment]
ae version?

**Comment by DrummerMC** [comment]
Try the new version

https://ci.appveyor.com/project/DrummerMC/extracells2/branch/rv5-1.12/artifacts

**Comment by TheLimePixel** [comment]
Works perfectly!
