### ISSUE TITLE
[1.12.2] After Server Restart Fluid Auto-filler not working, must break and re-place

### ISSUE THREAD

**Issue by BrewingCoder** [ExtraCells/ExtraCells2#498]
ExtraCells 1.12.2-2.5.3a25
AE2 rv5-stable-2
Forge:  1.12.2-14.23.0.2351

Place Fluid Auto Filler, recipes that require bucket work great. Bucket w/fluids show as craftable in UI

reset SMP server, re-start client, no buckets showing in UI, show as 'missing' when attempting to craft recipes that require them.

Break and then replace Auto Filler in same spot and viola! all works again until the next server restart or auto-restart.

**Comment by dooms247** [comment]
I'm still having this issue with EC 2.6.5
