### ISSUE TITLE
Crash on startup after updating to ExtraCells2 version 2.5.5

### ISSUE THREAD

**Issue by ghost** [ExtraCells/ExtraCells2#502]
After I updated to [ExtraCells2 version 2.5.5](https://minecraft.curseforge.com/projects/extracells2/files/2502995), I crash on startup.

**Crash log**: https://pastebin.com/raw/YK4iQdN0

There must be something wrong with the OpenComputers integration added in this version.

****

**Minecraft version**: 1.12.2
**Forge version**: 14.23.0.2552
**ExtraCells2 version**: 2.5.5
**OpenComputers version**: 1.7.0.20

**Comment by DrummerMC** [comment]
fixed in https://github.com/ExtraCells/ExtraCells2/commit/54789e689d991973cfa2277b3eb206eb0806a460
the new file will be uploaded to CurseForge. You can use the new version on CF or update to the latest OpenComputers version from the OC build server (not CurseForge)

**Comment by ghost** [comment]
Thanks!

**Comment by ghost** [comment]
@DrummerMC [The changelog](https://minecraft.curseforge.com/projects/extracells2/files/2503027) says “fixed crash on startup if OpenComputers is not installed,” but OpenComputers _was_ installed for me.

**Comment by DrummerMC** [comment]
This is the changelog for curseforge.
Your bug was fixed in 2.5.6.
The bux in the changelog was fixed in 2.5.7

**Comment by ghost** [comment]
Oh, my bad.
