### ISSUE TITLE
Server crash when autocrafting via fluid assembler and export bus

### ISSUE THREAD

**Issue by ouroborus** [ExtraCells/ExtraCells2#504]
Tried setting up autocrafting via export bus to make salt (Pam's Harvestcraft). I got the export bus set up and tried looking in the crafting storage. Server crashed and now crashes every time that chunk loads. (It's chunk loaded so I'll have to get in there with McEdit.)

I'll try and get a screenshot of the setup once I fix the world.

Applied Energistics 2 rv5-stable-2
Extra Cells 2 1.12.2-2.6.3a25

[crash-2017-12-02_01.15.01-server.txt](https://github.com/ExtraCells/ExtraCells2/files/1523689/crash-2017-12-02_01.15.01-server.txt)

**Comment by DrummerMC** [comment]
Try the latest version
https://ci.appveyor.com/project/DrummerMC/extracells2/branch/rv5-1.12/artifacts

**Comment by ouroborus** [comment]
Updating fixed things.
