### ISSUE TITLE
ME Ore Dicitionary Export Bus destroys things it exports

### ISSUE THREAD

**Issue by trpipher** [ExtraCells/ExtraCells2#509]
I setup the export bus to export "ore*" for all ore. it removes the ore from the system but does not actually export it to the storage crate. Also, doesn't work with chests or direct export to a pulverizer.

**Comment by mainframecn** [comment]
Can confirm running [1.12.2-forge2555]. 
Active mods: JEI,WAWLA,AE2 and ExtraCells2

**Comment by TNTUP** [comment]
Same issue on the pack Revelation 1.0.0 @ ExtraCells-1.12.2-2.5.9a45 It just voided all of my ores :(

**Comment by dyerseve** [comment]
This is a me too! Revelation pack. I found this out too late. Set it up late at night, "huh why isn't it exporting to pulverizer? I'll figure it out tomorrow" Went to bed, next morning I configure it to a chest to see if i did something wrong, still nothing, oh look no ores at all in my system... So sad.

IF there is any way to get it working properly I'd love to use it. Was it just an issue with the pulverizer? Is it the mod version that is the problem, some conflict?

**Comment by BrockWS** [comment]
Should be fixed in the next version

**Comment by TNTUP** [comment]
Yeah!!! Now just to see when FTB Revelation updates their pack, unless they discontinued it already im not sure :/ Can update manually, but that would require manual download/setup for others (and making a tutorial for noob friendly)
