### ISSUE TITLE
[1.10.2 ] Crash when opening universal wireless terminal with crafting module

### ISSUE THREAD

**Issue by eyeonus** [ExtraCells/ExtraCells2#517]
Versions:
appliedenergistics2-rv4-stable-1.jar
ExtraCells-1.10.2-2.4.4a15.jar
WirelessCraftingTerminal-1.10.2-2.1.39.jar

Crash Report:
https://pastebin.com/cHm7uSby

The wireless crafting terminal itself does not crash, but when crafting it into the universal wireless terminal, it does.

**Comment by aionys** [comment]
Apparently the relevant line should be 
`WCTApi.instance().interact().openWirelessCraftingTerminalGui(player);`

The () are missing in the relevant code.

**Comment by p455w0rd** [comment]
do I really need to add the interact() method to WCTApi.class @DrummerMC ? It would appear that in this situation, it would just throw an AbstractMethodError.. (interact() is a method in WCTAPIImplementation.class which WCTApi#getInstance casts to)

**Comment by eyeonus** [comment]
According to the wiki on WCT, the method for calling up the GUI is
`WCTApi.instance().interact().openWirelessCraftingTerminalGui(EntityPlayer player);`
https://github.com/p455w0rd/WirelessCraftingTerminal#wireless-crafting-terminal-api

In the code here (, which is in Scala,) it's called by the line
`WCTApi.instance.interact.openWirelessCraftingTerminalGui(player)`
https://github.com/ExtraCells/ExtraCells2/blob/rv4-1.10/src/main/scala/extracells/integration/WirelessCrafting/WirelessCrafting.scala

Which, as far as I can tell, is correct.

**Comment by eyeonus** [comment]
I have no idea why it's getting transformed into "p455w0rd.wct.api.WCTApi.interact()Lp455w0rd/wct/api/IWCTInteractionHelper;",

**Comment by p455w0rd** [comment]
exactly..i'm kinda lost

**Comment by eyeonus** [comment]
I think it's Scala's fault, but I don't know anything about Scala, so I don't know how or why it would be messing this up.

**Comment by p455w0rd** [comment]
eh..i think it's on scala for not throwing the appropriate error at compile time, but on my end for not adding the abstract method in WCTApi.class..really..this is on me..i will close this and continue any needed discussion on the WCT tracker..thanks for reporting :)
