### ISSUE TITLE
Storage Cell capacity mismatch

### ISSUE THREAD

**Issue by ouroborus** [ExtraCells/ExtraCells2#519]
Extra Cells 2 2.5.9

The storage cells in Extracells do not seem to use the same capacity formulas as those native to AE2 do. As a result, the ME 16384k Storage Cell, for example, doesn't store nearly as much as I'd expect an equivalently sized cell in AE2 would store.

In the screenshots, the cells shown contain the same exact items and amounts. (I used a ME IO Port on an isolated system to move the items between cells. I transferred them back and forth several times and the numbers didn't change.)

In this example, I would expect the ME 16384k Storage Cell to read near "21359 of 16777216" (~0.13% capacity). Instead we have "21359 of 65535" (~32.6% capacity) and "3807599 of 16777216" (~22.7% capacity). In other words, I'd expect the 16384k cell to have 256 times the capacity of the 64k cell but, in reality, it appears to only have ~1.5 times the capacity.

![2018-01-15_00 16 23](https://user-images.githubusercontent.com/392047/34933729-d5055d4e-f98c-11e7-9b52-67aa0c8a53e5.png)
![2018-01-15_00 16 52](https://user-images.githubusercontent.com/392047/34933730-d519991c-f98c-11e7-85be-7cce8b783954.png)

**Comment by Rubijox** [comment]
isn't that because of the way it calculates data usage base on the amount of different items?

 each different type added to a drive uses a certain percentage of the drive has a base ''byte cost'', additional items will use the normal amount of bytes.

**Comment by ouroborus** [comment]
@Rubijox Because the inventory is exactly the same in both of the cells used in my example, the base cost is also the same. As well, the listed "bytes used" should also be the same (or at least close) in both instances. Instead, the inventory in the larger cell uses ~178x the storage compared to the exact same inventory in the smaller cell.

**Comment by Rubijox** [comment]
> Because the inventory is exactly the same in both of the cells used in my example

you are comparing 2 different cells, 1% of 65536 bites is NOT the same as 1% of 16777216 bites

**Comment by Rubijox** [comment]
read this http://ae-mod.info/ME-Storage-Math/

**Comment by ouroborus** [comment]
Alright, I took a closer look at the math. Turns out the per-item-type cost is huge when compared against the per-stack cost making the whole thing hard to intuit. Having 63 item types eats about half the available bytes on a ME 16384k Storage Cell even when you have just 1 of each of those item types.
