### ISSUE TITLE
Gas level emitter GUI displays and behave as fluid level emitter

### ISSUE THREAD

**Issue by Erakol** [ExtraCells/ExtraCells2#520]
Hey there,

I play the "all the mods 3" modpack and I have a strange problem with the gas level emitter. After crafting the emitter it displays as Gas level emitter, but if I put it on a ME cable an open the emitter the GUI displays a fluid level emitter and it bahaves like one. I hope you have a solution for that problem.

**Comment by cinnamennen** [comment]
I can confirm this, on `2.5.11`

**Comment by localzuk** [comment]
Can confirm this is still a problem in 2.5.13 - prevents the Gas Level Emitter working entirely.

**Comment by seiverdamross** [comment]
this is still an issue in 2.6.2

**Comment by ebmusicman84** [comment]
Experiencing this issue in Enigmatica 2 Expert Mode as well (ExtraCells2 version 2.6.2a)

**Comment by ABelli99** [comment]
Still having this issue with the version 2.6.3

**Comment by mikenoethiger** [comment]
I'm a developer, is there any chance I can help out with this bug?

**Comment by zjeffer** [comment]
Is development of this mod dead? Last commit was in February :(

**Comment by Charismara** [comment]
Still having this issue in version 2.6.5

**Comment by albert-wong** [comment]
This is still an issue on skyfactory v4.1.0

**Comment by SsnShipz** [comment]
It's still an issue in MC Eternal as well, is this going to get fixed for 1.12 or is there no developer who wants to check this any more?

**Comment by Puyodead1** [comment]
came here from the 1.12.2 pack, same problem 😠
