### ISSUE TITLE
ME Fluid Storage Bus Insane Bandwidth Usage

### ISSUE THREAD

**Issue by iiiNook** [ExtraCells/ExtraCells2#522]
When using an ME Fluid Storage Bus connected to black hole tanks, and a liquid is being inputted/outputted rapidly (i.e. essence for a mob farm), there is insane bandwidth usage and causing players to time out. Possibly caused by every time an update occurs all packets are sent or something?

How to replicate:
- Have a fluid rapidly going in and out of a black hole tank, with a decent buffer of the liquid already in there (about 1 kilobucket)
- Use the ME system, for example craft lots of things, withdraw/deposit items.
- Observe the network usage.

**Comment by twinkie422** [comment]
issue still exist https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/3797
