### ISSUE TITLE
1.12.2 Fluid Export Won't Save Redstone

### ISSUE THREAD

**Issue by SirJBiscuit** [ExtraCells/ExtraCells2#523]
Okay when I press the redstone button on the left It won't stay when I close the GUI,
Either one I pick it's keep going back to default, also theirs no tool tip when you hover over the icon
It's quite irritating..

Does this happen to anyone else?

**Comment by erebus42** [comment]
I see the same on fluid import.

**Comment by 5t0rmr1d3r** [comment]
Can confirm both issues...

**Comment by jp1224** [comment]
also having this problem playing FTB Revelations
