### ISSUE TITLE
[1.10.2] Crash on startup when WCT (and TE?) also installed

### ISSUE THREAD

**Issue by eyeonus** [ExtraCells/ExtraCells2#527]
Relevant mod versions:
ThermalExpansion-1.10.2-5.1.10.28-universal.jar
ExtraCells-1.10.2-2.4.4a15.jar
WirelessCraftingTerminal-1.10.2-2.1.41.jar

The game crashes during loading because of a method in TE's sawmill code, because the WCT isn't being called correctly?

From the error, it looks like anything that tries to get the WCT through the Extra Cells implementation of the API would cause it to crash, not merely the time TE does it during load.

Crash report:
https://pastebin.com/GUKSTWJE

**Comment by brisingraerowing** [comment]
The WCT API changed the return type of the erroring method from IWCTItem to IWirelessCraftingTerminalItem.

**Comment by p455w0rd** [comment]
yes and Drummer did fix this, he just never pushed the updates to curse..I'm working on figuring something out..bare with me
