### ISSUE TITLE
Interfaces and buses kill framerate {1.12.2}

### ISSUE THREAD

**Issue by Rubijox** [ExtraCells/ExtraCells2#533]
when a fluid interface/bus is on my screen my framerate goes from 300 to 10-15

>Interfaces only lag me when being used(ie fluid being actively pumped into them)
>lag is almost constant, i only get back to ~300fps for about 5 seconds before going back down 10-15 fps

ExtraCells 2 Ver 2.5.10

after a bit of testing, i'm fairy certain the lag comes from the buses trying to move small amounts of liquid super quickly instead of moving full buckets every now and then, causing a ton of updates

**Comment by Rixxaw** [comment]
I might be experiencing the same thing I just put storage bus on an Ender Tank  and boom my system is lagging down from 90 FPS to 10 and I have about ripped my base apart trying to figure it out and then I came here because i"m having another issue and noticed this open issue.

**Comment by unikmhz** [comment]
Same here.
MC 1.12.2.
Forge 2611.
AE2 rv5-stable-11.
ExtraCells 2.5.11a48.
Visual debugging with sampler (```/csampler renderupdates show --cross --ignorez```) shows that ME fluid storage buses are constantly forcing render updates, when attached to output (bottom) block of an Immersive Engineering fluid tank. Interestingly, attaching them to thermal expansion tanks is not a problem.

**Comment by Rixxaw** [comment]
So is it a problem with the Tank ?

**Comment by Rubijox** [comment]
no, the modpack i was on when i found the issue didnt even have immersive engineering, the mod interacting with itself even causes this issue

**Comment by unikmhz** [comment]
Additionally, render updates are forced whenever a fluid amount changes in any tank, that is connected to a storage bus. This is a problem when fluid amount changes gradually, and not in big (whole bucket) steps.

**Comment by Eld0r** [comment]
can confirm this for FTB Revelation 1.8.0 (ExtraCells2, Jan 18, 2018)
Even a fluid storage in IO Port can create high server load because of copying each mB one by one.
But this creates no client lags.

**Comment by unikmhz** [comment]
This was in single-player, so server and client share the local host.

**Comment by Rubijox** [comment]
no point in bumping this, this github is dead
