### ISSUE TITLE
Fluid Storage Bus not remembering the fluid it was programmed to

### ISSUE THREAD

**Issue by HawkridgeV** [ExtraCells/ExtraCells2#535]
I am GT New Horizons. 

I have several fluid storage busses working with allsorts of fluids from GT. Helium plasma etc. 
When I put a storage bus onto a gt super tank 1 and program it to only store plasma there... it will at some point loose this programming. (e.g after server restart)
I have tunneled the me channels. 
This makes the extra cells 2 part of the mod unplayable.

**Comment by mthp1999** [comment]
Similar problem happens where, the storage bus will disconnect from network on restart or unloading and then wont reconnect when loaded back need, and you have to break and replace in order for it to reconnect to network
