### ISSUE TITLE
OreDictionary Export deletes items

### ISSUE THREAD

**Issue by Fently** [ExtraCells/ExtraCells2#539]
**Issue:**
Ore dictionary export bus removes items from inventory, but items go nowhere. Doesn't matter what it is connected to. Even vanilla minecraft chests will not except items.

**Versions**:
Forge: 1.12.2-forge1.12.2-14.23.2.2613
AppliedEnergistics 2: rv5-stable-8
ExtraCells: 1.12.2-2.5.11a48

**Comment by LazyDope** [comment]
I'm having the same issue and I just lost all my ores ;(

**Comment by suprra** [comment]
Just lost tens of thousands of ores by using the oredictionary export bus. Please fix.

**Comment by mainframecn** [comment]
Was reported over 3 months ago, new version came out but no fix in that update. [#509](https://github.com/ExtraCells/ExtraCells2/issues/509)

**Comment by BrockWS** [comment]
Should be fixed in the next version
