### ISSUE TITLE
[1.12.2] Wrong values (2x)

### ISSUE THREAD

**Issue by TheSnowyChickens** [ExtraCells/ExtraCells2#543]
How the 2 pictures show, the fluid interface show the twice amount from a Pressure Tank from Pressure Pipes connected in 1 ME System with 1 Controller with a Fluid Storage Bus.
Its connected on a Tank Access port.

![2018-03-25_21 03 27](https://user-images.githubusercontent.com/29357962/37878895-22323b54-3070-11e8-8a3d-d79e4552fe1f.png)

![2018-03-25_21 03 31](https://user-images.githubusercontent.com/29357962/37878896-24562ad0-3070-11e8-9b7c-75fc232bf892.png)

MC : 1.12.2
AE2 : stable 11
AE2 Stuff : 0.7.0.4
ExtraCells: 1.12.2-2.5.11a48
Forge : 14.23.2.2635

**Comment by BrockWS** [comment]
Looks like an issue with the tank and not EC2, please post the issue on Pressure Pipes github instead

**Comment by TheSnowyChickens** [comment]
Oh okay, thx for this info.

Done. (Someone else already created a thread for this bug, but I'm just gonna post it under this post)
