### ISSUE TITLE
Extracells doesn't handle fluids with NBT

### ISSUE THREAD

**Issue by Xiaminou** [ExtraCells/ExtraCells2#557]
I am trying to use extracells to transport Thermal Expansion's Potion fluid which uses NBT to determine its effects, however Extracells is not properly handling it and I cannot import or export it.

Minecraft: 1.12.2
Forge: 2673
Mods: [list.txt](https://github.com/ExtraCells/ExtraCells2/files/1960768/list.txt)

**Comment by Keridos** [comment]
This is fixed upstream (meaning AE2)

**Comment by ruifung** [comment]
Technically it's still a PR on the AE2 side, that being said, I'm not sure how relevant that is as this is for rv5, not rv6 which has fluid handling built in rather then handled by EC2.

**Comment by Keridos** [comment]
It is merged now and released, this can be closed.
