### ISSUE TITLE
requestItems api on ME upgrade only works if you have at least 1 item already in the selected slot

### ISSUE THREAD

**Issue by JesusFreke** [ExtraCells/ExtraCells2#559]
I was playing around with the ME upgrade for opencomputers. The only way I could get the requestItems functionality to work is if I had at least 1 of the desired item in the robot's inventory, in the currently selected slot.

e.g.

    me = component.upgrade_me
    me.store({name = "minecraft:coal"}, component.database.address, 1)
    me.requestItems(component.database.address, 1, 1)

If the currently selected slot is empty, then the requestItems function does nothing and returns 0. If the slot has at least 1 coal, it grabs another coal from the network and returns 1, as expected.

**Comment by ShadowTheAge** [comment]
Can confirm the issue

**Comment by alandoyle95** [comment]
can still confirm this issue. not to mention there is next to no documentation on this item at all... would be nice to have some.

**Comment by JesusFreke** [comment]
Agreed. I had to look at the source to figure it out

**Comment by alandoyle95** [comment]
do you happen to remember where its buried in the source? lol

**Comment by JesusFreke** [comment]
You should be able to grep for "requestItems". iirc, I think there may be some code in the opencomputers codebase as well, although I don't recall if this upgrade uses it, or if it's for interacting with ME via a non-robot computer and adapter.

**Comment by alandoyle95** [comment]
https://github.com/ExtraCells/ExtraCells2/blob/rv5-1.12/src/main/scala/extracells/integration/opencomputers/NetworkControl.scala

for anyone that hits this page looking for the same thing.....

thanks by the way.

**Comment by JesusFreke** [comment]
Yep, That's the one. The api functions seem to be the ones with the `@Callback` annotation

**Comment by JesusFreke** [comment]
Also, one other thing that I got hung up on, is that you need to place the upgrade into a security station to link it to your ME system. I guess it's obvious if you've used the wireless terminal before, but I was trying to use this upgrade before I had done anything with the wireless terminal, so I wan't familiar with how linking was performed.

**Comment by BrockWS** [comment]
The EC2/OC integration is strange but this issue should be fixed. Just have to get it merged

**Comment by alandoyle95** [comment]
Awesome sir! Thanks!
