### ISSUE TITLE
Phantom memory issues in EC monitors.

### ISSUE THREAD

**Issue by AnrDaemon** [ExtraCells/ExtraCells2#560]
Both Storage/Conversion Monitor and Level Emitter have phantom memory issues.
They do not react to storage changes, and even after server reboot level emitter will happily report existence of a fluid that is nowhere to be seen in the system, and not even a chance of it being stored is available.
This is for all MC versions from 1.7.10 to 1.12.2.

**Comment by BrockWS** [comment]
I am unable to reproduce, can you please provide steps to reproduce and some screenshots if possible. Are you also trying with the latest version.

**Comment by AnrDaemon** [comment]
Place ME drive, insert fluid storage cell into it.
Draw a length of cable away (5-7 meters, so that you could cut the middle).
Attach Creative Energy Cell near the drive.
Attach fluid level monitor about the middle. Set monitor to display water.
Attach fluid level emitter and fluid annihilation plane(facing down) to the other end of the cable.
Set level emitter to emit when storage is above 80k.
Create a pool of infinite water under plane. It should start filling the cell and monitor will display the cell contents.
Wit till the cell is full, then take the cell out of the drive.
Both level emitter and monitor will happily display the nonexistent storage levels, until you reload the world.

**Comment by BrockWS** [comment]
This is an issue with AE2. I'll see what can be done.
