### ISSUE TITLE
Ore Dictionary Export Bus crashing with Crafting Patterns in Interfaces

### ISSUE THREAD

**Issue by Revelence** [ExtraCells/ExtraCells2#563]
Minecraft 1.12.2
Forge-14.23.3.2678
Applied Energistics 2 rv5-stable-11
ExtraCells2 1.12.2-.2.13a56

Crash Report: https://pastebin.com/nteXuxwD

CTD whenever I insert a crafting pattern into an interface on a network that has an active Ore Dictionary Export Bus (ODEB),

Also happens when I active an ODEB on a network that has an interface with crafting patterns in it.

Both the ODEB and interfaces with crafting patterns work without issue independently but crash when on the same ME network as each other, whether on same or separate channels, configuration in relation to each other does not appear to matter.

**Comment by oa10712** [comment]
Similar sitation for me, the server crashed when i placed and set an entry: https://pastebin.com/xUmkKmvd

**Comment by PaulVlahosCS** [comment]
Same crash and situation here.

Crash Log: https://pastebin.com/ysYZPrfx

The modpack is FTB: Revelation with 4 or 5 custom mods.

Minecraft Version: 1.12.2

AE2 Version: rv5-stable-11

Extra Cells 2 Version: 2.5.13

Forge Version: 14.23.2.26.27

**Comment by danzio** [comment]
Similar situation:
https://pastebin.com/uKV7CKjE

**Comment by Revelence** [comment]
Just booted up my world to test, can confirm for myself at least that I'm no longer crashing out when activating the ODEB on a network with the interfaces.
