### ISSUE TITLE
Deprecate Fluid Cells and Fluid Buses

### ISSUE THREAD

**Issue by BrockWS** [ExtraCells/ExtraCells2#566]
Once AppliedEnergistics/Applied-Energistics-2#3510 is merged, the following should be deprecated and eventually removed.

- [x] 1k-64k Fluid Cells
- [x] Fluid Import Bus
- [x] Fluid Export Bus
- [x] Fluid Storage Bus
- [x] Fluid Terminal

Would be best to change item names to state this and add conversion recipes for this purpose.

**Comment by p455w0rd** [comment]
Will do, and thank you for the work on the AE2 Fluid PR :)
