### ISSUE TITLE
[any fluid] Cell (Tech Reborn) gets NBT tag when emptied in the Fluid Terminal

### ISSUE THREAD

**Issue by jottafan** [ExtraCells/ExtraCells2#567]
https://github.com/FTBTeam/FTB-Continuum/issues/201

**Comment by BrockWS** [comment]
Looks like an issue with TR, only happens when placed back into the players inventory and not when emptied by the terminal

**Comment by modmuss50** [comment]
Im not sure if this is on us or you, as `setContainerToEmpty` should be called from FluidHandlerItemStack.drain removing that tag. 

How are you getting the drained item?

**Comment by BrockWS** [comment]
The draining code is here [Fluid Terminal](https://github.com/ExtraCells/ExtraCells2/blob/af507a0235fd287e656847f7ee1e1812a361554a/src/main/scala/extracells/part/fluid/PartFluidTerminal.java#L130-L140) and [FluidHelper](https://github.com/ExtraCells/ExtraCells2/blob/af507a0235fd287e656847f7ee1e1812a361554a/src/main/scala/extracells/util/FluidHelper.java#L18-L28).

Not sure what you mean with `setContainerToEmpty` but the code that adds the NBT Tag `Fluid:{}` is from [DynamicCell](https://github.com/TechReborn/TechReborn/blob/7124ee6a11e10e15503cf0aec35fd6a3aabd7eea/src/main/java/techreborn/items/DynamicCell.java#L70-L81) which the comments say something about breaks ability to use in recipes.

**Comment by modmuss50** [comment]
![java_2018-07-16_21-59-55](https://user-images.githubusercontent.com/4324090/42783340-a534e8ae-8943-11e8-8435-5c76e3d90319.png)

Seems to work fine, I believe the issue was due to recipes in the mod pack.

**Comment by jottafan** [comment]
And when u put the cell in yor inventory its still fine?
