### ISSUE TITLE
64 stones uses 520 bytes with 64k storage cell but uses 2056 bytes with 256k storage cell in MC1.12.2

### ISSUE THREAD

**Issue by rirubear** [ExtraCells/ExtraCells2#568]
I tested with 64k storage cell and 256k storage cell.
I put 64 stones into both cell.

64k: 64 stones uses 520 bytes
256k: 64 stones uses 2056 bytes

Is this a bug?

**Comment by BrockWS** [comment]
This is intended, happens with AE2 1/4/16k Cells.
You can considered it an overhead for being able to store alot more in each cell. Every type used has this overhead.
