### ISSUE TITLE
Native AE2 Fluid support

### ISSUE THREAD

**Issue by pupnewfster** [ExtraCells/ExtraCells2#570]
Now that AE2 is adding fluid cell support in v6 it would be nice if Extra Cells extended this like they do item storage. This way there won't be duplicate cells when both are included.

I understand that this probably will take a while given you probably have your own API for fluid storage, but I am making an issue so that people remember.

**Comment by ruifung** [comment]
I'm sure they are well aware, as DrummerMC seems to be also involved in the AE2 fluid system. (I've seen some commits by him in there.)

**Comment by BrockWS** [comment]
All we should need to do is deprecate and add conversion recipes for the items that were added to AE2 as EC2 already uses the fluid channel stuff in AE2. Follow #566 for progress

**Comment by pupnewfster** [comment]
Didn't see that other issue when I was searching for any reference of the ae2 fluid system so I will close this as one is already open.
