### ISSUE TITLE
Enigmatica 2 1.41, MC 1.12 - Storage cells causing Ae2 network lockout/crash(possibly)

### ISSUE THREAD

**Issue by rbjustin** [ExtraCells/ExtraCells2#573]
Heyah,

I just reached a point where I can utilize extra cells 2 storage drives but I've run into a strange issue.

When I put it in the main ME drive system, and try to move/insert items into my storage, it basically locks up the Ae2 storage, I cant remove items, interact with anything till I restart the server. Then I can do it once, and I ruin into the same issue, complete lock out, it's like its shutting down the ae2 network.

Was wondering if there's any known issues regarding the item storage component of ec2.

using ver 2.5.13a60

steps to reproduce:

make ME 256k Storage cell
Insert into ME drive array, which is connected to ME controller using ME dense smart cable.
Open ME crafting terminal
Try to interact with anything in it (total lock out)

Lights are still on, everything is showing as online.

Please advise.

Thanks!

**Comment by BrockWS** [comment]
Fixed in #572, but for now you should use version 1.42 of the modpack
