### ISSUE TITLE
AE2 rv6 API breaking changes

### ISSUE THREAD

**Issue by vrork** [ExtraCells/ExtraCells2#578]
https://paste.dimdev.org/zukidifira.mccrash

ExtraCells-1.12.2-2.5.13a60
 Forge 14.23.4.2735

EDIT(by ruifung): For anyone having crashes with ExtraCells-1.12.2-2.5.13 (latest on curseforge at this time), please do check if you are running AE2 RV6 ALPHA. There's been a bunch of API breaks in AE2 RV6. At this point in time (20/06/2018) AE2 RV6 is still in ALPHA.

**Comment by Matakor** [comment]
Getting an identical crash. This one is very, VERY weird, as not two hours ago I was able to play fine, and I haven't changed ANYTHING since. Now, all of a sudden, it's not working.

Same EC2 vers
Forge 14.23.4.2736

EDIT: I should note that I have a personal server currently running the same pack with no changes, and it hasn't had any issues.

**Comment by ruifung** [comment]
AE2 API breaking change. Note that AE2 rv6 is *still* in alpha.
@vrork Use AE2 RV5 for now.

See: https://github.com/AppliedEnergistics/Applied-Energistics-2/pull/3586

**Comment by Matakor** [comment]
That is odd, because my server is running AE2 rv6 alpha 3, and I was able to play with it for a few hours before this happened.

Not to mention I've been playing with rv6 since a couple days after it came out.

**Comment by ruifung** [comment]
Probably just didn't have anything active at the time that triggers this code path.

**Comment by Matakor** [comment]
Still, it doesn't quite make sense as to why I can repeatedly load my server, but not my client. The pack is identical between them. Why would the client fail?

**Comment by ruifung** [comment]
Probably because the server doesn't need to populate the search index. As far as I know, searching in minecraft is entirely client sided.

I assume the server would start having issues as soon as anything calls the method in question.

**Comment by Furious1964** [comment]
Hope this will be solved soon so I can update AE2.

**Comment by Matakor** [comment]
Well, for now AE2 rv6 Alpha2 does work.

**Comment by EdMistic** [comment]
I'm having a similar issues to this. But I'm on the latest stable version of AE2. I broke a crafting terminal and my whole server crashed. I haven't been able to load my server since.

**Comment by ruifung** [comment]
@edmisticgamer Based on your crash report in that other issue, you most definitely are not  using the latest stable AE2,  You're using rv6-alpha2.

**Comment by Morpheus1101** [comment]
I get the same crash using AE2 rv6 Alpha3 .. It worked fine in Alpha1

**Comment by Pythonic-Rainbow** [comment]
If I downgrade to rv5, Wireless Crafting Terminal requires rv6

**Comment by ruifung** [comment]
@Pythonic-Rainbow I just checked and the latest released versions on curseforge are apparently for RV5?

**Comment by Matakor** [comment]
@ruifung Negative, the latest on curseforge is RV6 Alpha3.

https://minecraft.curseforge.com/projects/applied-energistics-2/files

It's not the stable channel, sure, but many of us prefer to use the latest versions to help troubleshoot/etc. So, it's still an issue. I don't have this crash with alpha2, but if I update to alpha3 it breaks.

**Comment by ruifung** [comment]
My previous comment about the latest released version was referring to the WCT mod. Which at the time I checked, had its latest release version reverted to rv5.

Note that with AE2 in alpha, their official website (ae-mod.info) has a warning on the download page that goes as follows:

```
These builds are considered unstable, they may contain item dupes, deletions or other world ending bugs these builds are for TESTING ONLY.
Alpha builds are not compatible with any AE2 addons, do not request add-on authors or other mod developers to support these builds.
```
In addition, from what I can tell, AE2 is reworking some of its internals, so you can probably expect it to keep breaking as AE2 rv6 development progresses.

So yeah, personally I'd say stick with RV5 for now, there's a PR open that covers compatibility with the alpha versions, but you'd probably have to compile them from source for now.

**Comment by Pythonic-Rainbow** [comment]
@ruifung thanks , fell back my WCT to Build 66 that supports RV5 specifically

**Comment by Morpheus1101** [comment]
So basically what is being said is, suck it up, we arent updating any code until its out of Alpha?

**Comment by Pythonic-Rainbow** [comment]
@Morpheus1101 yes

**Comment by Pythonic-Rainbow** [comment]
@ruifung I saw Wireless Crafting Terminal supporting RV6 and AE@ has RV6a4 now

**Comment by p455w0rd** [comment]
sorry ppl...this is just how it's gotta be..you won't have to wait much longer..as soon as RV6-Stable-1 is released, I'll update EC2 accordingly...WCT has versions that support both RV5 and RV6..look at the jar titles on curseforge..the most recent 'release' versions are for RV5...latest 'beta' are for RV6...updating EC2 right now would just cause more headaches for me as far as version mismatching..sorry..if you want ae2 out faster...pray to your creator is all i can offer for you to do...yueh and fscan are working hard to ensure that RV6 is not only an all around better version of AE2, but more efficient as far as memory/cpu usage.he's shown me JVisualVM screenshots..things are looking really nice, but this stuff takes time...

**Comment by CarlucciMods** [comment]
AE2 rv6 Beta 1 is out and not playing nice with extra cells......I know waiting for stable, but based on what he said, this version is pushable which means, as a modder myself.....would be nice to get a fix in on the extra cells side...PS GREAT WORK ON YOUR MOD.........GREAT WORK.....


java.lang.NoSuchMethodError: appeng.api.storage.ICellRegistry.getCellInventory(Lnet/minecraft/item/ItemStack;Lappeng/api/storage/ISaveProvider;Lappeng/api/storage/IStorageChannel;)Lappeng/api/storage/IMEInventoryHandler;
	at extracells.item.storage.ItemStorageCell.func_77624_a(ItemStorageCell.java:48)
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:707)
	at net.minecraft.client.Minecraft.lambda$populateSearchTreeManager$1(Minecraft.java:575)
	at net.minecraft.client.Minecraft$$Lambda$1931/1085954667.apply(Unknown Source)
	at net.minecraft.client.util.SearchTree.func_194042_b(SourceFile:49)
	at net.minecraft.client.util.SearchTree.func_194043_a(SourceFile:44)
	at net.minecraft.client.Minecraft$$Lambda$1951/189051241.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at net.minecraft.client.Minecraft.func_193986_ar(Minecraft.java:589)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:528)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at extracells.item.storage.ItemStorageCell.func_77624_a(ItemStorageCell.java:48)
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:707)
	at net.minecraft.client.Minecraft.lambda$populateSearchTreeManager$1(Minecraft.java:575)
	at net.minecraft.client.Minecraft$$Lambda$1931/1085954667.apply(Unknown Source)
	at net.minecraft.client.util.SearchTree.func_194042_b(SourceFile:49)
	at net.minecraft.client.util.SearchTree.func_194043_a(SourceFile:44)
	at net.minecraft.client.Minecraft$$Lambda$1951/189051241.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at net.minecraft.client.Minecraft.func_193986_ar(Minecraft.java:589)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:528)

**Comment by BrockWS** [comment]
EC2 will be updated soon, we have been working on it but as we are not 100% familiar with the code its going to take time

**Comment by p455w0rd** [comment]
other projects are just more important atm..AE2 supporting fluids natively should take away most of the need for EC2 anyway...Brock is working hard on Thaumic Energistics atm, and I have some AE2 sub projects myself that I'm working on and need to be ready either at RV6-Stable release are as shortly after as possible...I'm doing my best to get things done BEFORE stable hits..but I also have 14 other personal projects plus a couple others I help maintain..I'm only one person...EC2 will not be forgotten...It's just not priority atm
