### ISSUE TITLE
Crash upon breaking a crafting terminal. 

### ISSUE THREAD

**Issue by EdMistic** [ExtraCells/ExtraCells2#582]
I created a server for a modpack I made and had no issues until now. I had an AE2 ME system going and a storage cell from extra cells 2. I went to break the crafting terminal and the whole server crash (Just the server, the game had no issues.). Now I can't even start the server without it crashing on startup. Here is the pastebin link to the crash log. https://pastebin.com/bwmzSbB9 . Can anyone help me out here? Thanks!

**Comment by Nedelosk** [comment]
Duplicate of #578
