### ISSUE TITLE
Extra Cells (1.12.2) crash when Minecraft is loading :(

### ISSUE THREAD

**Issue by Migmag789** [ExtraCells/ExtraCells2#583]
Hey ! I was launching my game, with Extra Cells, and poof! crashes.. Can you help me please ? :)
Thank you :D 
[crash-2018-07-19_11.59.09-client.txt](https://github.com/ExtraCells/ExtraCells2/files/2209417/crash-2018-07-19_11.59.09-client.txt)

**Comment by BrockWS** [comment]
Duplicate of #578
