### ISSUE TITLE
Bug Dupe Liquid XP from OpenBlocks

### ISSUE THREAD

**Issue by LehensGivris** [ExtraCells/ExtraCells2#595]
When we put an "XP Bucket" from the mod OpenBlocks in the Fluid Terminal, it adds 1000mb of Liquid XP in the terminal but does not empty the bucket and therefore duplicates it.
When using a "Liquid Bucket XP" from the mod Cyclic, there is no problem.
When I take a bucket of Liquid XP, I get a Liquid XP Bucket from the mod Cyclic.

I am on a reduced version of modpack "All the Mods 3" in 1.12.2 available on Curse.
My forge version: forge-14.23.4.2715 1.12.2 (modded)
My version of the Extra Cell 2 mod: ExtraCells-1.12.2-2.5.13a60
My version of the mod Applied Energistics 2: appliedenergistics2-rv5-stable-11
My version of Openblock: OpenBlocks-1.12.2-1.7.6
My version of Cyclic: Cyclic-1.12.2-1.15.15

**Comment by carlucci9660** [comment]
same issues, also having: java.lang.NoSuchMethodError: appeng.api.storage.ICellRegistry.getCellInventory(Lnet/minecraft/item/ItemStack;Lappeng/api/storage/ISaveProvider;Lappeng/api/storage/IStorageChannel;)Lappeng/api/storage/IMEInventoryHandler;
	at extracells.item.storage.ItemStorageCell.func_77624_a(ItemStorageCell.java:48)

with new beta 1 rv 6 AE2
