### ISSUE TITLE
anyone know how to download the new .jar for rv 6-alpha1 (beta-1)

### ISSUE THREAD

**Issue by CarlucciMods** [ExtraCells/ExtraCells2#599]
anyone know how to download the new .jar for rv 6-alpha1 (beta-1)

**Comment by Zer0Lyfe** [comment]
Open powershell or command prompt in the folder by holding shift + right clicking and picking either:command prompt or powershell and type in either:

**Command Prompt:** gradlew build
**Power-shell:** ./gradlew build
**mac/Linux:** I'm not too sure how to open it at direct it to the folder but the command should the same as power-shell.

**Comment by CarlucciMods** [comment]
Yea, I just want a .jar file.....that's all I asked for.

**Comment by BrockWS** [comment]
There is still work to be done for rv6 so there is no official download. If you want it so bad, go compile it yourself, else please just wait.

**Comment by CarlucciMods** [comment]
No need to be rude. I'm sorry if I came off demanding, it just sounded like
there was a fix for it and a new update was issued so I was looking for it
I couldn't find it. That's why I asked what's with the attitude

**Comment by CarlucciMods** [comment]
Maybe you can explain to me what folder you're talking about
