### ISSUE TITLE
Build Failed when trying to download newest rv6 update

### ISSUE THREAD

**Issue by CarlucciMods** [ExtraCells/ExtraCells2#601]
5 warnings found
:compileScala FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileScala'.
> java.io.IOException: Cannot run program "C:\Program Files\Java\jre1.8.0_181\bin\javac": CreateProcess error=2, The system cannot find the file specified

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 25.656 secs

**Comment by CarlucciMods** [comment]
downloaded Java JDK, but still doesnt work

**Comment by CarlucciMods** [comment]
Managed to get it built, thanks for all the hard work. Im a modder so I know people making constant demands is not welcomed...i was just lost and didnt know what one of the developers meant when he came out with a fix...plus i never really use github...shocking... please see photo, which build do I use.
![capture](https://user-images.githubusercontent.com/31194015/46260564-ab7caf00-c4b5-11e8-8137-f3fb3ac5c76e.PNG)

**Comment by carlucci9660** [comment]
Managed to get it built, thanks for all the hard work. Im a modder so I know people making constant demands is not welcomed...i was just lost and didnt know what one of the developers meant when he came out with a fix...plus i never really use github...shocking... please see photo, which build do I use.
![capture](https://user-images.githubusercontent.com/31194015/46260564-ab7caf00-c4b5-11e8-8137-f3fb3ac5c76e.PNG)
