### ISSUE TITLE
[1.12.2] Useful Info Needed to be Noted

### ISSUE THREAD

**Issue by PulseBeat02** [ExtraCells/ExtraCells2#604]
Applied Energestics 2 recently released a new stable version a couple hours ago. Extra Cells 2 still doesn't work even with the new stable version of AE2. However, the only working version was the last stable version of AE2, or, rv5-Stable-11. If possible, maybe add compatibility between the two mods, because the new version of AE2 fixes many major bugs. This post was not meant to be a problem, it was just so other people could note this.

**Comment by p455w0rd** [comment]
the AE2 API completely changed in RV6...compat is just not feasible..updating is, and it will happen..in time

**Comment by CarlucciMods** [comment]
Gosh everyone is so demanding no matter what game, modders do this for us....they have lives too....be patient.....

**Comment by PulseBeat02** [comment]
@carlucci9660 I am not demanding an update. This was a reminder for other people NOT THE DEVELOPERS. I am a modder also, and I get how hard it is ok.
