### ISSUE TITLE
[Request - 1.12.2] Option to exclude specific things

### ISSUE THREAD

**Issue by Chr0n4s** [ExtraCells/ExtraCells2#608]
If you are using for example "ore*" to pulverize all ores and "dust*" to make the ingots in a furnace the furnace will also burn all "coalDust". But coalDust is needed for many recipes.

My suggestion is to make something like this for the Ore Dictionary Export Bus:
"dust*;-dustCoal"

So u can specify some things u don't wont to pull. Also u can specify multiple single ore dicts.
E.g. "dustIron;dustGold"

**Comment by ruifung** [comment]
Fixed in 64fba68e11dc20c3516776eff457c4b5a5004e58
