### ISSUE TITLE
ME Gas Level Emitter is behaving like ME Liquid Level Emitter but with a different GUI

### ISSUE THREAD

**Issue by nowifi4u** [ExtraCells/ExtraCells2#617]
o/

The ME Gas Level Emitter is like ME Liquid Level Emitter: you can set it up for any liquid (and it will work for that liquid), but not for gasses like intended.

Versions:
AE2: appliedenergistics2-rv6-stable-3
ExtraCells2: ExtraCells-1.12.2-2.6.1a

![image](https://user-images.githubusercontent.com/36640388/49543388-28c70480-f8e9-11e8-9f0a-08aecabef379.png)
![image](https://user-images.githubusercontent.com/36640388/49543408-367c8a00-f8e9-11e8-9a5d-45cab4e4c693.png)

_Originally posted by @nowifi4u in https://github.com/ExtraCells/ExtraCells2/issues/606#issuecomment-444644445_

**Comment by ShibaRoTatsuya** [comment]
I am having the same issue on versions
ExtraCells-1.12.2-2.6.2a
appliedenergistics2-rv6-stable-6.jar

![javaw_2019-03-14_21-42-55](https://user-images.githubusercontent.com/48546834/54409102-3804dd80-46a2-11e9-9ea3-73e271adef73.png)
![javaw_2019-03-14_21-43-01](https://user-images.githubusercontent.com/48546834/54409105-3a673780-46a2-11e9-91f0-2797de38fe79.png)

**Comment by zjeffer** [comment]
Duplicate of #520
