### ISSUE TITLE
Crash with new Wireless Crafting Terminal library

### ISSUE THREAD

**Issue by rainbowskydancer** [ExtraCells/ExtraCells2#624]
Pastebinning crash report here: https://pastebin.com/Kw06YaTc

Clients crashes totally to launcher. Seems WCT changed some API thing so extra cells goes "ohmegerd where's the library?!"

**Comment by rainbowskydancer** [comment]
(sorry about PEBKAC I hit enter instead of shift when writing the report up...)

**Comment by BrockWS** [comment]
Duplicate of #619. You can use the build located here until its up on CF. https://ci.brock.pw/job/ExtraCells2/job/ExtraCells2-RV6/4/
