### ISSUE TITLE
crash plz help

### ISSUE THREAD

**Issue by Noobje130** [ExtraCells/ExtraCells2#626]
[crash-2018-12-28_21.35.24-client.txt](https://github.com/ExtraCells/ExtraCells2/files/2715654/crash-2018-12-28_21.35.24-client.txt)

**Comment by LemADEC** [comment]
Issue is fixed in dev, we're pending mod author to push a new version on Curse

**Comment by Nedelosk** [comment]
[Fixed Version](https://minecraft.curseforge.com/projects/extracells2/files/2653854)
