### ISSUE TITLE
Adding Crafting Terminal to Universal Wireless Terminal causes crash

### ISSUE THREAD

**Issue by UmbraEterna** [ExtraCells/ExtraCells2#632]
Hello,

I am posting this here, but I will also report it to WCT, since it seems to be an interaction issue between the two. I can use the Wireless Crafting Terminal and the Universal Crafting Terminal independent of each other successfully. I can even successfully add the crafting module to the UCT, but upon trying to open the GUI for the crafting module of the UCT my game crashes. I think that your UCT is trying to use the GUI from the Wireless Crafting Terminal as its GUI for the crafting module. (It is my assumption from reading what I can understand from the crash log)

[Link to the crash log](https://gist.github.com/UmbraEterna/b8ae8002a6fd1d422b41349820870124)

**Comment by UmbraEterna** [comment]
Fixed with Extra Cells 2.6.3a

**Comment by CARA560** [comment]
If you updated to the newest version of extra cells (2.6.5) you think it might work ?
