### ISSUE TITLE
Crafting mode on Universal Wireless Terminal doesn't work

### ISSUE THREAD

**Issue by UmbraEterna** [ExtraCells/ExtraCells2#633]
All other addable modes to the UWT work, but the crafting mode. Right-clicking simply makes the animation of trying to open a UI, but nothing actually happens. Nothing is reported in the Minecraft log.

**Comment by Fireztonez** [comment]
I get the same Issue, I can't access the wireless crafting terminal with the unifersal one :(...

I have installed Wireless Crafting Terminal version 3.11.88
Applied Energistics 2 : RV6-Stable-6
Extra Cell 2 : v.2.6.2 a
Forge: 14.23.5.2806
