### ISSUE TITLE
Tech Reborn Dupe

### ISSUE THREAD

**Issue by Fargaze** [ExtraCells/ExtraCells2#635]
The dupe happens when inserting any Tech Reborn cell into the ME Fluid Terminal. It inserts the fluid into the system and instead of returning a empty cell it will return a full one. 
![2019-01-15_23 55 51](https://user-images.githubusercontent.com/4890935/51218079-b0f5ec00-1922-11e9-95bf-47aa034b7ac0.png)

Modpack is FTB Continuum v1.5.2
Extra Cells 2.5.13a60
Tech Reborn 2.17.4.824

**Comment by Fargaze** [comment]
Still an issue in FTB Continuum v1.6.0
Extra Cells 2.6.2a
Tech Reborn 2.20.1.889

**Comment by BrockWS** [comment]
With EC2 2.6.2a you can convert to the AE2 fluid terminal, the EC2 has been deprecated and shouldn't be used anymore.
