### ISSUE TITLE
Ore Dictionary Export Bus

### ISSUE THREAD

**Issue by NeyoSemperDux** [ExtraCells/ExtraCells2#652]
I would appreciate an in depth definition on what the filter on this bus is capable of. I know that ore* and oreIron etc works, but was wondering if there was ways of using this format to have several filters or exclude certain items from an overall filter. I am trying to figure out a way to let myself use ore* while excluding oreGold.

I appreciate and am thankful for any responses.

**Comment by NeyoSemperDux** [comment]
If anyone else finds this via google, I looked through the code and figured that ore*&!oreGold worked. I got it working with ore*&!oreGold&!oreIron to proceed to then start delivering coal too, however dustBasalz&ore*&!oreGold did not seem to work even when I tried it with dust* instead.

I would still like to see the proper syntax though from any Devs that might have worked on this element.

**Comment by ruifung** [comment]
Well, I've overhauled that oredict export bus syntax, will document it at some point when I can get this published to curseforge I guess.
