### ISSUE TITLE
[Infinite Crash] ME System With Any Fluid Storage

### ISSUE THREAD

**Issue by barkerm1031** [ExtraCells/ExtraCells2#656]
so basically i was playin on my friends server and thought to build a fluid storage network with extracells and AE2. so i connected everything as it should be and when i inserted a 4096k fluid storage cell it immediately crashed the server and she is now restoring from a backup.

Crash Report:
https://paste.dimdev.org/raw/facayediwe

**Comment by ruifung** [comment]
Was fixed in 55e5e99ad803a7f75e2ed91e949164cc8af74bc6.
