### ISSUE TITLE
Crashing due to a clash between two mods. AE2 and Extra Cells 2 

### ISSUE THREAD

**Issue by AwesomeBroDude** [ExtraCells/ExtraCells2#658]
Describe the bug
When I placed down a charger from AE2 for a wireless terminal, and placed my Wireless terminal into the charger, I instantly crashed. This also answers the question below.

Expected behavior
I expected the WT to start charging like it normally should.

Additional context
https://pastebin.com/eJiT2ykg - Crashlog for the very first time it happened. Havent been able to log into the world since.

Environment
https://pastebin.com/9rc1zLww - This is the listed mods in the pack.

The modpack I am using is StoneBlock 2(v1.15.0) Minecraft Version 1.12.2 - run through the FTB Launcher, not the Twitch launcher.

Minecraft Version:
AE2 Version: AE2WT - 1.0.30
AE2stuff - 0.7.0.4
Forge Version: N/A - Forge Multipart by Chickenbones

Extra Cells 2 Version: 2.6.3aNIGHTLY

**Comment by Sangohanssj** [comment]
Same as above but on the Ragnamod V modpack.
https://pastebin.com/Tm87Ae5W Crash log

Minecraft Version: 1.12.2
AE2 Version: stable rv6-stable-6 for Forge 14.23.5.2768
AE2stuff : 0.7.0.4  
Extracells : 2.6.2

**Comment by Shybella** [comment]
Yeah, can reproduce by placing a wireless crafting terminal in a ae2 charger. 

Steps on a temp fix, modify the configs below in the picture
http://prntscr.com/oprvim
http://prntscr.com/oprw9g

**Comment by dierke9** [comment]
Same problem with a player who reported this to me playing the Dungeons, Dragons and space shuttles pack.
Crash is the same as above, yet if log is needed let me know. These are the modversions of the build the player was using:

Applied energistics2: rv6-stable-6
Extra cells: 2.6.2
AE2WTLib: 1.0.6
forge: 14.23.5.2836

**Comment by ruifung** [comment]
Should be fixed as of the latest commit. Unfortunately I can't publish to curseforge.
