### ISSUE TITLE
Multiple Filters for ME Ore Dictionary Export bus not working.

### ISSUE THREAD

**Issue by astridos2go** [ExtraCells/ExtraCells2#659]
When attempting to add multiple filters to the ME Ore Dictionary Export bus, for example, `oreIron&oreGold` the export bus does not recognize the input. 

When I type `oreIron` or even `oreIron&` the export bus recognizes the filter and works. I can also type something like `oreIron&!oreCinnabar` and it will work correctly. 

As I would like to specify multiple filters for a single ME Ore Dictionary Export bus and the [code](https://github.com/ExtraCells/ExtraCells2/blob/a0ab63f4e86b5b5414881e0e7bab168229288e43/src/main/scala/extracells/part/PartOreDictExporter.java#L74) seems to support doing so just by using a `&`, I was just wondering why this is seemingly broken, or if I am missing something blatantly obvious.

I did not find the code by myself, it was used in a response to a post I made on [reddit](https://www.reddit.com/r/feedthebeast/comments/chgqr0/multiple_different_entries_for_extra_cells_2/) when I was trying to find out what logical operator could be used to define multiple filters.

Any help would be greatly appreciated! Thank you so much for your time!

**Comment by ruifung** [comment]
Fixed in 4f4d41b23f0dbe77860bdca58a6c1ee4a383324e

Definitely not on curseforge for now until I can get a hold of someone who can publish there.
