### ISSUE TITLE
[1.7.10] Fluid Interface liquid duplication 

### ISSUE THREAD

**Issue by rsg888** [ExtraCells/ExtraCells2#662]
Basically , #562 is still present in the latest version of the mod for 1.7.10. It seems to be an easy fix - the issue is exactly the same - a "return;" is missing. However,  I can`t even test that because the ae rv3-beta6 API seems to be gone from the repository(along with some other dependencies).It would be really nice if somebody could compile a version with a fix , but just getting those dependencies would be greatly appreciated too.
Gradle build log : https://pastebin.com/0EXHBYGH

**Comment by ruifung** [comment]
If you can't compile it for that reason, neither can I.
You might have to compile most of the dependencies from source for that.
