### ISSUE TITLE
Ore Dictionary Export wildcard

### ISSUE THREAD

**Issue by DarkEyeDragon** [ExtraCells/ExtraCells2#667]
exporting ores with wildcards seems to skip ores that are in ore dictionary.

![image](https://user-images.githubusercontent.com/6131099/66237439-5a6d4f80-e6f5-11e9-9931-baff03812f47.png)
this works.

![image](https://user-images.githubusercontent.com/6131099/66237480-6ce78900-e6f5-11e9-91cd-4412520aacc2.png)
however this does not export the black quartz. This also seems to exclude Osmium from Mekanism and some other ores. However it does process Copper from Mekanism fine

**Comment by ruifung** [comment]
I suspect this is because EC2 loops through all items in AE and tries to export the first matching item it finds... if that first matching item fails to export... it just gives up.... and on the next tick.. it would proceed to do the same thing all over again.
