### ISSUE TITLE
NoClassDefFoundError: extracells/item/ItemWirelessTerminalUniversal [ExtraCells-1.12.2-2.6.3]

### ISSUE THREAD

**Issue by nephatrine** [ExtraCells/ExtraCells2#669]
Updated to ExtraCells-1.12.2-2.6.3 and am now getting a crash on server start:

https://pastebin.com/urM5DLbt

Reverting back to ExtraCells-1.12.2-2.6.2a resolved the issue.

**Comment by ruifung** [comment]
*sighs* Looks like @Optional.Interface isn't working for whatever reason. Which is funny, because I never even touch that part, I just implemented the missing methods for this according to said interface. Hmm.
