### ISSUE TITLE
Extra Cells 2.6.4, MC 1.12.2, ME Drive Fixture led display wrong.

### ISSUE THREAD

**Issue by Splutty** [ExtraCells/ExtraCells2#683]
https://i.imgur.com/avFAqmO.png

When a storage drive is full, the led is supposed to be orange or red, but the Fixture renders it as a green line to the left leaving the led transparent showing the cabling behind it.

**Comment by Splutty** [comment]
The coordinates seem off by one, but I've left that in place. The issue is in part/drive_cell_types_full.json.

For the Cell Light entry, this needs to be fixed:
         "uv": [
            0,
            4,
            3,
            6
          ],

(That was 0,4,6,3)

**Comment by ruifung** [comment]
Thanks, I'll see about getting this in soon.
