### ISSUE TITLE
Getting IncompatibleClassChangeError on startup

### ISSUE THREAD

**Issue by Fenekhu** [ExtraCells/ExtraCells2#687]
I saw a closed thread from november 2019 saying the problem was solved but I'm using 2.6.5 and still getting the error

Crash Report: https://pastebin.com/apmbUfeR

**Comment by Shad0wlife** [comment]
You seem to be using XCPatch by shadows_of_fire, which is listed as Incompatible with 2.6.5 on curseforge (also mentioned in the description). So you might want to remove that.
