### ISSUE TITLE
ME Gas Terminal Will only display the Gas Amount From one cell at a time.

### ISSUE THREAD

**Issue by oxgen1** [ExtraCells/ExtraCells2#688]
Minecraft Version: 1.12.2
Extra Cells 2 Version: 2.6.5
Forge Version: 14.23.5.2847
Applied Energistics 2 Version: rv6-stable-7
 
Cell's in Position 3-5 are completely empty.
Cell 1 has: 
Cell 1 is 64K Gas Cell
Cell 2 is 4096K Gas Cell

With Cell 1 & 2 In:  
![image](https://user-images.githubusercontent.com/4802686/74883875-e946d580-533f-11ea-9207-6ec37796397e.png)
![image](https://user-images.githubusercontent.com/4802686/74883911-ffed2c80-533f-11ea-9bfe-13f75cf47936.png)

With Cell 2 In:
![image](https://user-images.githubusercontent.com/4802686/74883979-20b58200-5340-11ea-863c-56ed03822b74.png)
![image](https://user-images.githubusercontent.com/4802686/74883882-f06de380-533f-11ea-882d-ad71b12e8e99.png)

I did not get a picture but with 2 in and 1 Out it displays the same as with 1 & 2 in.

**Comment by turt2live** [comment]
This also appears to be an issue with the gas storage bus. I have 3 hooked up to individual gas tanks from Mekanism and the terminal is only showing one of the three.

**Comment by robertmaxton42** [comment]
Just chiming in to say that I have the same problem. The other cells will _fill_ just fine, but neither the terminal, nor the storage monitor, will acknowledge their existence. Scared me half to death when my sulfuric acid seemed to be just vanishing into the ether... >.>

**Comment by paulcooper12** [comment]
Yea I have this problem too, clearly a glitch that needs to be fixed. It only shows one at a time.

**Comment by Demonly** [comment]
@ruifung 
@Shad0wlife 

Do either of you have an update on this? Or could either of you point to where this value is built and I can probably take a look at fixing it. Otherwise this can be very annoying.

**Comment by Demonly** [comment]
@oxgen1 
@paulcooper12
@robertmaxton42
@turt2live

#708 

Will resolve this problem. You're welcome to build from my branch in the mean time.
