### ISSUE TITLE
Serverside Crash, unsure why

### ISSUE THREAD

**Issue by Jacob345k** [ExtraCells/ExtraCells2#692]
[crash-2020-03-11_10.33.59-server.txt](https://github.com/ExtraCells/ExtraCells2/files/4324831/crash-2020-03-11_10.33.59-server.txt)
Heres the crashlog, if you need any info ill respond quickly. Thanks!

**Comment by Jacob345k** [comment]
Aight, dead mod? cool, ill just remove it

**Comment by Shad0wlife** [comment]
How exactly did you get the idea that this mod causes the crash?

All I can find in the stacktrace that is mod specific is
`funwayguy.epicsiegemod.ai.ESM_EntityAINearestAttackableTarget`
So epicsiegemod seems to be the culprit. Some multithreading issue probably as its a concurrent modification exception while ticking a creeper entity...

Edit: I see you're using cubic chunks. That nof modifies some datastructures in the world and I remember there being issues with entities at some point. Maybe the entity handling there is not compatible with the siege mod?

**Comment by ruifung** [comment]
That log doesn't even have anything pointing to EC2. All I find is that epicsiegemod thing as mentioned above.

Also, 
Not dead, just really really busy IRL. I still do check on this from time to time, but I dont really have time to work on this... (i guess i have lots of time now with COVID-19 going around and so...)
