### ISSUE TITLE
Way to add multiple ore types to Ore Dictionary export bus?

### ISSUE THREAD

**Issue by Insyder28** [ExtraCells/ExtraCells2#693]
I would like to add multiple ore types to the export bus, because some ores need processing in one way, and others in another way. Using ore* doesn't work because it tries to export an ore type that won't go into that specific machine.

**Comment by ruifung** [comment]
Already supported

https://github.com/ExtraCells/ExtraCells2/wiki/Network#me-ore-dictionary-export-bus
