### ISSUE TITLE
Fluid Terminal behaves wrong with Galacticraft canisters

### ISSUE THREAD

**Issue by EoD** [ExtraCells/ExtraCells2#85]
I already reported it on the GC issuse tracker and they say it's probably ExtraCell's fault. 

micdoodle8/Galacticraft#1065
micdoodle8/Galacticraft#1131 

Basically, the fluid terminal 
- does not accept GC canisters (ExtraCells rv0)
- makes GC canisters unsusable (EC rv1 + GC build .224 and before)
- allows duplication of the GC canisters (EC rv1 + GC build .225 and later)

**Comment by DrummerMC** [comment]
try it with the newest rv2 version

**Comment by katzenpapst** [comment]
Hm, I had the issues with ExtraCells-1.7.10-2.2.65b97. Or at least one issue: if a partially-filled canister is placed into the fluid terminal, it's contents are added to the ME network, but the canister is not emptied. Galacticraft is GalacticraftCore-1.7-3.0.11.306
