### ISSUE TITLE
Digital Trade-o-mat?

### ISSUE THREAD

**Issue by excelcrafter** [ExtraCells/ExtraCells2#91]
what about monitor or terminal which can be used like digital trade-o-mat?

IC2 trade-o-mat in digital version or Gregtech trade-o-mat in digital version

it can access network and only the owner is able to break it or remove it...

one window what it wants another window what it gives...

hopefully idea for servers, lets trade together by the easier way...

**Comment by Ianaver** [comment]
that sounds like a very good idea!!!!!   :D

**Comment by excelcrafter** [comment]
we are alone here :-D
